/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.Combinatorics.ComplementaryOccurrencePairedWordCore
import AlgebraicComplexity.Combinatorics.ComplementaryOccurrenceProjectionProfile

/-!
# Paired words and complementary occurrence profiles

A recursive constituent stores two labelled child occurrences for each ordered parent state.
This file identifies that doubled child word with the two labelled marginals of the word of
parent pairs.  The right occurrence is transported through the complement permutation, so a
self-complementary state still contributes twice: once from each labelled half.

The dependency-minimal word identities live in `ComplementaryOccurrencePairedWordCore`.  The
theorem here turns exact multiplicity equations for the ordered-state word and doubled
child word into the normalized pooled-profile predicate used by parent concentration.  No
probabilistic feasibility or support condition is assumed separately.
-/

namespace AlgebraicComplexity
namespace ComplementaryOccurrenceLaw

universe u v

variable {State : Type u} [Fintype State] [DecidableEq State]
variable {Symbol : Type v} [Fintype Symbol] [DecidableEq Symbol] [Nonempty Symbol]
variable {profile : State → ℕ}

/-- Exact paired-word profiles instantiate the normalized pooled-parent projection model.

This is the finite semantic bridge required by the recursive CW target count: clients prove only
the two literal word-type equalities generated by their conditional type class. -/
theorem isPooledMarginalProfile_of_pairWords
    (law : ComplementaryOccurrenceLaw profile Symbol)
    (complement : Equiv.Perm State)
    (hmass : 0 < WordType.profileMass profile)
    (state : Fin n → State) (left right : Fin n → Symbol)
    (hstate : WordType.multiplicity state = profile)
    (hchildren :
      WordType.multiplicity (labelledChildWord complement state left right) =
        law.cellJointProfile complement id) :
    let M := law.toComplementaryProductProjectionModel complement hmass
    WordType.IsPooledMarginalProfile M.toSparsePooledMarginalProjectionModel
      (WordType.multiplicity (parentPairWord state left right)) := by
  apply law.isPooledMarginalProfile_of_mappedType_eq complement hmass
  · rw [mappedType_fst_multiplicity_parentPairWord, hstate]
  · intro childState symbol
    rw [pooledMappedType_multiplicity_parentPairWord, hchildren]

end ComplementaryOccurrenceLaw
end AlgebraicComplexity
