/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.Tensor.AsymptoticSliceRank
import AlgebraicComplexity.Tensor.Degeneration
import AlgebraicComplexity.Tensor.SliceRank
import AlgebraicComplexity.Tensor.SliceRankSaturation

/-!
# Slice rank along a polynomial degeneration

Alman's thesis (Proposition 5.1, quoting [TaoSawin2016, Corollary 2]) states that slice rank is
monotone under degeneration: `B ⊴ A` implies `S (B) ≤ S (A)` and hence `S̃(B) ≤ S̃(A)`.  This module
develops the certificate-level half of that statement for the constructive one-parameter
degenerations of `Tensor/Degeneration.lean` and isolates precisely what is missing.

## What is proved

Let `A` be a polynomial family of legwise linear maps and `T` a tensor with a slice decomposition
into `r` terms.

* `HasLeadingTerm.polynomialPure`: the leading term of a polynomial pure tensor is the pure tensor
  of the three leading coefficients, in the sum of the three orders.  This is the polynomial-vector
  bookkeeping the whole argument runs on, and it uses `PolynomialVector.order`, the least degree
  carrying a nonzero coefficient.
* `SliceTermAlong.exists_leading_sliceTermAlong`: transporting a *single* slice term along `c`
  produces a degree below which the path `polynomialTransform A T` vanishes and at which its
  coefficient is again a slice term along `c`.  The point is that all pure summands of a `c`-slice
  term share their leg-`c` vector `v`, so all of their transported leading coefficients share the
  leading coefficient of `A_c v`; slice terms with a *common vector* are closed under addition
  (`SliceTermWith` in `Tensor/SliceRank.lean`), which is what lets the surviving coefficients merge.
* `SliceRankLE.hasSliceLeadingBound` and `exists_leading_sliceRankLE`: consequently there is a
  degree `m` with `polynomialTransform A T n = 0` for all `n < m` and
  `SliceRankLE (sliceRank T) (polynomialTransform A T m)`.
* `SliceRankLE.of_hasLeadingTerm_of_le`: if such an `m` is at least the leading degree `d` of the
  path, the leading coefficient itself has slice rank at most `r` --- either `m = d` and the two
  coefficients agree, or `m > d` and the leading coefficient is zero.
* `sliceRank_le_of_polynomialDegeneratesAt_zero`: unconditional monotonicity for degenerations
  displaying leading degree `0`, where `d ≤ m` is automatic.
* `sliceRank_le_of_hasLeadingTerm`: thesis Proposition 5.1 under the hypothesis `d ≤ m`.

## The full statement

The certificate-level argument above only pins down the degree `m` at which the sum of the `r`
transported slice terms *can first* be nonzero.  Nothing prevents the leading coefficients of the
individual transported terms from cancelling, in which case `m < d` and the certificate says
nothing about the degree-`d` coefficient `S`.  Cancellation really does occur: with `x ⊗ y ⊗ z`
presented once as an `X`-slice and once as a `Y`-slice, the two leading coefficients cancel across
different legs.

Repairing this is the Zariski/valuative content of [TaoSawin2016, Corollary 2]; it is carried out
over a field in `Tensor/SliceRankSaturation.lean`, where the `K[λ]`-modules generated by the
transported slice vectors are replaced by saturated ones
(`exists_polynomialLinearMap_fixing_list`).  This module therefore only *imports* the result and
records its consequences:

* `sliceRankDegenerationMonotone_holds`: the named obligation `SliceRankDegenerationMonotone` is a
  theorem over every field.
* `sliceRank_polynomialDegenerates_le` and `asymptoticSliceRank_polynomialDegenerates_le` are
  unconditional over a field.

The `Prop` definition `SliceRankDegenerationMonotone` is kept as the universe-explicit packaging of
the statement --- it is no longer an obligation, and downstream theorems that still take it as a
hypothesis can discharge it with `sliceRankDegenerationMonotone_holds`.

## References

* J. Alman, *Limits on the Universal Method for Matrix Multiplication*, Ph.D. thesis, MIT, 2019,
  Proposition 5.1.
* T. Tao and W. Sawin, *Notes on the "slice rank" of tensors*, blog post, 2016, Corollary 2.
-/

namespace AlgebraicComplexity.Tensor

universe u v w

section Order

variable {M : Type*} [Zero M]

/-- The **order** of a polynomial vector: the least degree carrying a nonzero coefficient, and
`0` for the zero polynomial vector. -/
noncomputable def PolynomialVector.order (P : PolynomialVector M) : ℕ :=
  sInf {n | P n ≠ 0}

/-- Every polynomial vector has a leading term in its own order: all lower coefficients vanish,
by minimality of the order, and the coefficient in that degree is by definition the leading one.
For the zero polynomial vector the order is `0` and the statement is vacuous. -/
theorem PolynomialVector.hasLeadingTerm_order (P : PolynomialVector M) :
    HasLeadingTerm P P.order (P P.order) := by
  refine ⟨rfl, fun e he ↦ ?_⟩
  by_contra hne
  exact Nat.not_lt.mpr (Nat.sInf_le (Set.mem_setOf_eq ▸ hne)) he

end Order

section LeadingPure

variable {K : Type u} [CommSemiring K]
variable {V : Leg → Type v} [∀ c, AddCommMonoid (V c)] [∀ c, Module K (V c)]

/-- Coefficientwise description of a polynomial pure tensor: the degree-`n` coefficient collects
the pure tensors of all triples of coefficients whose degrees add up to `n`. -/
theorem polynomialPure_coeff (x : ∀ c, PolynomialVector (V c)) (n : ℕ) :
    polynomialPure (K := K) x n =
      ∑ dx ∈ (x .X).support, ∑ dy ∈ (x .Y).support, ∑ dz ∈ (x .Z).support,
        if dx + dy + dz = n then
          pure (K := K) (ofLegs (x .X dx) (x .Y dy) (x .Z dz)) else 0 := by
  classical
  simp [polynomialPure, Finsupp.sum, PolynomialVector.monomial, Finsupp.single_apply, eq_comm]

/-- **Leading term of a polynomial pure tensor.**  If the three polynomial vectors of a
polynomial pure tensor have leading coefficients `u c` in degrees `a c`, then the pure tensor has
leading coefficient `pure u` in the total degree `a X + a Y + a Z`.

Proof sketch: by `polynomialPure_coeff` the degree-`n` coefficient sums the pure tensors of
coefficient triples with `dx + dy + dz = n`, over the supports.  Every supported degree of leg `c`
is at least `a c`, so below the total degree no triple contributes, and in the total degree the
only possible triple is `(a X, a Y, a Z)`.  If some `a c` is unsupported, that triple is absent as
well, but then `u c = 0` and the pure tensor of `u` vanishes too. -/
theorem HasLeadingTerm.polynomialPure {x : ∀ c, PolynomialVector (V c)} {a : Leg → ℕ}
    {u : ∀ c, V c} (h : ∀ c, HasLeadingTerm (x c) (a c) (u c)) :
    HasLeadingTerm (Tensor.polynomialPure (K := K) x) (a .X + a .Y + a .Z)
      (pure (K := K) u) := by
  classical
  have hcoeff : ∀ c, x c (a c) = u c := fun c ↦ (h c).coeff
  constructor
  · rw [polynomialPure_coeff]
    by_cases hmem : a .X ∈ (x .X).support ∧ a .Y ∈ (x .Y).support ∧ a .Z ∈ (x .Z).support
    · obtain ⟨hX, hY, hZ⟩ := hmem
      rw [Finset.sum_eq_single (a .X)]
      · rw [Finset.sum_eq_single (a .Y)]
        · rw [Finset.sum_eq_single (a .Z)]
          · rw [if_pos rfl, hcoeff, hcoeff, hcoeff, ofLegs_eta]
          · intro dz hdz hne
            rw [if_neg]
            have := (h .Z).degree_le_of_mem_support hdz
            omega
          · intro hnot
            exact absurd hZ hnot
        · intro dy hdy hne
          refine Finset.sum_eq_zero fun dz hdz ↦ ?_
          rw [if_neg]
          have h1 := (h .Y).degree_le_of_mem_support hdy
          have h2 := (h .Z).degree_le_of_mem_support hdz
          omega
        · intro hnot
          exact absurd hY hnot
      · intro dx hdx hne
        refine Finset.sum_eq_zero fun dy hdy ↦ Finset.sum_eq_zero fun dz hdz ↦ ?_
        rw [if_neg]
        have h1 := (h .X).degree_le_of_mem_support hdx
        have h2 := (h .Y).degree_le_of_mem_support hdy
        have h3 := (h .Z).degree_le_of_mem_support hdz
        omega
      · intro hnot
        exact absurd hX hnot
    · have hzero : pure (K := K) u = 0 := by
        rcases not_and_or.mp hmem with hc | hc
        · have : u .X = 0 := by
            rw [← hcoeff]
            simpa using hc
          exact (PiTensorProduct.tprod K).map_coord_zero .X this
        rcases not_and_or.mp hc with hc | hc
        · have : u .Y = 0 := by
            rw [← hcoeff]
            simpa using hc
          exact (PiTensorProduct.tprod K).map_coord_zero .Y this
        · have : u .Z = 0 := by
            rw [← hcoeff]
            simpa using hc
          exact (PiTensorProduct.tprod K).map_coord_zero .Z this
      rw [hzero]
      refine Finset.sum_eq_zero fun dx hdx ↦ Finset.sum_eq_zero fun dy hdy ↦
        Finset.sum_eq_zero fun dz hdz ↦ ?_
      have h1 := (h .X).degree_le_of_mem_support hdx
      have h2 := (h .Y).degree_le_of_mem_support hdy
      have h3 := (h .Z).degree_le_of_mem_support hdz
      by_cases hsum : dx + dy + dz = a .X + a .Y + a .Z
      · exfalso
        have hxa : dx = a .X := by omega
        have hya : dy = a .Y := by omega
        have hza : dz = a .Z := by omega
        subst hxa; subst hya; subst hza
        exact hmem ⟨hdx, hdy, hdz⟩
      · rw [if_neg hsum]
  · intro n hn
    rw [polynomialPure_coeff]
    refine Finset.sum_eq_zero fun dx hdx ↦ Finset.sum_eq_zero fun dy hdy ↦
      Finset.sum_eq_zero fun dz hdz ↦ ?_
    rw [if_neg]
    have h1 := (h .X).degree_le_of_mem_support hdx
    have h2 := (h .Y).degree_le_of_mem_support hdy
    have h3 := (h .Z).degree_le_of_mem_support hdz
    omega

end LeadingPure

section SliceLeading

variable {K : Type u} [CommSemiring K]
variable {V : Leg → Type v} [∀ c, AddCommMonoid (V c)] [∀ c, Module K (V c)]
variable {W : Leg → Type w} [∀ c, AddCommMonoid (W c)] [∀ c, Module K (W c)]

/-- `HasSliceLeadingBound r P`: there is a degree `m` below which all coefficients of the
polynomial tensor path `P` vanish and whose own coefficient has slice rank at most `r`.

This is the exact output of transporting a slice decomposition along a polynomial family of
legwise maps: the transported decomposition pins down one degree at which the path can first be
nonzero, and the coefficient there is again a sum of `r` slice terms.  It does **not** claim that
the coefficient at `m` is nonzero; see the module documentation. -/
def HasSliceLeadingBound (r : ℕ) (P : PolynomialTensor K W) : Prop :=
  ∃ m : ℕ, (∀ n < m, P n = 0) ∧ SliceRankLE r (P m)

namespace HasSliceLeadingBound

/-- The zero path has a slice-rank-`0` leading bound. -/
theorem zero : HasSliceLeadingBound 0 (0 : PolynomialTensor K W) :=
  ⟨0, by simp, by simpa using SliceRankLE.zero (K := K) (V := W)⟩

/-- Slice-rank leading bounds are monotone in the bound. -/
theorem mono {r s : ℕ} {P : PolynomialTensor K W} (h : HasSliceLeadingBound r P) (hrs : r ≤ s) :
    HasSliceLeadingBound s P := by
  obtain ⟨m, hvanish, hrank⟩ := h
  exact ⟨m, hvanish, hrank.mono hrs⟩

/-- Slice-rank leading bounds add: take the smaller of the two degrees.  Below it both paths
vanish, and at it each path either contributes its own certified coefficient or vanishes. -/
theorem add {r s : ℕ} {P Q : PolynomialTensor K W}
    (hP : HasSliceLeadingBound r P) (hQ : HasSliceLeadingBound s Q) :
    HasSliceLeadingBound (r + s) (P + Q) := by
  obtain ⟨mP, hPv, hPs⟩ := hP
  obtain ⟨mQ, hQv, hQs⟩ := hQ
  refine ⟨min mP mQ, ?_, ?_⟩
  · intro n hn
    rw [Finsupp.add_apply, hPv n (lt_of_lt_of_le hn (min_le_left _ _)),
      hQv n (lt_of_lt_of_le hn (min_le_right _ _)), add_zero]
  · rw [Finsupp.add_apply]
    refine SliceRankLE.add ?_ ?_
    · rcases eq_or_lt_of_le (min_le_left mP mQ) with heq | hlt
      · rw [heq]; exact hPs
      · rw [hPv _ hlt]; exact SliceRankLE.zero.mono (Nat.zero_le r)
    · rcases eq_or_lt_of_le (min_le_right mP mQ) with heq | hlt
      · rw [heq]; exact hQs
      · rw [hQv _ hlt]; exact SliceRankLE.zero.mono (Nat.zero_le s)

/-- A list of paths with a common slice-rank leading bound `r` sums to a path with leading bound
`length · r`. -/
theorem list_sum {r : ℕ} (terms : List (PolynomialTensor K W))
    (h : ∀ P ∈ terms, HasSliceLeadingBound r P) :
    HasSliceLeadingBound (terms.length * r) terms.sum := by
  induction terms with
  | nil => simpa using HasSliceLeadingBound.zero.mono (Nat.zero_le 0)
  | cons P rest ih =>
      rw [List.sum_cons, List.length_cons]
      exact ((h P (List.mem_cons_self ..)).add
        (ih fun Q hQ ↦ h Q (List.mem_cons_of_mem _ hQ))).mono (Nat.le_of_eq (by ring))

end HasSliceLeadingBound

/-- Helper: a list of paths that all become, at their own first possibly nonzero degree, slice
terms with one *common* leg-`c` vector `v`, sums to a path with the same property.  The common
vector is what allows the surviving coefficients to be merged into a single slice term. -/
private theorem exists_leading_sliceTermWith_list {c : Leg} {v : W c}
    (terms : List (PolynomialTensor K W))
    (h : ∀ P ∈ terms, ∃ m, (∀ n < m, P n = 0) ∧ SliceTermWith c v (P m)) :
    ∃ m, (∀ n < m, terms.sum n = 0) ∧ SliceTermWith c v (terms.sum m) := by
  induction terms with
  | nil => exact ⟨0, by simp, by simpa using SliceTermWith.zero c v⟩
  | cons P rest ih =>
      obtain ⟨mP, hPv, hPs⟩ := h P (List.mem_cons_self ..)
      obtain ⟨mR, hRv, hRs⟩ := ih fun Q hQ ↦ h Q (List.mem_cons_of_mem _ hQ)
      refine ⟨min mP mR, ?_, ?_⟩
      · intro n hn
        rw [List.sum_cons, Finsupp.add_apply, hPv n (lt_of_lt_of_le hn (min_le_left _ _)),
          hRv n (lt_of_lt_of_le hn (min_le_right _ _)), add_zero]
      · rw [List.sum_cons, Finsupp.add_apply]
        refine SliceTermWith.add ?_ ?_
        · rcases eq_or_lt_of_le (min_le_left mP mR) with heq | hlt
          · rw [heq]; exact hPs
          · rw [hPv _ hlt]; exact SliceTermWith.zero c v
        · rcases eq_or_lt_of_le (min_le_right mP mR) with heq | hlt
          · rw [heq]; exact hRs
          · rw [hRv _ hlt]; exact SliceTermWith.zero c v

/-- **Transport of a single slice term along a polynomial family of legwise maps.**  If `T` is a
slice term along the leg `c`, then for every polynomial family `A` the transformed path
`polynomialTransform A T` has a degree below which it vanishes and at which its coefficient is
again a slice term along `c`.

Proof sketch: write `T = ∑_k pure(t_k)` with `t_k c = v` for all `k`.  Transformation is additive
and sends `pure(t_k)` to the polynomial pure tensor of the three transformed polynomial vectors
`A_i (t_k i)`.  By `HasLeadingTerm.polynomialPure` that path has leading coefficient
`pure(fun i ↦ leading coefficient of A_i (t_k i))` in the sum of the three orders.  Its leg-`c`
entry is the leading coefficient of `A_c v`, which does not depend on `k`, so the surviving
coefficients merge into one slice term along `c` by `exists_leading_sliceTermWith_list`. -/
theorem SliceTermAlong.exists_leading_sliceTermAlong {c : Leg} {T : Tensor3 K V}
    (h : SliceTermAlong c T) (A : ∀ i, PolynomialLinearMap K (V i) (W i)) :
    ∃ m : ℕ, (∀ n < m, polynomialTransform A T n = 0) ∧
      SliceTermAlong c (polynomialTransform A T m) := by
  classical
  obtain ⟨v, factors, hcomm, rfl⟩ := h
  set vc : PolynomialVector (W c) := PolynomialLinearMap.applyVector (A c) v with hvc
  have hpath : polynomialTransform A (factors.map pure).sum =
      (factors.map fun t ↦ polynomialPure (K := K)
        fun i ↦ PolynomialLinearMap.applyVector (A i) (t i)).sum := by
    rw [polynomialTransform_list_sum, List.map_map]
    exact congrArg List.sum (List.map_congr_left fun t _ ↦ polynomialTransform_pure A t)
  rw [hpath]
  have hkey : ∀ P ∈ (factors.map fun t ↦ polynomialPure (K := K)
      fun i ↦ PolynomialLinearMap.applyVector (A i) (t i)),
      ∃ m, (∀ n < m, P n = 0) ∧ SliceTermWith c (vc vc.order) (P m) := by
    intro P hP
    obtain ⟨t, ht, rfl⟩ := List.mem_map.mp hP
    set y : ∀ i, PolynomialVector (W i) :=
      fun i ↦ PolynomialLinearMap.applyVector (A i) (t i) with hy
    have hlead : HasLeadingTerm (polynomialPure (K := K) y)
        ((y .X).order + (y .Y).order + (y .Z).order)
        (pure (K := K) fun i ↦ y i (y i).order) :=
      HasLeadingTerm.polynomialPure fun i ↦ (y i).hasLeadingTerm_order
    refine ⟨(y .X).order + (y .Y).order + (y .Z).order, fun n hn ↦ hlead.lower_coeff hn, ?_⟩
    rw [hlead.coeff]
    refine SliceTermWith.pure_tensor _ ?_
    show y c (y c).order = vc vc.order
    have hyc : y c = vc := by
      show PolynomialLinearMap.applyVector (A c) (t c) = PolynomialLinearMap.applyVector (A c) v
      rw [hcomm t ht]
    rw [hyc]
  obtain ⟨m, hvanish, hslice⟩ := exists_leading_sliceTermWith_list _ hkey
  exact ⟨m, hvanish, hslice.sliceTermAlong⟩

/-- **Transport of a slice-rank certificate along a polynomial family of legwise maps.**  A
decomposition of `T` into `r` slice terms produces, for every polynomial family `A`, one degree
below which `polynomialTransform A T` vanishes and at which its coefficient has slice rank at
most `r`. -/
theorem SliceRankLE.hasSliceLeadingBound {r : ℕ} {T : Tensor3 K V} (hT : SliceRankLE r T)
    (A : ∀ i, PolynomialLinearMap K (V i) (W i)) :
    HasSliceLeadingBound r (polynomialTransform A T) := by
  obtain ⟨terms, hlen, hslice, rfl⟩ := hT
  have hpath : polynomialTransform A (terms.map Prod.snd).sum =
      (terms.map fun p ↦ polynomialTransform A p.2).sum := by
    rw [polynomialTransform_list_sum, List.map_map]
    rfl
  rw [hpath]
  refine (HasSliceLeadingBound.list_sum (r := 1) _ ?_).mono ?_
  · intro P hP
    obtain ⟨p, hp, rfl⟩ := List.mem_map.mp hP
    obtain ⟨m, hvanish, hterm⟩ := (hslice p hp).exists_leading_sliceTermAlong A
    exact ⟨m, hvanish, hterm.sliceRankLE⟩
  · simpa using hlen

/-- **The first-order half of thesis Proposition 5.1.**  For every polynomial family `A` of
legwise maps there is a degree `m` such that `polynomialTransform A T` vanishes below `m` and its
degree-`m` coefficient has slice rank at most `sliceRank T`. -/
theorem exists_leading_sliceRankLE (T : Tensor3 K V)
    (A : ∀ i, PolynomialLinearMap K (V i) (W i)) :
    ∃ m : ℕ, (∀ n < m, polynomialTransform A T n = 0) ∧
      SliceRankLE (sliceRank T) (polynomialTransform A T m) :=
  (sliceRank_spec T).hasSliceLeadingBound A

/-- If a degree `m` at or above the leading degree `d` of a polynomial path has all lower
coefficients vanishing and a slice-rank-`r` coefficient, then the leading coefficient itself has
slice rank at most `r`: either `m = d`, and the two coefficients coincide, or `m > d`, and then
the leading coefficient is zero. -/
theorem SliceRankLE.of_hasLeadingTerm_of_le {P : PolynomialTensor K W} {d m r : ℕ}
    {S : Tensor3 K W} (hlead : HasLeadingTerm P d S) (hdm : d ≤ m)
    (hvanish : ∀ n < m, P n = 0) (hrank : SliceRankLE r (P m)) :
    SliceRankLE r S := by
  rcases eq_or_lt_of_le hdm with rfl | hlt
  · rwa [hlead.coeff] at hrank
  · have hS : S = 0 := by
      rw [← hlead.coeff]
      exact hvanish d hlt
    rw [hS]
    exact SliceRankLE.zero.mono (Nat.zero_le r)

/-- **Thesis Proposition 5.1, first-order case.**  If the transported slice decomposition of `T`
first becomes nonzero no earlier than the leading degree `d` of the degeneration path, then the
target of the degeneration has slice rank at most `sliceRank T`.

The hypothesis `hfirst` is exactly the gap discussed in the module documentation: it is the
statement that the degree produced by `exists_leading_sliceRankLE` is not smaller than the leading
degree of the path, which is what fails when the transported slice terms cancel to higher order. -/
theorem sliceRank_le_of_hasLeadingTerm {T : Tensor3 K V} {S : Tensor3 K W} {d : ℕ}
    {A : ∀ i, PolynomialLinearMap K (V i) (W i)}
    (hlead : HasLeadingTerm (polynomialTransform A T) d S)
    (hfirst : ∀ m : ℕ, (∀ n < m, polynomialTransform A T n = 0) →
      SliceRankLE (sliceRank T) (polynomialTransform A T m) → d ≤ m) :
    sliceRank S ≤ sliceRank T := by
  obtain ⟨m, hvanish, hrank⟩ := exists_leading_sliceRankLE T A
  exact sliceRank_le_iff.mpr
    (SliceRankLE.of_hasLeadingTerm_of_le hlead (hfirst m hvanish hrank) hvanish hrank)

end SliceLeading

/-! ## Consequences and the remaining obligation -/

section Consequences

variable {K : Type u} [CommSemiring K]
variable {V : Leg → Type v} [∀ c, AddCommMonoid (V c)] [∀ c, Module K (V c)]
variable {W : Leg → Type w} [∀ c, AddCommMonoid (W c)] [∀ c, Module K (W c)]

/-- **Degree-zero degenerations do not increase slice rank**, unconditionally: for `d = 0` the
hypothesis `d ≤ m` of `SliceRankLE.of_hasLeadingTerm_of_le` is automatic.  Such a degeneration is
an exact restriction in disguise, so this is a consistency check on the machinery rather than new
information; it is the smallest client of `exists_leading_sliceRankLE`. -/
theorem sliceRank_le_of_polynomialDegeneratesAt_zero {T : Tensor3 K V} {S : Tensor3 K W}
    (h : PolynomialDegeneratesAt 0 T S) : sliceRank S ≤ sliceRank T := by
  obtain ⟨A, hlead⟩ := h
  obtain ⟨m, hvanish, hrank⟩ := exists_leading_sliceRankLE T A
  exact sliceRank_le_iff.mpr
    (SliceRankLE.of_hasLeadingTerm_of_le hlead (Nat.zero_le m) hvanish hrank)

end Consequences

section Statement

/-- Monotonicity of slice rank under polynomial degeneration, for one fixed pair of leg universes.
This is thesis Proposition 5.1, quoting [TaoSawin2016, Corollary 2].

It was a named proof obligation while the saturation step was missing; it is now a theorem over
every field, `sliceRankDegenerationMonotone_holds`.  The `Prop` definition is kept because it is
the universe-explicit packaging of the statement, and because downstream theorems that still carry
it as a hypothesis can now discharge it. -/
def SliceRankDegenerationMonotone (K : Type u) [CommSemiring K] : Prop :=
  ∀ {V : Leg → Type v} [∀ c, AddCommMonoid (V c)] [∀ c, Module K (V c)]
    {W : Leg → Type w} [∀ c, AddCommMonoid (W c)] [∀ c, Module K (W c)]
    (T : Tensor3 K V) (S : Tensor3 K W),
    PolynomialDegenerates T S → sliceRank S ≤ sliceRank T

/-- **Thesis Proposition 5.1** ([TaoSawin2016, Corollary 2]), in the universe-explicit packaging:
over a field, polynomial degeneration never increases slice rank.

The mathematics is `sliceRank_le_of_polynomialDegenerates` in `Tensor/SliceRankSaturation.lean`;
the only work here is that the packaged statement quantifies over `AddCommMonoid` leg spaces,
whereas the saturation argument subtracts, so the canonical additive-group structure of a module
over a ring (`Module.addCommMonoidToAddCommGroup`) is installed on the target legs. -/
theorem sliceRankDegenerationMonotone_holds (K : Type u) [Field K] :
    SliceRankDegenerationMonotone.{u, v, w} K := by
  intro V _ _ W _ _ T S h
  letI : ∀ c, AddCommGroup (W c) := fun _ ↦ Module.addCommMonoidToAddCommGroup K
  exact sliceRank_le_of_polynomialDegenerates h

variable {K : Type u} [Field K]
variable {V : Leg → Type v} [∀ c, AddCommMonoid (V c)] [∀ c, Module K (V c)]
variable {W : Leg → Type w} [∀ c, AddCommMonoid (W c)] [∀ c, Module K (W c)]

/-- **Thesis Proposition 5.1**: the target of a polynomial degeneration has slice rank at most that
of its source. -/
theorem sliceRank_polynomialDegenerates_le
    {T : Tensor3 K V} {S : Tensor3 K W} (h : PolynomialDegenerates T S) :
    sliceRank S ≤ sliceRank T :=
  sliceRankDegenerationMonotone_holds.{u, v, w} K T S h

/-- **Asymptotic half of thesis Proposition 5.1**: polynomial degeneration does not increase
asymptotic slice rank.

Proof sketch: polynomial degenerations are stable under canonical tensor powers
(`PolynomialDegenerates.power`), so Proposition 5.1 compares the two slice-rank power sequences
pointwise, and `Growth.exponentialRate_mono` transports the comparison to the growth rates.  The
exponential bound the monotonicity lemma requires is
`exists_exponentialBound_sliceRankPowerSequence`. -/
theorem asymptoticSliceRank_polynomialDegenerates_le
    {T : Tensor3 K V} {S : Tensor3 K W} (h : PolynomialDegenerates T S) :
    asymptoticSliceRank S ≤ asymptoticSliceRank T := by
  refine Growth.exponentialRate_mono (fun n ↦ ?_)
    (exists_exponentialBound_sliceRankPowerSequence T)
  exact sliceRankDegenerationMonotone_holds.{u, max u v, max u w} K _ _ (h.power n)

end Statement

end AlgebraicComplexity.Tensor
