/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.Probability.MarginalProjection
import Mathlib.Tactic.Linarith

/-!
# Parent-consistent compatibility pooling

This module isolates the information-theoretic correction that appears when a recursive
compatibility argument replaces child-specific complete-split laws by averages within
compatibility cells.

A `CompatibilityPoolingModel` consists of a coarse split `u`, its two compatibility cells, and
one pooled child law in each cell.  Its `reference` law first samples `u`, then samples the two
children independently from their pooled laws.  A competing joint law is `IsFeasible` when it
has the same coarse-split marginal and the same two cell-labelled child marginals.

The main theorem `conditionalEntropy_add_parentKl_le` proves

`H(Q | U) + D(Q_parent || reference_parent) ≤ H(reference | U)`.

Thus enforcing a prescribed parent law reduces the compatibility-counting entropy by at least
the KL divergence between that parent law and the decoupled parent law.  The proof is exact: the
feasibility marginals make the expectation of the reference log-density invariant, turning KL
into an entropy gap, and deterministic data processing projects that KL to the parent symbol.

All information-theoretic content is inherited from the generic
`ThreeMarginalProjectionModel` in `Probability/MarginalProjection.lean`: the embedding
`toThreeMarginalProjectionModel` identifies the pooled reference with a three-potential
log-density model, and each pooled theorem is the instantiation of the corresponding generic
theorem at the parent statistic `parentMap`.
-/

open scoped BigOperators

namespace AlgebraicComplexity

universe u₁ u₂ u₃ u₄ u₅

/-- The finite data used when compatibility classes pool two child distributions. -/
structure CompatibilityPoolingModel
    (U : Type u₁) (L : Type u₂) (R : Type u₃) (CL : Type u₄) (CR : Type u₅)
    [Fintype U] [Fintype L] [Fintype R] [Fintype CL] [Fintype CR] where
  /-- Law of the ordered coarse split. -/
  coarseLaw : ProbabilityVector U
  /-- Compatibility cell of the left child at a coarse split. -/
  leftCell : U → CL
  /-- Compatibility cell of the right child at a coarse split. -/
  rightCell : U → CR
  /-- Pooled complete-split law for a left compatibility cell. -/
  pooledLeft : CL → ProbabilityVector L
  /-- Pooled complete-split law for a right compatibility cell. -/
  pooledRight : CR → ProbabilityVector R
  /-- Full support on the structural coarse-split support. -/
  coarse_pos : ∀ u, 0 < coarseLaw.weight u
  /-- Full support on each structural left-child support. -/
  pooledLeft_pos : ∀ c l, 0 < (pooledLeft c).weight l
  /-- Full support on each structural right-child support. -/
  pooledRight_pos : ∀ c r, 0 < (pooledRight c).weight r

namespace CompatibilityPoolingModel

variable
    {U : Type u₁} {L : Type u₂} {R : Type u₃} {CL : Type u₄} {CR : Type u₅}
    [Fintype U] [Fintype L] [Fintype R] [Fintype CL] [Fintype CR]
    [DecidableEq U] [DecidableEq L] [DecidableEq R] [DecidableEq CL] [DecidableEq CR]

/-- Sample space carrying a coarse split and the two complete-split child symbols. -/
abbrev Sample (U : Type u₁) (L : Type u₂) (R : Type u₃) := U × (L × R)

/-- Forget the children and retain the coarse split. -/
def coarseMap : Sample U L R → U := Prod.fst

/-- Forget the coarse split and retain the parent complete-split symbol. -/
def parentMap : Sample U L R → L × R := Prod.snd

/-- Retain the left compatibility cell together with its child symbol. -/
def leftOccurrence (M : CompatibilityPoolingModel U L R CL CR) :
    Sample U L R → CL × L :=
  fun x ↦ (M.leftCell x.1, x.2.1)

/-- Retain the right compatibility cell together with its child symbol. -/
def rightOccurrence (M : CompatibilityPoolingModel U L R CL CR) :
    Sample U L R → CR × R :=
  fun x ↦ (M.rightCell x.1, x.2.2)

/-- The decoupled law generated by compatibility-cell averages. -/
noncomputable def reference (M : CompatibilityPoolingModel U L R CL CR) :
    ProbabilityVector (Sample U L R) :=
  M.coarseLaw.joint fun u ↦
    (M.pooledLeft (M.leftCell u)).product (M.pooledRight (M.rightCell u))

omit [DecidableEq U] [DecidableEq L] [DecidableEq R] [DecidableEq CL] [DecidableEq CR] in
@[simp] theorem reference_weight
    (M : CompatibilityPoolingModel U L R CL CR) (u : U) (l : L) (r : R) :
    M.reference.weight (u, (l, r)) =
      M.coarseLaw.weight u *
        ((M.pooledLeft (M.leftCell u)).weight l *
          (M.pooledRight (M.rightCell u)).weight r) :=
  rfl

omit [DecidableEq U] [DecidableEq L] [DecidableEq R] [DecidableEq CL] [DecidableEq CR] in
/-- The decoupled reference has full support on the model's structural sample space. -/
theorem reference_pos (M : CompatibilityPoolingModel U L R CL CR)
    (x : Sample U L R) :
    0 < M.reference.weight x := by
  rcases x with ⟨u, l, r⟩
  exact mul_pos (M.coarse_pos u)
    (mul_pos (M.pooledLeft_pos (M.leftCell u) l)
      (M.pooledRight_pos (M.rightCell u) r))

/-- A law is feasible for compatibility pooling when it preserves the coarse split and both
cell-labelled child occurrence distributions. -/
def IsFeasible (M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) : Prop :=
  q.pushforward coarseMap = M.reference.pushforward coarseMap ∧
    q.pushforward M.leftOccurrence = M.reference.pushforward M.leftOccurrence ∧
    q.pushforward M.rightOccurrence = M.reference.pushforward M.rightOccurrence

/-- Parent complete-split law of a joint compatibility model. -/
noncomputable def parentLaw (_M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) : ProbabilityVector (L × R) :=
  q.pushforward parentMap

/-- Parent law implicitly produced after the two pooled child laws are decoupled. -/
noncomputable def decoupledParent (M : CompatibilityPoolingModel U L R CL CR) :
    ProbabilityVector (L × R) :=
  M.parentLaw M.reference

private noncomputable def coarsePotential
    (M : CompatibilityPoolingModel U L R CL CR) (u : U) : ℝ :=
  Real.log (M.coarseLaw.weight u)

private noncomputable def leftPotential
    (M : CompatibilityPoolingModel U L R CL CR) (x : CL × L) : ℝ :=
  Real.log ((M.pooledLeft x.1).weight x.2)

private noncomputable def rightPotential
    (M : CompatibilityPoolingModel U L R CL CR) (x : CR × R) : ℝ :=
  Real.log ((M.pooledRight x.1).weight x.2)

omit [DecidableEq U] [DecidableEq L] [DecidableEq R] [DecidableEq CL] [DecidableEq CR] in
/-- The decoupled log-density is a sum of potentials controlled by the three feasibility
marginals. -/
private theorem log_reference_weight
    (M : CompatibilityPoolingModel U L R CL CR) (x : Sample U L R) :
    Real.log (M.reference.weight x) =
      (coarsePotential M ∘ coarseMap) x +
        ((leftPotential M ∘ M.leftOccurrence) x +
          (rightPotential M ∘ M.rightOccurrence) x) := by
  rcases x with ⟨u, l, r⟩
  rw [reference_weight,
    Real.log_mul (M.coarse_pos u).ne'
      (mul_pos (M.pooledLeft_pos (M.leftCell u) l)
        (M.pooledRight_pos (M.rightCell u) r)).ne',
    Real.log_mul (M.pooledLeft_pos (M.leftCell u) l).ne'
      (M.pooledRight_pos (M.rightCell u) r).ne']
  rfl

/-- View a full-support compatibility-pooling model as the generic three-marginal information
projection model.  Structural applications with zero cells instead instantiate
`ThreeMarginalProjectionModel` directly on their legal-support subtype. -/
noncomputable def toThreeMarginalProjectionModel
    (M : CompatibilityPoolingModel U L R CL CR) :
    ThreeMarginalProjectionModel (Sample U L R) U (CL × L) (CR × R) where
  reference := M.reference
  coarse := coarseMap
  leftFeature := M.leftOccurrence
  rightFeature := M.rightOccurrence
  coarsePotential := coarsePotential M
  leftPotential := leftPotential M
  rightPotential := rightPotential M
  reference_pos := M.reference_pos
  log_reference_weight := M.log_reference_weight

/-- Feasible laws have exactly the same expectation of the decoupled reference log-density.
Instantiates `ThreeMarginalProjectionModel.expectation_log_reference_eq` at the pooled model. -/
theorem expectation_log_reference_eq
    (M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (hq : M.IsFeasible q) :
    q.expectation (fun x ↦ Real.log (M.reference.weight x)) =
      M.reference.expectation (fun x ↦ Real.log (M.reference.weight x)) :=
  M.toThreeMarginalProjectionModel.expectation_log_reference_eq q hq

omit [Fintype U] [Fintype L] [Fintype R]
    [DecidableEq U] [DecidableEq L] [DecidableEq R] in
/-- Projection to the parent symbol is surjective whenever the coarse-split type is inhabited. -/
theorem parentMap_surjective [Nonempty U] :
    Function.Surjective (parentMap (U := U) (L := L) (R := R)) := by
  intro z
  exact ⟨(Classical.choice (inferInstance : Nonempty U), z), rfl⟩

/-- **Parent-consistency correction, in nats.**  Among laws satisfying the pooled occurrence
constraints, imposing a parent marginal costs at least its KL divergence from the parent law
implicitly generated by decoupling the pooled children.  Instantiates
`ThreeMarginalProjectionModel.conditionalEntropy_add_parentKl_le` at the parent statistic
`parentMap`. -/
theorem conditionalEntropy_add_parentKl_le [Nonempty U]
    (M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (hq : M.IsFeasible q) :
    q.conditionalEntropy coarseMap +
        (q.pushforward parentMap).klDiv (M.reference.pushforward parentMap) ≤
      M.reference.conditionalEntropy coarseMap :=
  M.toThreeMarginalProjectionModel.conditionalEntropy_add_parentKl_le
    parentMap parentMap_surjective q hq

/-- Subtractive form of the parent-consistency correction. -/
theorem conditionalEntropy_le_sub_parentKl [Nonempty U]
    (M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (hq : M.IsFeasible q) :
    q.conditionalEntropy coarseMap ≤
      M.reference.conditionalEntropy coarseMap -
        (M.parentLaw q).klDiv M.decoupledParent := by
  change q.conditionalEntropy coarseMap ≤
    M.reference.conditionalEntropy coarseMap -
      (q.pushforward parentMap).klDiv (M.reference.pushforward parentMap)
  linarith [conditionalEntropy_add_parentKl_le M q hq]

/-- Direct form for a prescribed parent law `β`. -/
theorem conditionalEntropy_le_sub_prescribedParentKl [Nonempty U]
    (M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (β : ProbabilityVector (L × R))
    (hq : M.IsFeasible q) (hparent : M.parentLaw q = β) :
    q.conditionalEntropy coarseMap ≤
      M.reference.conditionalEntropy coarseMap -
        β.klDiv M.decoupledParent := by
  simpa [hparent] using conditionalEntropy_le_sub_parentKl M q hq

/-- Parent-consistency correction measured in bits.  Instantiates
`ThreeMarginalProjectionModel.conditionalEntropyBits_add_parentKlBits_le`. -/
theorem conditionalEntropyBits_add_parentKlBits_le [Nonempty U]
    (M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (hq : M.IsFeasible q) :
    q.conditionalEntropyBits coarseMap +
        (q.pushforward parentMap).klDivBits (M.reference.pushforward parentMap) ≤
      M.reference.conditionalEntropyBits coarseMap :=
  M.toThreeMarginalProjectionModel.conditionalEntropyBits_add_parentKlBits_le
    parentMap parentMap_surjective q hq

/-- Fully rational-in-the-laws version of the correction.  It replaces parent KL by the
coordinatewise quadratic lower bound used by the current certificate.  Instantiates
`ThreeMarginalProjectionModel.conditionalEntropyBits_add_parentQuadratic_le`. -/
theorem conditionalEntropyBits_add_parentQuadratic_le [Nonempty U]
    (M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (hq : M.IsFeasible q) :
    q.conditionalEntropyBits coarseMap +
        (M.parentLaw q).quadraticKlLowerBits M.decoupledParent ≤
      M.reference.conditionalEntropyBits coarseMap :=
  M.toThreeMarginalProjectionModel.conditionalEntropyBits_add_parentQuadratic_le
    parentMap parentMap_surjective q hq

/-- Prescribed-parent correction in the base-two units used by tensor exponents. -/
theorem conditionalEntropyBits_le_sub_prescribedParentKlBits [Nonempty U]
    (M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (β : ProbabilityVector (L × R))
    (hq : M.IsFeasible q) (hparent : M.parentLaw q = β) :
    q.conditionalEntropyBits coarseMap ≤
      M.reference.conditionalEntropyBits coarseMap -
        β.klDivBits M.decoupledParent := by
  have h := conditionalEntropyBits_add_parentKlBits_le M q hq
  rw [show q.pushforward parentMap = β by simpa [parentLaw] using hparent] at h
  change q.conditionalEntropyBits coarseMap ≤
    M.reference.conditionalEntropyBits coarseMap -
      β.klDivBits (M.reference.pushforward parentMap)
  linarith

/-- Prescribed-parent quadratic correction in base-two units.  Instantiates
`ThreeMarginalProjectionModel.conditionalEntropyBits_le_sub_prescribedParentQuadratic`. -/
theorem conditionalEntropyBits_le_sub_prescribedParentQuadratic [Nonempty U]
    (M : CompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (β : ProbabilityVector (L × R))
    (hq : M.IsFeasible q) (hparent : M.parentLaw q = β) :
    q.conditionalEntropyBits coarseMap ≤
      M.reference.conditionalEntropyBits coarseMap -
        β.quadraticKlLowerBits M.decoupledParent :=
  M.toThreeMarginalProjectionModel.conditionalEntropyBits_le_sub_prescribedParentQuadratic
    parentMap parentMap_surjective q β hq hparent

end CompatibilityPoolingModel

end AlgebraicComplexity
