/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.Probability.EntropyChainRule
import AlgebraicComplexity.Probability.ParentConsistency
import AlgebraicComplexity.Probability.SparseMarginalProjection
import Mathlib.Tactic.Linarith

/-!
# Parent-consistent compatibility pooling with structural zeroes

This is the certificate-facing counterpart of `CompatibilityPoolingModel`.  Coarse and pooled
child laws may contain exact structural zeroes.  Feasible competitors must be absolutely
continuous with respect to the decoupled reference; `SparseMarginalProjection` then removes the
common zeroes exactly and proves the same parent-consistency correction without positive padding.

The main theorem
`SparseCompatibilityPoolingModel.conditionalEntropyBits_le_sub_prescribedParentQuadratic`
has precisely the rational correction used by the level-4 checker.
-/

open scoped BigOperators

namespace AlgebraicComplexity

universe u₁ u₂ u₃ u₄ u₅

/-- Compatibility-pooling data whose probability tables may contain structural zeroes. -/
structure SparseCompatibilityPoolingModel
    (U : Type u₁) (L : Type u₂) (R : Type u₃) (CL : Type u₄) (CR : Type u₅)
    [Fintype U] [Fintype L] [Fintype R] [Fintype CL] [Fintype CR] where
  coarseLaw : ProbabilityVector U
  leftCell : U → CL
  rightCell : U → CR
  pooledLeft : CL → ProbabilityVector L
  pooledRight : CR → ProbabilityVector R

namespace SparseCompatibilityPoolingModel

variable
    {U : Type u₁} {L : Type u₂} {R : Type u₃} {CL : Type u₄} {CR : Type u₅}
    [Fintype U] [Fintype L] [Fintype R] [Fintype CL] [Fintype CR]
    [DecidableEq U] [DecidableEq L] [DecidableEq R] [DecidableEq CL] [DecidableEq CR]

abbrev Sample (U : Type u₁) (L : Type u₂) (R : Type u₃) :=
  CompatibilityPoolingModel.Sample U L R

abbrev coarseMap : Sample U L R → U :=
  CompatibilityPoolingModel.coarseMap

abbrev parentMap : Sample U L R → L × R :=
  CompatibilityPoolingModel.parentMap

/-- Left compatibility-cell occurrence feature. -/
def leftOccurrence (M : SparseCompatibilityPoolingModel U L R CL CR) :
    Sample U L R → CL × L :=
  fun x ↦ (M.leftCell x.1, x.2.1)

/-- Right compatibility-cell occurrence feature. -/
def rightOccurrence (M : SparseCompatibilityPoolingModel U L R CL CR) :
    Sample U L R → CR × R :=
  fun x ↦ (M.rightCell x.1, x.2.2)

/-- The possibly sparse decoupled law generated by compatibility-cell averages. -/
noncomputable def reference (M : SparseCompatibilityPoolingModel U L R CL CR) :
    ProbabilityVector (Sample U L R) :=
  M.coarseLaw.joint fun u ↦
    (M.pooledLeft (M.leftCell u)).product (M.pooledRight (M.rightCell u))

omit [DecidableEq U] [DecidableEq L] [DecidableEq R]
    [DecidableEq CL] [DecidableEq CR] in
@[simp] theorem reference_weight
    (M : SparseCompatibilityPoolingModel U L R CL CR) (u : U) (l : L) (r : R) :
    M.reference.weight (u, (l, r)) =
      M.coarseLaw.weight u *
        ((M.pooledLeft (M.leftCell u)).weight l *
          (M.pooledRight (M.rightCell u)).weight r) :=
  rfl

private noncomputable def coarsePotential
    (M : SparseCompatibilityPoolingModel U L R CL CR) (u : U) : ℝ :=
  Real.log (M.coarseLaw.weight u)

private noncomputable def leftPotential
    (M : SparseCompatibilityPoolingModel U L R CL CR) (x : CL × L) : ℝ :=
  Real.log ((M.pooledLeft x.1).weight x.2)

private noncomputable def rightPotential
    (M : SparseCompatibilityPoolingModel U L R CL CR) (x : CR × R) : ℝ :=
  Real.log ((M.pooledRight x.1).weight x.2)

omit [DecidableEq U] [DecidableEq L] [DecidableEq R]
    [DecidableEq CL] [DecidableEq CR] in
private theorem factors_pos_of_reference_pos
    (M : SparseCompatibilityPoolingModel U L R CL CR) (u : U) (l : L) (r : R)
    (h : 0 < M.reference.weight (u, (l, r))) :
    0 < M.coarseLaw.weight u ∧
      0 < (M.pooledLeft (M.leftCell u)).weight l ∧
      0 < (M.pooledRight (M.rightCell u)).weight r := by
  rw [reference_weight] at h
  have hcoarseZero : M.coarseLaw.weight u ≠ 0 := by
    intro hz
    simp [hz] at h
  have hleftZero : (M.pooledLeft (M.leftCell u)).weight l ≠ 0 := by
    intro hz
    simp [hz] at h
  have hrightZero : (M.pooledRight (M.rightCell u)).weight r ≠ 0 := by
    intro hz
    simp [hz] at h
  exact ⟨
    lt_of_le_of_ne (M.coarseLaw.nonneg u) (Ne.symm hcoarseZero),
    lt_of_le_of_ne ((M.pooledLeft (M.leftCell u)).nonneg l) (Ne.symm hleftZero),
    lt_of_le_of_ne ((M.pooledRight (M.rightCell u)).nonneg r) (Ne.symm hrightZero)⟩

omit [DecidableEq U] [DecidableEq L] [DecidableEq R]
    [DecidableEq CL] [DecidableEq CR] in
/-- On the positive structural support, the sparse reference log-density is still the sum of the
three compatibility potentials. -/
theorem log_reference_weight
    (M : SparseCompatibilityPoolingModel U L R CL CR) (x : Sample U L R)
    (hx : 0 < M.reference.weight x) :
    Real.log (M.reference.weight x) =
      (coarsePotential M ∘ coarseMap) x +
        ((leftPotential M ∘ M.leftOccurrence) x +
          (rightPotential M ∘ M.rightOccurrence) x) := by
  rcases x with ⟨u, l, r⟩
  obtain ⟨hu, hl, hr⟩ := factors_pos_of_reference_pos M u l r hx
  rw [reference_weight, Real.log_mul hu.ne' (mul_pos hl hr).ne',
    Real.log_mul hl.ne' hr.ne']
  rfl

/-- Sparse pooling as a generic sparse three-marginal information projection. -/
noncomputable def toSparseThreeMarginalProjectionModel
    (M : SparseCompatibilityPoolingModel U L R CL CR) :
    SparseThreeMarginalProjectionModel (Sample U L R) U (CL × L) (CR × R) where
  reference := M.reference
  coarse := coarseMap
  leftFeature := M.leftOccurrence
  rightFeature := M.rightOccurrence
  coarsePotential := coarsePotential M
  leftPotential := leftPotential M
  rightPotential := rightPotential M
  log_reference_weight := M.log_reference_weight

/-- A sparse competitor preserves the three pooled marginals and has no mass on structurally
forbidden reference samples. -/
def IsFeasible (M : SparseCompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) : Prop :=
  M.toSparseThreeMarginalProjectionModel.IsFeasible q

/-- Parent complete-split law of a sparse compatibility model. -/
noncomputable def parentLaw (_M : SparseCompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) : ProbabilityVector (L × R) :=
  q.pushforward parentMap

/-- Parent law generated by the sparse decoupled reference. -/
noncomputable def decoupledParent (M : SparseCompatibilityPoolingModel U L R CL CR) :
    ProbabilityVector (L × R) :=
  M.parentLaw M.reference

/-- Exact parent-consistency correction for sparse tables, in bits. -/
theorem conditionalEntropyBits_add_parentKlBits_le
    (M : SparseCompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (hq : M.IsFeasible q) :
    q.conditionalEntropyBits coarseMap +
        (M.parentLaw q).klDivBits M.decoupledParent ≤
      M.reference.conditionalEntropyBits coarseMap := by
  exact M.toSparseThreeMarginalProjectionModel.conditionalEntropyBits_add_parentKlBits_le
    parentMap q hq

/-- Exact rational-in-the-laws sparse parent correction. -/
theorem conditionalEntropyBits_add_parentQuadratic_le
    (M : SparseCompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (hq : M.IsFeasible q) :
    q.conditionalEntropyBits coarseMap +
        (M.parentLaw q).quadraticKlLowerBits M.decoupledParent ≤
      M.reference.conditionalEntropyBits coarseMap := by
  exact M.toSparseThreeMarginalProjectionModel.conditionalEntropyBits_add_parentQuadratic_le
    parentMap q hq

/-- Prescribed-parent sparse correction in the rational quadratic form used by certificate
verification. -/
theorem conditionalEntropyBits_le_sub_prescribedParentQuadratic
    (M : SparseCompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (β : ProbabilityVector (L × R))
    (hq : M.IsFeasible q) (hparent : M.parentLaw q = β) :
    q.conditionalEntropyBits coarseMap ≤
      M.reference.conditionalEntropyBits coarseMap -
        β.quadraticKlLowerBits M.decoupledParent := by
  exact M.toSparseThreeMarginalProjectionModel
    |>.conditionalEntropyBits_le_sub_prescribedParentQuadratic
      parentMap q β hq hparent

omit [DecidableEq L] [DecidableEq R] [DecidableEq CL] [DecidableEq CR] in
/-- The sparse pooled entropy is still the explicit coarse-weighted sum of child entropies. -/
theorem reference_conditionalEntropyBits_eq
    (M : SparseCompatibilityPoolingModel U L R CL CR) :
    M.reference.conditionalEntropyBits coarseMap =
      ∑ u, M.coarseLaw.weight u *
        ((M.pooledLeft (M.leftCell u)).entropyBits +
          (M.pooledRight (M.rightCell u)).entropyBits) := by
  rw [reference, coarseMap, CompatibilityPoolingModel.coarseMap,
    ProbabilityVector.conditionalEntropyBits_joint_fst]
  apply Finset.sum_congr rfl
  intro u _
  rw [ProbabilityVector.entropyBits_product]

/-- A feasible prescribed parent law is absolutely continuous with respect to the sparse
decoupled parent law. -/
theorem parentLaw_isAbsolutelyContinuous
    (M : SparseCompatibilityPoolingModel U L R CL CR)
    (q : ProbabilityVector (Sample U L R)) (hq : M.IsFeasible q) :
    (M.parentLaw q).IsAbsolutelyContinuous M.decoupledParent :=
  hq.1.pushforward parentMap

end SparseCompatibilityPoolingModel

end AlgebraicComplexity
