/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.MatrixMultiplication.PartitionedPowerHashing

/-!
# Type-selected subpartitions of a partitioned tensor power

A laser-style extraction fixes a family `words` of supported source words, keeps exactly the
blocks of a positive partitioned power whose three leg labels satisfy a leg-local predicate
`keep`, and then hashes the survivors.  Every client of that recipe needs the same three facts:

* the selected subpartition has exactly the modeled support of `words`
  (`PartitionHashEncoding.select_positivePower_support`);
* every retained constituent restricts to the client's target tensor, because it is the
  external product along one selected word
  (`Tensor.Restricts.select_positivePower_constituent`);
* the legwise-isolated indexed direct sum of retained constituents restricts componentwise to
  the constant direct sum of that target
  (`Tensor.Restricts.legwiseIsolatedIndexedDirectSum_const`).

None of the three depends on the target being a matrix-multiplication tensor, on the number of
constituents, or on the arithmetic identity of the word products, so the same statements serve
square and rectangular clients with three or six constituents.  The client supplies only the
type-selection bridge `hwords`, which characterizes `words` by `keep`, and one restriction
certificate per selected word; `MatrixMultiplication/PartitionedTypeExtraction.lean` produces
the latter from base-constituent certificates whenever the target is a rectangular
matrix-multiplication tensor.

The module is deliberately paper-independent: the Coppersmith--Winograd hashing clients are
consumers, not part of the interface.
-/

namespace AlgebraicComplexity

open Tensor

universe u v w x y

variable {R : Type u} [Field R]
variable {A : Leg → Type w} [∀ c, Fintype (A c)] [∀ c, DecidableEq (A c)]
variable {K : Type v} [CommSemiring K]
variable {W : Leg → Type y} [∀ c, AddCommMonoid (W c)] [∀ c, Module K (W c)]

section BasePower

variable {V : ∀ c, A c → Type (max v x)}
variable [∀ c a, AddCommMonoid (V c a)] [∀ c a, Module K (V c a)]

/-- Every constituent retained by a leg-local keep-block selection of a positive partitioned
power restricts to a common target tensor `T`.

`hwords` is the type-selection bridge: membership in the source family `words` is exactly the
conjunction of the three leg-local conditions `keep`.  `hword` supplies one restriction
certificate for each selected word, stated on the iterated external product
`P.positiveSupportWordTensor`.  Since `T` is arbitrary, this covers square and rectangular
matrix-multiplication targets as well as any other common constituent shape. -/
theorem Tensor.Restricts.select_positivePower_constituent
    (P : PartitionedTensor (K := K) (A := A) V) (n : ℕ)
    (keep : ∀ c, PositiveWord (A c) n → Prop)
    [∀ c word, Decidable (keep c word)]
    (words : Finset (PositiveWord P.support n))
    (hwords : ∀ q : PositiveWord P.support n,
      q ∈ words ↔ ∀ c, keep c (PartitionHashEncoding.supportWordAddress n q c))
    {T : Tensor3 K W}
    (hword : ∀ q ∈ words, Restricts (P.positiveSupportWordTensor n q) T)
    (s : ((P.positivePower n).select keep).support) :
    Restricts (((P.positivePower n).select keep).constituent s.1) T := by
  obtain ⟨hsPower, hsKeep⟩ :=
    (PartitionedTensor.mem_select_support (P.positivePower n) keep s.1).mp s.2
  obtain ⟨q, haddress⟩ :=
    P.exists_positiveSupportWord_of_mem_positivePower_support n hsPower
  have hq : q ∈ words := by
    refine (hwords q).mpr fun c ↦ ?_
    have hc := congrFun haddress c
    unfold PartitionHashEncoding.supportWordAddress
    rw [hc]
    exact hsKeep c
  have hrestrict : Restricts ((P.positivePower n).constituent
      (positiveSupportWordBlockAddress P.support n q)) T := by
    rw [P.positivePower_constituent_positiveSupportWordBlockAddress n q]
    exact hword q hq
  rw [haddress] at hrestrict
  exact hrestrict

/-- A leg-local keep-block selection of the full positive power has exactly the support modeled
by the selected source words.  This is the hashing-side companion of
`Tensor.Restricts.select_positivePower_constituent`: the same bridge `hwords` identifies the
selected blocks with the legal hashing targets generated by `words`. -/
theorem PartitionHashEncoding.select_positivePower_support
    (P : PartitionedTensor (K := K) (A := A) V)
    (H : PartitionHashEncoding (R := R) P.support) (n : ℕ)
    (keep : ∀ c, PositiveWord (A c) n → Prop)
    [∀ c word, Decidable (keep c word)]
    (words : Finset (PositiveWord P.support n))
    (hwords : ∀ q : PositiveWord P.support n,
      q ∈ words ↔ ∀ c, keep c (PartitionHashEncoding.supportWordAddress n q c)) :
    ((P.positivePower n).select keep).support =
      H.modeledAddresses n (H.legalTargets n words) := by
  classical
  change (P.positivePower n).support.filter (fun s ↦ ∀ c, keep c (s c)) = _
  rw [H.positivePower_support_eq_modeledLegalTargets P n]
  exact H.filter_modeledLegalTargets_eq_of_mem_iff n words keep hwords

end BasePower

section PowerLevel

variable {n : ℕ}
variable {V : ∀ c, PositiveWord (A c) n → Type x}
variable [∀ c a, AddCommMonoid (V c a)] [∀ c a, Module K (V c a)]

/-- The legwise-isolated part of a modeled partitioned power restricts componentwise to the
constant indexed direct sum of any tensor that all its constituents restrict to.

The isolated addresses are a subfamily of the modeled support, so each summand certificate is
just the corresponding constituent certificate; only the subfamily bookkeeping is generic. -/
theorem Tensor.Restricts.legwiseIsolatedIndexedDirectSum_const [NeZero (2 : R)]
    {support : Finset (BlockAddress A)}
    (H : PartitionHashEncoding (R := R) support)
    (words : Finset (PositiveWord support n)) (B : Finset R)
    (seed : ProgressionHash.Seed R (Fin (n + 1)))
    (P : PartitionedTensor (K := K) (A := fun c ↦ PositiveWord (A c) n) V)
    (hsupport : P.support = H.modeledAddresses n (H.legalTargets n words))
    {T : Tensor3 K W}
    (hconstituent : ∀ s : P.support, Restricts (P.constituent s.1) T) :
    Restricts
      (Tensor.indexedDirectSum
        (V := SelectedBlockFamily (V := V)
          (H.legwiseIsolatedPowerAddresses n words B seed))
        (fun s : H.legwiseIsolatedPowerAddresses n words B seed ↦ P.constituent s.1))
      (Tensor.indexedDirectSum
        (fun _ : H.legwiseIsolatedPowerAddresses n words B seed ↦ T)) := by
  apply Tensor.Restricts.indexedDirectSum
  intro s
  refine hconstituent ⟨s.1, ?_⟩
  rw [hsupport]
  exact H.filteredPowerAddresses_subset_modeledAddresses n words B seed
    (H.legwiseIsolatedPowerAddresses_subset_filteredPowerAddresses n words B seed s.2)

end PowerLevel

end AlgebraicComplexity
