import AlgebraicComplexity.MatrixMultiplication.PermutationStableLegFiberCounting
import AlgebraicComplexity.MatrixMultiplication.RationalTypedLeafHashing
import AlgebraicComplexity.MatrixMultiplication.RationalTypedLeafGrowth

/-!
# Fixed-marginal hashing families generated by a rational typed leaf

A `RationalTypedLeaf` stores exactly the data needed to define the two word families in a modern
laser extraction:

* the **marked** family has the leaf's prescribed proportional joint type;
* the **ambient** family contains every support word with the same three proportional marginal
  types.

This module constructs those families generically whenever the leaf coordinates are the actual
block coordinates of a partition support.  It proves position-permutation stability, the exact
division-free marginal/fiber factorization, and the resulting finite affine-hashing competitor
bound.  Named tensor clients therefore need not duplicate the substantial counting argument in
`CoppersmithWinogradSquareCounting`.

The three marginal fiber sizes are allowed to differ.  The exact field requirement is four times
their sum, so this API also supports rectangular and asymmetric typed leaves without replacing
them by a worst-case common bound.
-/

namespace AlgebraicComplexity

open Tensor
open scoped BigOperators

universe u v w

namespace RationalTypedLeaf

variable {A : Leg → Type v} [∀ c, Fintype (A c)] [∀ c, DecidableEq (A c)]
variable {support : Finset (BlockAddress A)} [Nonempty support]

/-- A typed leaf uses exactly the three block-coordinate projections of a partition support.

This deliberately concerns only finite alphabets.  It does not mention tensor spaces or an
extraction relation; those semantic witnesses are supplied separately to the typed-leaf
extraction theorem. -/
def IsSupportCoordinate (leaf : RationalTypedLeaf support A) : Prop :=
  ∀ c s, leaf.coordinate c s = s.1 c

/-- Positive-word depth corresponding to `k` repetitions of the leaf's integral profile.

`PositiveWord I n` has `n + 1` letters, hence the subtraction by one.  All semantic theorems use
a positive repetition and recover the exact length `profile.mass * k`. -/
def proportionalDepth (leaf : RationalTypedLeaf support A) (k : ℕ) : ℕ :=
  leaf.profile.mass * k - 1

/-- At positive repetition, the recursive-word length is exactly the proportional profile mass. -/
theorem proportionalDepth_add_one
    (leaf : RationalTypedLeaf support A) {k : ℕ} (hk : 0 < k) :
    leaf.proportionalDepth k + 1 = leaf.profile.mass * k := by
  unfold proportionalDepth
  have hmass := leaf.profile.mass_pos
  have hprod : 0 < leaf.profile.mass * k := Nat.mul_pos hmass hk
  omega

/-- Exact proportional joint-type words selected for their matrix-multiplication value. -/
noncomputable def markedWords
    (leaf : RationalTypedLeaf support A) (k : ℕ) :
    Finset (PositiveWord support (leaf.proportionalDepth k)) :=
  positiveTypeClass support (leaf.proportionalDepth k)
    (WordType.proportionalCounts leaf.profile.count k)

/-- Predicate that one visible leg word has the leaf's prescribed proportional marginal type. -/
def KeepsMarginal (leaf : RationalTypedLeaf support A) (k : ℕ) (c : Leg)
    (word : PositiveWord (A c) (leaf.proportionalDepth k)) : Prop :=
  WordType.multiplicity
      (positiveWordEquiv (A c) (leaf.proportionalDepth k) word) =
    WordType.proportionalCounts (leaf.marginalProfile c) k

noncomputable instance keepsMarginalDecidable
    (leaf : RationalTypedLeaf support A) (k : ℕ) (c : Leg)
    (word : PositiveWord (A c) (leaf.proportionalDepth k)) :
    Decidable (leaf.KeepsMarginal k c word) := by
  classical
  unfold KeepsMarginal
  infer_instance

/-- All support words having the three marginal types prescribed by a typed leaf.

This is the ambient family obtainable by legwise block zeroing.  It may contain many joint types
even though `markedWords` contains only the distinguished proportional joint type. -/
noncomputable def ambientWords
    (leaf : RationalTypedLeaf support A) (k : ℕ) :
    Finset (PositiveWord support (leaf.proportionalDepth k)) :=
  Finset.univ.filter fun word ↦ ∀ c,
    leaf.KeepsMarginal k c
      (PartitionHashEncoding.supportWordAddress
        (A := A) (support := support) (leaf.proportionalDepth k) word c)

/-- Membership in the ambient family is exactly its three legwise marginal conditions. -/
theorem mem_ambientWords_iff
    (leaf : RationalTypedLeaf support A) (k : ℕ)
    (word : PositiveWord support (leaf.proportionalDepth k)) :
    word ∈ leaf.ambientWords k ↔
      ∀ c, leaf.KeepsMarginal k c
        (PartitionHashEncoding.supportWordAddress
          (A := A) (support := support) (leaf.proportionalDepth k) word c) := by
  classical
  simp [ambientWords]

/-- The distinguished joint type is contained in its complete three-marginal fiber.

Proof sketch: projection of a word multiplicity is the mapped joint multiplicity.  Replace the
marked multiplicity by the proportional profile, commute mapping with proportional scaling, and
use that the typed-leaf coordinate is the actual support coordinate. -/
theorem markedWords_subset_ambientWords
    (leaf : RationalTypedLeaf support A) (hcoordinate : leaf.IsSupportCoordinate)
    (k : ℕ) :
    leaf.markedWords k ⊆ leaf.ambientWords k := by
  classical
  intro word hword
  rw [mem_ambientWords_iff]
  intro c
  unfold KeepsMarginal marginalProfile
  rw [PartitionHashEncoding.positiveWordEquiv_supportWordAddress
    (A := A) (support := support)]
  change WordType.multiplicity
      ((fun s : support ↦ s.1 c) ∘
        positiveWordEquiv support (leaf.proportionalDepth k) word) = _
  have hmap : (fun s : support ↦ s.1 c) = leaf.coordinate c := by
    funext s
    exact (hcoordinate c s).symm
  rw [hmap, WordType.multiplicity_comp_eq_mappedType,
    mem_positiveTypeClass.mp hword,
    WordType.mappedType_proportionalCounts]

/-- The proportional marked joint type is legal at every positive repetition. -/
theorem markedProfile_mem_types
    (leaf : RationalTypedLeaf support A) {k : ℕ} (hk : 0 < k) :
    WordType.proportionalCounts leaf.profile.count k ∈
      WordType.types support (leaf.proportionalDepth k + 1) := by
  rw [leaf.proportionalDepth_add_one hk]
  change WordType.proportionalCounts leaf.profile.count k ∈
    WordType.types support (WordType.profileMass leaf.profile.count * k)
  exact WordType.proportionalCounts_mem_types leaf.profile.count k

/-- The exact marked joint type class is nonempty at every positive repetition. -/
theorem markedWords_nonempty
    (leaf : RationalTypedLeaf support A) {k : ℕ} (hk : 0 < k) :
    (leaf.markedWords k).Nonempty := by
  rw [← Finset.card_pos]
  unfold markedWords
  rw [card_positiveTypeClass]
  exact Finset.card_pos.mpr
    (WordType.typeClass_nonempty _ (leaf.markedProfile_mem_types hk))

/-- Every proportional marginal profile is a legal word type at positive repetition. -/
theorem marginalProfile_mem_types
    (leaf : RationalTypedLeaf support A) {k : ℕ} (hk : 0 < k) (c : Leg) :
    WordType.proportionalCounts (leaf.marginalProfile c) k ∈
      WordType.types (A c) (leaf.proportionalDepth k + 1) := by
  rw [leaf.proportionalDepth_add_one hk,
    ← leaf.profileMass_marginalProfile c]
  exact WordType.proportionalCounts_mem_types (leaf.marginalProfile c) k

/-- The ambient three-marginal family is invariant under a common permutation of word positions.

Proof sketch: each defining condition is a multiplicity equation, and multiplicity is invariant
under reindexing the sample positions. -/
theorem ambientWords_reindex_mem_iff
    (leaf : RationalTypedLeaf support A) (k : ℕ)
    (e : Equiv.Perm (Fin (leaf.proportionalDepth k + 1)))
    (word : PositiveWord support (leaf.proportionalDepth k)) :
    word ∈ leaf.ambientWords k ↔
      PartitionHashEncoding.positiveWordReindex
          (leaf.proportionalDepth k) e word ∈ leaf.ambientWords k := by
  classical
  have forward : ∀ (permutation : Equiv.Perm
      (Fin (leaf.proportionalDepth k + 1)))
      (source : PositiveWord support (leaf.proportionalDepth k)),
      source ∈ leaf.ambientWords k →
        PartitionHashEncoding.positiveWordReindex
            (leaf.proportionalDepth k) permutation source ∈ leaf.ambientWords k := by
    intro permutation source hsource
    rw [mem_ambientWords_iff] at hsource ⊢
    intro c
    have hc := hsource c
    unfold KeepsMarginal at hc ⊢
    have hreindex :=
      PartitionHashEncoding.positiveWordEquiv_supportWordAddress_reindex
        (A := A) (support := support) (leaf.proportionalDepth k)
          permutation source c
    calc
      WordType.multiplicity
          (positiveWordEquiv (A c) (leaf.proportionalDepth k)
            (PartitionHashEncoding.supportWordAddress
              (leaf.proportionalDepth k)
              (PartitionHashEncoding.positiveWordReindex
                (leaf.proportionalDepth k) permutation source) c)) =
        WordType.multiplicity
          (positiveWordEquiv (A c) (leaf.proportionalDepth k)
              (PartitionHashEncoding.supportWordAddress
                (leaf.proportionalDepth k) source c) ∘ permutation.symm) :=
          congrArg WordType.multiplicity hreindex
      _ = WordType.multiplicity
          (positiveWordEquiv (A c) (leaf.proportionalDepth k)
            (PartitionHashEncoding.supportWordAddress
              (leaf.proportionalDepth k) source c)) :=
          WordType.multiplicity_reindex permutation _
      _ = WordType.proportionalCounts (leaf.marginalProfile c) k := hc
  constructor
  · exact forward e word
  · intro hword
    have hback := forward e.symm
      (PartitionHashEncoding.positiveWordReindex
        (leaf.proportionalDepth k) e word) hword
    simpa using hback

/-- Exact size of an ambient fiber on one tensor leg. -/
noncomputable def ambientFiberSize
    (leaf : RationalTypedLeaf support A) (k : ℕ) (c : Leg) : ℕ :=
  (leaf.ambientWords k).card /
    (WordType.typeClass (leaf.proportionalDepth k + 1)
      (WordType.proportionalCounts (leaf.marginalProfile c) k)).card

/-- Exact division-free factorization of the ambient family into equal leg fibers.

For a correctly typed target word, marginal-type cardinality times the corresponding ambient
fiber cardinality is the total ambient cardinality. -/
theorem marginalCard_mul_ambientFiber
    (leaf : RationalTypedLeaf support A) (k : ℕ) (c : Leg)
    (target : PositiveWord (A c) (leaf.proportionalDepth k))
    (htarget : target ∈ positiveTypeClass (A c) (leaf.proportionalDepth k)
      (WordType.proportionalCounts (leaf.marginalProfile c) k)) :
    (positiveTypeClass (A c) (leaf.proportionalDepth k)
        (WordType.proportionalCounts (leaf.marginalProfile c) k)).card *
      (PartitionHashEncoding.sourceWordLegFiber
        (leaf.proportionalDepth k) (leaf.ambientWords k) c target).card =
      (leaf.ambientWords k).card := by
  exact PartitionHashEncoding.card_legType_mul_card_sourceWordLegFiber
    (leaf.proportionalDepth k) (leaf.ambientWords k) c
    (fun e word ↦ leaf.ambientWords_reindex_mem_iff k e word)
    (WordType.proportionalCounts (leaf.marginalProfile c) k)
    (fun word hword ↦ by
      exact (leaf.mem_ambientWords_iff k word).mp hword c)
    target htarget

/-- Every correctly typed ambient source-word fiber has `ambientFiberSize` elements. -/
theorem card_ambient_sourceWordLegFiber
    (leaf : RationalTypedLeaf support A) {k : ℕ} (hk : 0 < k) (c : Leg)
    (target : PositiveWord (A c) (leaf.proportionalDepth k))
    (htarget : target ∈ positiveTypeClass (A c) (leaf.proportionalDepth k)
      (WordType.proportionalCounts (leaf.marginalProfile c) k)) :
    (PartitionHashEncoding.sourceWordLegFiber
      (leaf.proportionalDepth k) (leaf.ambientWords k) c target).card =
      leaf.ambientFiberSize k c := by
  unfold ambientFiberSize
  rw [show (WordType.typeClass (leaf.proportionalDepth k + 1)
      (WordType.proportionalCounts (leaf.marginalProfile c) k)).card =
      (positiveTypeClass (A c) (leaf.proportionalDepth k)
        (WordType.proportionalCounts (leaf.marginalProfile c) k)).card by
    exact (card_positiveTypeClass _ _).symm]
  have hpos : 0 <
      (positiveTypeClass (A c) (leaf.proportionalDepth k)
        (WordType.proportionalCounts (leaf.marginalProfile c) k)).card := by
    rw [card_positiveTypeClass]
    exact Finset.card_pos.mpr
      (WordType.typeClass_nonempty _ (leaf.marginalProfile_mem_types hk c))
  exact Nat.eq_div_of_mul_eq_left
    (Nat.ne_of_gt hpos)
    (by
      simpa [Nat.mul_comm, card_positiveTypeClass] using
        leaf.marginalCard_mul_ambientFiber k c target htarget)

/-- Every encoded ambient target has the prescribed proportional marginal type on each leg. -/
theorem ambientTarget_legWord_mem_marginalTypeClass
    {R : Type u} [Field R]
    (leaf : RationalTypedLeaf support A)
    (H : PartitionHashEncoding (R := R) support) (k : ℕ)
    {triple : ProgressionHash.LegalTriple R
      (Fin (leaf.proportionalDepth k + 1)) H.target}
    (htriple : triple ∈ H.legalTargets (leaf.proportionalDepth k)
      (leaf.ambientWords k)) (c : Leg) :
    H.modeledAddress (leaf.proportionalDepth k) triple c ∈
      positiveTypeClass (A c) (leaf.proportionalDepth k)
        (WordType.proportionalCounts (leaf.marginalProfile c) k) := by
  let source := H.sourceWordOfLegalTriple (leaf.proportionalDepth k) triple
  have hsource : source ∈ leaf.ambientWords k :=
    H.sourceWordOfLegalTriple_mem_of_mem _ _ htriple
  rw [mem_positiveTypeClass]
  have hc := (leaf.mem_ambientWords_iff k source).mp hsource c
  unfold KeepsMarginal at hc
  simpa [source, PartitionHashEncoding.modeledAddress] using hc

/-- Every encoded ambient leg fiber has the exact typed-leaf fiber size. -/
theorem card_ambientTarget_legFiber
    {R : Type u} [Field R]
    (leaf : RationalTypedLeaf support A)
    (H : PartitionHashEncoding (R := R) support)
    {k : ℕ} (hk : 0 < k)
    {triple : ProgressionHash.LegalTriple R
      (Fin (leaf.proportionalDepth k + 1)) H.target}
    (htriple : triple ∈ H.legalTargets (leaf.proportionalDepth k)
      (leaf.ambientWords k)) (c : Leg) :
    (ProgressionHash.LegalTriple.legFiber
      (H.legalTargets (leaf.proportionalDepth k) (leaf.ambientWords k))
      triple c).card = leaf.ambientFiberSize k c := by
  rw [H.card_legFiber_legalTargets_eq_card_sourceWordLegFiber _ _ htriple]
  exact leaf.card_ambient_sourceWordLegFiber hk c _
    (leaf.ambientTarget_legWord_mem_marginalTypeClass H k htriple c)

/-- Competitors of an ambient hashing target are bounded by the sum of its three exact leg-fiber
sizes. -/
theorem card_ambientTarget_legwiseCompetitors_le
    {R : Type u} [Field R]
    (leaf : RationalTypedLeaf support A)
    (H : PartitionHashEncoding (R := R) support)
    {k : ℕ} (hk : 0 < k)
    {triple : ProgressionHash.LegalTriple R
      (Fin (leaf.proportionalDepth k + 1)) H.target}
    (htriple : triple ∈ H.legalTargets (leaf.proportionalDepth k)
      (leaf.ambientWords k)) :
    (ProgressionHash.LegalTriple.legwiseCompetitorYIndices
      (H.legalTargets (leaf.proportionalDepth k) (leaf.ambientWords k))
      triple).card ≤ ∑ c, leaf.ambientFiberSize k c := by
  exact (ProgressionHash.LegalTriple.card_legwiseCompetitorYIndices_le_sum_legFibers
    _ _).trans (Finset.sum_le_sum fun c _ ↦
      (leaf.card_ambientTarget_legFiber H hk htriple c).le)

/-- Exact field-cardinality requirement for marked hashing of a rational typed leaf. -/
noncomputable def hashingRequirement
    (leaf : RationalTypedLeaf support A) (k : ℕ) : ℕ :=
  4 * ∑ c, leaf.ambientFiberSize k c

/-- A sufficiently large finite field yields a seed retaining many marked typed-leaf addresses.

The marked family is isolated against the complete three-marginal ambient family.  The field
requirement is four times the sum of the exact leg-fiber sizes; no artificial symmetry or
worst-case factor is assumed. -/
theorem exists_seed_many_markedIsolatedPowerAddresses
    {R : Type u} [Field R] [Fintype R] [NeZero (2 : R)]
    (leaf : RationalTypedLeaf support A) (hcoordinate : leaf.IsSupportCoordinate)
    (H : PartitionHashEncoding (R := R) support)
    {k : ℕ} (hk : 0 < k)
    (B : Finset R) (hB : ThreeAPFree (B : Set R))
    (hfield : leaf.hashingRequirement k ≤ Fintype.card R) :
    ∃ seed : ProgressionHash.Seed R (Fin (leaf.proportionalDepth k + 1)),
      3 * (leaf.markedWords k).card * B.card ≤
          4 * (Fintype.card R * Fintype.card R) *
            (H.markedLegwiseIsolatedPowerAddresses
              (leaf.proportionalDepth k) (leaf.ambientWords k)
              (leaf.markedWords k) B seed).card ∧
        H.markedLegwiseIsolatedPowerAddresses
            (leaf.proportionalDepth k) (leaf.ambientWords k)
            (leaf.markedWords k) B seed ⊆
          H.filteredPowerAddresses (leaf.proportionalDepth k)
            (leaf.ambientWords k) B seed ∧
        IsLegwiseInjective
          (H.markedLegwiseIsolatedPowerAddresses
            (leaf.proportionalDepth k) (leaf.ambientWords k)
            (leaf.markedWords k) B seed) := by
  apply H.exists_seed_many_markedLegwiseIsolatedPowerAddresses
    (leaf.proportionalDepth k) (leaf.ambientWords k) (leaf.markedWords k)
    (leaf.markedWords_subset_ambientWords hcoordinate k) B hB
  intro triple htriple
  have hambient : triple ∈ H.legalTargets (leaf.proportionalDepth k)
      (leaf.ambientWords k) :=
    H.legalTargets_mono _ (leaf.markedWords_subset_ambientWords hcoordinate k)
      htriple
  calc
    4 * (ProgressionHash.LegalTriple.legwiseCompetitorYIndices
        (H.legalTargets (leaf.proportionalDepth k) (leaf.ambientWords k))
        triple).card ≤
      4 * ∑ c, leaf.ambientFiberSize k c :=
        Nat.mul_le_mul_left 4
          (leaf.card_ambientTarget_legwiseCompetitors_le H hk hambient)
    _ = leaf.hashingRequirement k := rfl
    _ ≤ Fintype.card R := hfield

end RationalTypedLeaf

end AlgebraicComplexity
