/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.Combinatorics.ComplementaryOccurrenceLaw
import AlgebraicComplexity.MatrixMultiplication.ExactCompleteSplitRecursion
import AlgebraicComplexity.MatrixMultiplication.RecursiveChildType

set_option autoImplicit false

/-!
# Complete-split laws on labelled recursive child occurrences

An ordered recursive split state generates two labelled child occurrences.  When its left and
right complete-split profiles have sizes `L` and `R`, respectively, each left symbol occurs once
for every right-profile choice and conversely.  Thus an ordered state of multiplicity `a` has
labelled laws

* `a * R * left.counts` on its left occurrence;
* `a * L * right.counts` on its right occurrence.

Both rows have mass `a * (L * R)`.  This module packages that elementary product law and then
pools it into the exact and compatibility-cell tables consumed by the recursive CW cleanup.
Every hypothesis in the target constructor is a finite equality between explicit local count
tables; no tensor restriction, hashing conclusion, or repair theorem is accepted as input.
-/

open scoped BigOperators

namespace AlgebraicComplexity

universe u v w

namespace RecursiveSplitProfileComponent

/-- Exact symbol law on the two labelled occurrences generated by independently concatenated
left and right complete-split profiles. -/
def occurrenceLaw
    {State : Type u} [Fintype State]
    {depth parentTotal leftSamples rightSamples : ℕ}
    (alphaCount : State → ℕ)
    (component : State → RecursiveSplitProfileComponent
      depth parentTotal leftSamples rightSamples) :
    ComplementaryOccurrenceLaw
      (fun state ↦ alphaCount state * (leftSamples * rightSamples))
      (SplitWord depth) where
  count occurrence word :=
    match occurrence.2 with
    | .left =>
        alphaCount occurrence.1 * rightSamples *
          (component occurrence.1).left.counts word
    | .right =>
        alphaCount occurrence.1 * leftSamples *
          (component occurrence.1).right.counts word
  rowSum occurrence := by
    obtain ⟨state, side⟩ := occurrence
    cases side with
    | left =>
        calc
          (∑ word,
              alphaCount state * rightSamples *
                (component state).left.counts word) =
              (alphaCount state * rightSamples) *
                ∑ word, (component state).left.counts word := by
                  rw [Finset.mul_sum]
          _ = (alphaCount state * rightSamples) * leftSamples := by
                rw [(component state).left.sum_counts]
          _ = alphaCount state * (leftSamples * rightSamples) := by
                ac_rfl
    | right =>
        calc
          (∑ word,
              alphaCount state * leftSamples *
                (component state).right.counts word) =
              (alphaCount state * leftSamples) *
                ∑ word, (component state).right.counts word := by
                  rw [Finset.mul_sum]
          _ = (alphaCount state * leftSamples) * rightSamples := by
                rw [(component state).right.sum_counts]
          _ = alphaCount state * (leftSamples * rightSamples) := by
                ac_rfl

end RecursiveSplitProfileComponent

namespace MoreAsymmetryCompatibility

open Tensor

namespace ExactRecursiveSplitType

/-- Occurrence law obtained from one exact ordered split type and a common-size family of
independent child-profile pairs.  Its row profile is definitionally the split type scaled by the
Cartesian child-profile factor. -/
def completeSplitOccurrenceLaw
    {parent : Leg → ℕ} {childTotal samples depth childSamples : ℕ}
    (alpha : ExactRecursiveSplitType parent childTotal samples) (c : Leg)
    (component : RecursiveChildShape parent childTotal →
      RecursiveSplitProfileComponent depth (parent c) childSamples childSamples) :
    ComplementaryOccurrenceLaw
      (alpha.scale (childSamples * childSamples)).count (SplitWord depth) :=
  RecursiveSplitProfileComponent.occurrenceLaw alpha.count component

@[simp] theorem completeSplitOccurrenceLaw_count_left
    {parent : Leg → ℕ} {childTotal samples depth childSamples : ℕ}
    (alpha : ExactRecursiveSplitType parent childTotal samples) (c : Leg)
    (component : RecursiveChildShape parent childTotal →
      RecursiveSplitProfileComponent depth (parent c) childSamples childSamples)
    (child : RecursiveChildShape parent childTotal) (word : SplitWord depth) :
    (alpha.completeSplitOccurrenceLaw c component).count (child, .left) word =
      alpha.count child * childSamples * (component child).left.counts word :=
  rfl

@[simp] theorem completeSplitOccurrenceLaw_count_right
    {parent : Leg → ℕ} {childTotal samples depth childSamples : ℕ}
    (alpha : ExactRecursiveSplitType parent childTotal samples) (c : Leg)
    (component : RecursiveChildShape parent childTotal →
      RecursiveSplitProfileComponent depth (parent c) childSamples childSamples)
    (child : RecursiveChildShape parent childTotal) (word : SplitWord depth) :
    (alpha.completeSplitOccurrenceLaw c component).count (child, .right) word =
      alpha.count child * childSamples * (component child).right.counts word :=
  rfl

end ExactRecursiveSplitType

section TargetTables

variable {State : Type u} [Fintype State]
variable {Part : Type v} [DecidableEq Part]
variable {depth : ℕ} {profile : State → ℕ}

/-- Pool a labelled occurrence law through an arbitrary cell map.  Only the source state space
must be finite: compatibility labels such as `CoarseIndex Part` contain natural coordinates and
are intentionally not assumed to form a finite type. -/
noncomputable def recursiveOccurrencePooledProfile
    {Cell : Type w} [DecidableEq Cell]
    (cellOf : ComplementaryOccurrence State → Cell)
    (law : ComplementaryOccurrenceLaw profile (SplitWord depth))
    (cell : Cell) (word : SplitWord depth) : ℕ :=
  ∑ occurrence,
    if cellOf occurrence = cell then
      law.count occurrence word
    else 0

/-- Specialization of occurrence pooling when the right child is described by a permutation of
the ordered state. -/
noncomputable def recursiveComplementaryOccurrencePooledProfile
    {Cell : Type w} [DecidableEq Cell]
    (complement : Equiv.Perm State) (cellOf : State → Cell)
    (law : ComplementaryOccurrenceLaw profile (SplitWord depth))
    (cell : Cell) (word : SplitWord depth) : ℕ :=
  recursiveOccurrencePooledProfile
    (fun occurrence ↦ cellOf (occurrence.childState complement)) law cell word

/-- On a finite target alphabet, the generalized pooling operation agrees definitionally with
the conditional-type joint profile used by the counting library. -/
@[simp] theorem recursiveComplementaryOccurrencePooledProfile_eq_cellJointProfile
    {Cell : Type w} [Fintype Cell] [DecidableEq Cell]
    (complement : Equiv.Perm State) (cellOf : State → Cell)
    (law : ComplementaryOccurrenceLaw profile (SplitWord depth))
    (cell : Cell) (word : SplitWord depth) :
    recursiveComplementaryOccurrencePooledProfile complement cellOf law cell word =
      law.cellJointProfile complement cellOf (cell, word) :=
  rfl

/-- Evaluator form of a labelled occurrence/symbol law.  After reindexing the right occurrences,
one child cell receives its left count plus the right count of its unique preimage under
complementation.  At a fixed point these are still two separately labelled summands. -/
theorem recursiveComplementaryOccurrencePooledProfile_eq_evaluator
    {Cell : Type w} [DecidableEq Cell]
    (complement : Equiv.Perm State) (cellOf : State → Cell)
    (law : ComplementaryOccurrenceLaw profile (SplitWord depth))
    (cell : Cell) (word : SplitWord depth) :
    recursiveComplementaryOccurrencePooledProfile complement cellOf law cell word =
      ∑ child,
        if cellOf child = cell then
          law.count (child, .left) word +
            law.count (complement.symm child, .right) word
        else 0 := by
  classical
  unfold recursiveComplementaryOccurrencePooledProfile recursiveOccurrencePooledProfile
  rw [← Finset.univ_product_univ, Finset.sum_product]
  have hsides : (Finset.univ : Finset ComplementarySide) = {.left, .right} := by
    ext side
    cases side <;> simp
  have hsumSide (state : State) :
      (∑ side,
        if cellOf (ComplementaryOccurrence.childState complement (state, side)) = cell then
          law.count (state, side) word else 0) =
        (if cellOf state = cell then law.count (state, .left) word else 0) +
          (if cellOf (complement state) = cell then
            law.count (state, .right) word else 0) := by
    rw [hsides]
    simp [ComplementaryOccurrence.childState, ComplementaryOccurrence.side,
      ComplementaryOccurrence.orderedState]
    rfl
  simp_rw [hsumSide]
  rw [Finset.sum_add_distrib]
  have hreindex :
      (∑ state,
        if cellOf (complement state) = cell then
          law.count (state, .right) word else 0) =
        ∑ child,
          if cellOf child = cell then
            law.count (complement.symm child, .right) word else 0 := by
    simpa using
      (Equiv.sum_comp complement
        (fun child ↦ if cellOf child = cell then
          law.count (complement.symm child, .right) word else 0))
  rw [hreindex, ← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro child _
  by_cases hcell : cellOf child = cell <;> simp [hcell]

/-- With the identity state cell, one pooled symbol row is exactly the labelled left row at that
state plus the labelled right row at its unique complementary preimage.  This abstract formula is
also a performance boundary: concrete clients should use it instead of reducing a finite sum over
their state representation. -/
theorem recursiveComplementaryOccurrencePooledProfile_id
    [DecidableEq State]
    (complement : Equiv.Perm State)
    (law : ComplementaryOccurrenceLaw profile (SplitWord depth))
    (state : State) (word : SplitWord depth) :
    recursiveComplementaryOccurrencePooledProfile complement id law state word =
      law.count (state, .left) word +
        law.count (complement.symm state, .right) word := by
  classical
  rw [recursiveComplementaryOccurrencePooledProfile_eq_evaluator]
  simp only [id_eq]
  rw [Finset.sum_eq_single state]
  · simp
  · intro other _ hother
    simp [hother]
  · simp

/-- Exact complete-split table on one coarse child constituent, obtained by pooling the two
labelled occurrence laws that realize that child state. -/
noncomputable def recursiveOccurrenceExactProfile
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (law : ComplementaryOccurrenceLaw profile (SplitWord depth))
    (q : CoarseIndex Part) (word : SplitWord depth) : ℕ :=
  recursiveOccurrencePooledProfile coarseOf law q word

/-- Pooled positive `Y` compatibility-cell table induced by a labelled occurrence law. -/
noncomputable def recursiveOccurrenceYPooledProfile
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (law : ComplementaryOccurrenceLaw profile (SplitWord depth))
    (cellPart : Part) (y : ℕ) (word : SplitWord depth) : ℕ :=
  recursiveOccurrencePooledProfile
    (fun occurrence ↦ yCompatibilityCell (coarseOf occurrence))
    law (.pooled cellPart y) word

/-- Pooled positive `Z` compatibility-cell table induced by a labelled occurrence law. -/
noncomputable def recursiveOccurrenceZPooledProfile
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (law : ComplementaryOccurrenceLaw profile (SplitWord depth))
    (cellPart : Part) (z : ℕ) (word : SplitWord depth) : ℕ :=
  recursiveOccurrencePooledProfile
    (fun occurrence ↦ zCompatibilityCell (coarseOf occurrence))
    law (.pooled cellPart z) word

/-- Three local labelled-occurrence laws together with the boundary symmetries required by CW
legality.  The fields are finite count-table equalities. -/
structure RecursiveOccurrenceTargetData
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (profile : State → ℕ) where
  law : ∀ _c, ComplementaryOccurrenceLaw profile (SplitWord depth)
  yBoundary : ∀ q, q.z = 0 → ∀ word,
    recursiveOccurrenceExactProfile coarseOf (law Leg.Y) q word =
      recursiveOccurrenceExactProfile coarseOf (law Leg.X) q
        (complementSplitWord word)
  zBoundaryOfX : ∀ q, q.y = 0 → ∀ word,
    recursiveOccurrenceExactProfile coarseOf (law Leg.Z) q word =
      recursiveOccurrenceExactProfile coarseOf (law Leg.X) q
        (complementSplitWord word)
  zBoundaryOfY : ∀ q, q.x = 0 → ∀ word,
    recursiveOccurrenceExactProfile coarseOf (law Leg.Z) q word =
      recursiveOccurrenceExactProfile coarseOf (law Leg.Y) q
        (complementSplitWord word)

namespace RecursiveOccurrenceTargetData

/-- Convert local occurrence laws into the exact compatibility target tables. -/
noncomputable def toCompatibilityTargets
    {coarseOf : ComplementaryOccurrence State → CoarseIndex Part}
    {profile : State → ℕ}
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf profile) :
    CompatibilityTargets Part depth where
  xExact := recursiveOccurrenceExactProfile coarseOf (data.law .X)
  yExact := recursiveOccurrenceExactProfile coarseOf (data.law .Y)
  zExact := recursiveOccurrenceExactProfile coarseOf (data.law .Z)
  yPooled := recursiveOccurrenceYPooledProfile coarseOf (data.law .Y)
  zPooled := recursiveOccurrenceZPooledProfile coarseOf (data.law .Z)
  yBoundary := data.yBoundary
  zBoundaryOfX := data.zBoundaryOfX
  zBoundaryOfY := data.zBoundaryOfY

@[simp] theorem toCompatibilityTargets_xExact
    {coarseOf : ComplementaryOccurrence State → CoarseIndex Part}
    {profile : State → ℕ}
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf profile) :
    data.toCompatibilityTargets.xExact =
      recursiveOccurrenceExactProfile coarseOf (data.law .X) :=
  rfl

@[simp] theorem toCompatibilityTargets_yExact
    {coarseOf : ComplementaryOccurrence State → CoarseIndex Part}
    {profile : State → ℕ}
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf profile) :
    data.toCompatibilityTargets.yExact =
      recursiveOccurrenceExactProfile coarseOf (data.law .Y) :=
  rfl

@[simp] theorem toCompatibilityTargets_zExact
    {coarseOf : ComplementaryOccurrence State → CoarseIndex Part}
    {profile : State → ℕ}
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf profile) :
    data.toCompatibilityTargets.zExact =
      recursiveOccurrenceExactProfile coarseOf (data.law .Z) :=
  rfl

end RecursiveOccurrenceTargetData

end TargetTables

end MoreAsymmetryCompatibility
end AlgebraicComplexity
