import AxiomAudit.Command
import AlgebraicComplexity.Combinatorics.AggregateMarkedHashing

/-! Focused trust audit for heterogeneous aggregate marked affine hashing. -/

#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.aggregate_injective
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.card_aggregateTargets
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.card_aggregate_legFiber
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.card_aggregate_legwiseCompetitorYIndices_le_sum_products
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.aggregate_quarter_of_factorFiberBounds
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.exists_seed_many_aggregateMarkedLegwiseIsolatedTargets
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.exists_seed_many_aggregateMarkedLegwiseIsolatedTargets_of_max
