/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import AlgebraicComplexity.Combinatorics.AggregateMarkedCompatibilityHashing

/-! Focused trust audit for directional compatibility hashing on aggregate marked families. -/

#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.mem_directionalCompatibilityFiber
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.aggregateDirectionalCompatible_aggregate_iff
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.aggregateDirectionalCompatible_sharesLeg
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.card_aggregateDirectionalCompatibilityAlternativeTargets_le_sum_products
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.card_aggregateDirectionalCompatibilityAlternativeIndices_le_sum_products
#assert_axioms AlgebraicComplexity.ProgressionHash.LegalTriple.exists_seed_many_aggregateMarkedDirectionalCompatibilityIsolatedTargets
