/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.BetaFourSparseContributions

/-!
# Enforcing audit for sparse routed beta-four rows

These assertions cover the generic normalization, merge, expansion, and compact-certificate
soundness theorems used to keep generated beta-four arithmetic out of dense array reduction.
-/

#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.AllTargetsBelow.target_lt_of_mem
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sparseNumeratorAt_insertSparse
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sparseNumeratorAt_mergeSparse
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sparseNumeratorAt_filterMap_eq_numeratorAt
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sparseNumeratorAt_normalizeSparse
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sparseNumeratorAt_append
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.numeratorAt_append
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sparseNumeratorAt_canonicalizeRows
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.IsCanonicalFrom.target_ge_of_mem
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.IsCanonicalFrom.target_lt_of_mem
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.IsCanonicalFrom.numerator_pos_of_mem
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.expandSparseFrom_eq_map_range'
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.dropZeros_expandSparseFrom
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.dropZeros_scatterOn_range_eq_map_numerator_of_canonicalizeRows_eq
