/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.BetaFourShardedContributions

/-!
# Enforcing audit for compositional beta-four sparse certificates

These assertions cover target restriction, bounded merge traces, sparse and dense consecutive-band
assembly, and the final sharded certificate theorems used by generated level-four arithmetic.
-/

#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sparseNumeratorAt_restrictSparse_of_mem
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.IsCanonicalFrom.sparseNumeratorAt_eq_zero_of_lt_start
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.IsCanonicalFrom.sparseNumeratorAt_eq_zero_of_limit_le
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.IsCanonicalFrom.mono_start
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.IsCanonicalFrom.append
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.MergeTrace.sparseNumeratorAt
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sum_sparseNumeratorAt_eq_numeratorAt_flatten_of_forall₂
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.AllTargetsBelow.append
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.AllTargetsBelow.flatten_of_forall
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.AllTargetsBelow.flatten₂_of_forall
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sum_sparseNumeratorAt_eq_of_restricted_forall₂
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.sum_sparseNumeratorAt_filterMap_eq_of_restricted_forall₂
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.BandCertificate.sparseNumeratorAt
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.BandCover.start_le
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.BandCover.canonical
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.BandCover.sparseNumeratorAt
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.dropZeros_scatterOn_range_eq_bandFinalRow_and_allTargetsBelow
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.DenseBandCover.start_le
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.DenseBandCover.values_eq
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.dropZeros_scatterOn_range_eq_denseBandValues_and_allTargetsBelow
