/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.BetaFourLocalContributions

/-!
# Enforcing audit for routed parent-local beta-four contributions

These assertions cover the cache-free factorization that computes expensive parent-support routes
once and then reuses them across bounded arithmetic shards.
-/

#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.scatterOn_append
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.betaFourRowNumeratorAt_scatterArray
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourRoutedContribution.scatterArray_toList_eq_scatterOn_range
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalSlotData.routedContributionFromSupports_eq_some_unchecked
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalSlotData.getD_ne_zero_of_mem_nonzeroSymbols
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalSlotData.routedContributionsForLeftFromSupports_eq_unchecked
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalSlotData.routedContributions_eq_flatMap_forLeft_of_ne
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalSlotData.routedContributions_eq_flatMap_forLeftFromSupports_of_ne
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalSlotData.routedContributions_eq_nil_of_split_eq_zero
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalSlotData.foldl_routedContributions_eq_addToNumeratorAt
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalData.routedNumeratorAt_eq
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalData.routedScatterOn_eq_scatterOn
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.BetaFourLocalData.routedScatterOn_range_eq_scatter
