import AxiomAudit.Command
import AlgebraicComplexity.MatrixMultiplication.CartesianAssembly

/-! Focused trust audit for heterogeneous Cartesian constituent assembly. -/

#assert_axioms AlgebraicComplexity.PositiveStageOutput.card
#assert_axioms AlgebraicComplexity.Tensor.Restricts.external_indexedDirectSum_matrixMultiplication
#assert_axioms AlgebraicComplexity.Tensor.Restricts.positiveWord_dependentIndexedDirectSum
#assert_axioms AlgebraicComplexity.Tensor.Restricts.cartesianComponentTensor_matrixMultiplication
#assert_axioms AlgebraicComplexity.Tensor.Restricts.positiveWord_dependentIndexedDirectSum_matrixMultiplication
#assert_axioms AlgebraicComplexity.Tensor.Restricts.power_positiveWord_dependentIndexedDirectSum
#assert_axioms AlgebraicComplexity.Tensor.Restricts.power_positiveWord_dependentIndexedDirectSum_matrixMultiplication
#assert_axioms AlgebraicComplexity.Tensor.PolynomialDegenerates.positiveWord_dependentIndexedDirectSum_matrixMultiplication
#assert_axioms AlgebraicComplexity.Tensor.PolynomialDegenerates.power_positiveWord_dependentIndexedDirectSum_matrixMultiplication
