/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.Analysis.ComplementaryOccurrenceCellPairedWordFamily
import AlgebraicComplexity.Analysis.ConditionalWordFamilyCoordinateDual
import AlgebraicComplexity.Analysis.FiniteTypicalProfileUniformization
import AlgebraicComplexity.Analysis.PairedConditionalWordFamilyCoarsenedEntropy
import AlgebraicComplexity.Analysis.PooledMarginalProjectionWordFamily
import AlgebraicComplexity.Combinatorics.AggregateMarkedCompatibilityHashing
import AlgebraicComplexity.Combinatorics.AggregateMarkedXHashing
import AlgebraicComplexity.Combinatorics.CompatibilityIsolationLabel
import AlgebraicComplexity.Combinatorics.ComplementaryOccurrenceCounting
import AlgebraicComplexity.Combinatorics.ComplementaryOccurrenceLawPushforward
import AlgebraicComplexity.Combinatorics.ComplementaryOccurrencePairedWord
import AlgebraicComplexity.Combinatorics.GuardedFineCompatibility
import AlgebraicComplexity.Combinatorics.HashingIsolationChargedCollision
import AlgebraicComplexity.Combinatorics.MappedTypeActiveSupport
import AlgebraicComplexity.Combinatorics.PooledOrbitCategory
import AlgebraicComplexity.Combinatorics.ProductCellCompetitorCount
import AlgebraicComplexity.Combinatorics.RealizedProfileTypedFiberBound
import AlgebraicComplexity.Combinatorics.SharedLegSeedHoleMass
import AlgebraicComplexity.Combinatorics.TypedFineSeedHoles
import AlgebraicComplexity.Examples.CoppersmithWinogradChunkEventualDivisionForestStage
import AlgebraicComplexity.Examples.CoppersmithWinogradChunkEventualDivisionStage
import AlgebraicComplexity.Examples.CoppersmithWinogradCompatibilityDivisionLeafStage
import AlgebraicComplexity.Examples.CoppersmithWinogradCompatibilityOuterStage
import AlgebraicComplexity.Examples.CoppersmithWinogradCompatibilityProportionalDivisionLeafStage
import AlgebraicComplexity.Examples.CoppersmithWinogradCompatibilityTargetOutputGrowth
import AlgebraicComplexity.Examples.CoppersmithWinogradMergedTypedLeafCleanup
import AlgebraicComplexity.Examples.CoppersmithWinogradNestedTotalWeightFiberDisintegration
import AlgebraicComplexity.Examples.CoppersmithWinogradNestedTotalWeightSupportEncoding
import AlgebraicComplexity.Examples.CoppersmithWinogradOccurrenceCellTypeRealization
import AlgebraicComplexity.Examples.CoppersmithWinogradPresentFixedCellCounting
import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveApproximateCleanupHoleSemantic
import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveApproximateTargetRepairClient
import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveExactTargetSegmentedTiny
import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveTotalWeightFeatureCounting
import AlgebraicComplexity.Examples.CoppersmithWinogradSortedPair112Cyclic
import AlgebraicComplexity.Examples.CoppersmithWinogradSortedPairAdditiveObstruction
import AlgebraicComplexity.Examples.CoppersmithWinogradSquare211TypedLeaf
import AlgebraicComplexity.Examples.CoppersmithWinogradTightQuotientCounting
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightCompatibilityHashing
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightLevelTwoSemantic
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightMarkedHashExtraction
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightOuterSourceBridge
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightPresentFixedCellMarkedLeafStage
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightPresentMarkedHashExtraction
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightSelectedTermMarkedIsolation
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightTypeCounting
import AlgebraicComplexity.Examples.CoppersmithWinogradUniformPowerSelection
import AlgebraicComplexity.Examples.CoppersmithWinogradZeroDivisionLeafStage
import AlgebraicComplexity.Examples.CoppersmithWinogradZeroOrientationCTensor
import AlgebraicComplexity.Examples.CoppersmithWinogradZeroTypeClassGrowth
import AlgebraicComplexity.MatrixMultiplication.ConditionalTypeSegmentedRestriction
import AlgebraicComplexity.MatrixMultiplication.ExactInterfaceDivisionVolumeLoss
import AlgebraicComplexity.MatrixMultiplication.LaserVolumeLossMonotone
import AlgebraicComplexity.MatrixMultiplication.MarkedXYPresentPartitionGrouping
import AlgebraicComplexity.MatrixMultiplication.MergedLeafClassFactor
import AlgebraicComplexity.MatrixMultiplication.ModeledMarkedHashingProductSupport
import AlgebraicComplexity.MatrixMultiplication.OneSliceRestrictionRelation
import AlgebraicComplexity.MatrixMultiplication.PositiveWordTensorReindex
import AlgebraicComplexity.MatrixMultiplication.TwoStageRecursiveChildShape
import AlgebraicComplexity.MatrixMultiplication.ZeroCoordinateOrientedTypeClassGrowth
import AlgebraicComplexity.MatrixMultiplication.ZeroCoordinateTypeClassGrowth
import AlgebraicComplexity.Probability.CouplingConcentration
import AlgebraicComplexity.Probability.IntegralProfileEntropyReindex
import AlgebraicComplexity.Tensor.GroupedCompatibilityPermutation
import AlgebraicComplexity.Tensor.PartitionedBoxRestriction
import MatrixMultiplication.BetaFourCompactRouteCertificate
import MatrixMultiplication.CoppersmithWinogradZeroLeafEvaluatorBridge
import MatrixMultiplication.DyadicEntropyListZeroPadding
import MatrixMultiplication.DyadicIntegralProfileEntropy
import MatrixMultiplication.PairedTotalWeightA5FrozenRowData
import MatrixMultiplication.PairedTotalWeightA5MixedKernelNoGo
import MatrixMultiplication.SignedDyadicLogFormSum
import MatrixMultiplication.SignedDyadicLogRowAccumulatorDefs
import MatrixMultiplication.SignedDyadicLogStreaming

/-!
# Census import roots for the ordinary AxiomAudit target

GENERATED FILE -- regenerate with `bash scripts/regen_census_roots.sh --write`; do not edit by
hand.

`#axiom_census` can only see modules it imports, so the census closure has to equal the build.
Some modules are built only because a focused `#assert_axioms` audit imports them, which puts
them inside the build but outside every census closure -- a hole in the trust policy rather than
a cosmetic gap, since `AxiomAudit.CensusAll` is what actually walks `Environment.constants`.

This module imports the 74 maximal such modules for this tier, which pulls 211 of them in total
(importing a module pulls its whole cone, so only the roots are listed). It declares nothing; it
exists purely to widen the closure of `AxiomAudit.CensusAll`.

Tier split: a root that reaches `MatrixMultiplication.Generated.*` belongs to the opt-in
certificate census instead, so this file contains no root that reaches the generated numeral tables.
-/
