import AxiomAudit.Command
import AlgebraicComplexity.Combinatorics.ChargedAveraging

/-! Focused trust audit for charged averaging and the sparse-budget sub-family selection. -/

#assert_axioms AlgebraicComplexity.ChargedAveraging.exists_mem_cost_le_reward
#assert_axioms AlgebraicComplexity.ChargedAveraging.exists_mem_floor_add_charge_le_reward
#assert_axioms AlgebraicComplexity.ChargedAveraging.exists_mem_floor_add_weightedCharge_le_reward
#assert_axioms AlgebraicComplexity.ChargedAveraging.exists_seed_type_floor_add_charge_le_reward
#assert_axioms AlgebraicComplexity.ChargedAveraging.finiteWeightedCharge
#assert_axioms AlgebraicComplexity.ChargedAveraging.exists_seed_type_floor_add_weightedCharge_le_reward
#assert_axioms AlgebraicComplexity.ChargedAveraging.mul_card_filter_le_sum_sub
#assert_axioms AlgebraicComplexity.ChargedAveraging.card_filter_lt_le_sum_sub
#assert_axioms AlgebraicComplexity.ChargedAveraging.mul_card_filter_le_of_sum_le
#assert_axioms AlgebraicComplexity.ChargedAveraging.sum_sub_le_sum_charge
#assert_axioms AlgebraicComplexity.ChargedAveraging.exists_subset_forall_cost_le_reward
#assert_axioms AlgebraicComplexity.ChargedAveraging.exists_subset_forall_charge_lt
