import AxiomAudit.Command
import AlgebraicComplexity.Combinatorics.CompatibilityHashingIsolation

/-! Focused trust audit for the affine-hash compatibility-isolation adapter. -/

#assert_axioms AlgebraicComplexity.ProgressionHash.Seed.mem_compatibilityAlternativeIndices
#assert_axioms AlgebraicComplexity.ProgressionHash.Seed.card_compatibilityAlternativeIndices_le
#assert_axioms AlgebraicComplexity.ProgressionHash.Seed.mem_commonBucketFilteredTargets
#assert_axioms AlgebraicComplexity.ProgressionHash.Seed.mem_compatibilityIsolatedTargets
#assert_axioms AlgebraicComplexity.ProgressionHash.Seed.compatibilityHashIsolatedTargets_subset_commonBucketFilteredTargets
#assert_axioms AlgebraicComplexity.ProgressionHash.Seed.compatibilityHashIsolatedTargets_subset_compatibilityIsolatedTargets
#assert_axioms AlgebraicComplexity.ProgressionHash.Seed.exists_seed_many_compatibilityHashIsolatedTargets
#assert_axioms AlgebraicComplexity.ProgressionHash.Seed.commonBucketFilteredTargets_selfCompatible
#assert_axioms AlgebraicComplexity.Tensor.compatibilityIsolatedTargets_pivot_eq_compatibilityIsolatedSupport
#assert_axioms AlgebraicComplexity.Tensor.isCompatibilitySound_of_selfCompatible
