import AxiomAudit.Command
import AlgebraicComplexity.MatrixMultiplication.CompatibilityTargetSupport

/-! Focused trust audit for reconstruction of support-correct compatibility targets. -/

#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactCompatibilityProfileFamily.ofCounts_profile_counts
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactCompatibilityProfileFamily.isXWeightSupported_of_realizesTargets
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactCompatibilityProfileFamily.yExact_weight_eq_of_realizesTargets
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactCompatibilityProfileFamily.zExact_weight_eq_of_realizesTargets
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactCompatibilityProfileFamily.isYWeightSupported_of_realizesTargets
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactCompatibilityProfileFamily.isZWeightSupported_of_realizesTargets
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactCompatibilityProfileFamily.isWeightSupported_of_realizesTargets
