/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinograd238
import AlgebraicComplexity.MatrixMultiplication.CyclicValueNormalization

/-!
# Axiom audit for the modern CW-square `τ`-value assembly

This audit covers the complete semantic spine of the modern square proof: the symmetric
64-address entropy and constituent calculation, its finite cyclic degeneration and survivor
growth, the exact outer square assembly, the square border-rank certificate, Schönhage
soundness, and the final directed arithmetic comparison.  Naming the intermediate bridges is
deliberately redundant with auditing the final theorem: if the endpoint later fails its trust
policy, this list identifies the first mathematical layer whose dependencies changed.
-/

#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricProfileProbability_marginalEntropyBits
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricProfileProbability_isMaximumEntropy
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricSupportedConstituent_restricts
#assert_axioms AlgebraicComplexity.Examples.exists_cw112SymmetricGoodSeed_count
#assert_axioms AlgebraicComplexity.Examples.cw112CyclicPowerProductFiniteExtraction
#assert_axioms AlgebraicComplexity.Examples.exists_eventually_cw112SymmetricSurvivorGrowth
#assert_axioms AlgebraicComplexity.Examples.cwSquareBaseProfile_isMaximumEntropy
#assert_axioms AlgebraicComplexity.Examples.card_cwSquareAmbientWords_le_outerTypeLoss_mul_markedWords
#assert_axioms AlgebraicComplexity.Examples.cwSquareMarginalCard_le_hashLoss_mul_outerCopies
#assert_axioms AlgebraicComplexity.Examples.exists_eventually_cwSquareOuterSurvivorGrowth
#assert_axioms AlgebraicComplexity.Examples.cwSquareMarkedWord_constituent_isomorphic_chunks
#assert_axioms AlgebraicComplexity.Examples.cwSquarePower_restricts_markedIndexedDirectSum
#assert_axioms AlgebraicComplexity.TauValueCertificate.indexedDirectSumPowerOne
#assert_axioms AlgebraicComplexity.TauValueCertificate.indexedDirectSumPowerOne_term
#assert_axioms AlgebraicComplexity.TauValueCertificate.ofPowerOneOnPower
#assert_axioms AlgebraicComplexity.TauValueCertificate.term_ofPowerOneOnPower
#assert_axioms AlgebraicComplexity.CyclicExtractionCertificate.term_rpow_three_mul_power
#assert_axioms AlgebraicComplexity.CyclicExtractionCertificate.rpow_three_mul_power_le_volumePowerSum
#assert_axioms AlgebraicComplexity.Examples.cwSquareGroupedChunkTauValueCertificate
#assert_axioms AlgebraicComplexity.Examples.cwSquareGroupedChunkTauValueCertificate_term
#assert_axioms AlgebraicComplexity.Examples.cwSquareOuterSurvivorTauValueCertificate
#assert_axioms AlgebraicComplexity.Examples.cwSquareTauValueCertificateOfOuterSurvivors
#assert_axioms AlgebraicComplexity.Examples.cwSquareTauValueCertificateOfOuterSurvivors_term
#assert_axioms AlgebraicComplexity.Examples.cwSquareTauValueCertificateOfCyclicInner
#assert_axioms AlgebraicComplexity.Examples.cwSquareTauValueCertificateOfCyclicInner_term
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricCanonical_power_eq_squareMultiplicity_mul
#assert_axioms AlgebraicComplexity.Examples.cwSquareSymmetric112TauValueCertificate
#assert_axioms AlgebraicComplexity.Growth.Subexponential.exists_forall_pow_le_natCast_of_pow_le_mul
#assert_axioms AlgebraicComplexity.normalizedRepeatedPower_eq
#assert_axioms AlgebraicComplexity.Examples.cwSquareTauValueFiniteLowerTerm_eq_limit
#assert_axioms AlgebraicComplexity.Examples.lt_cwSquareTauValueLimitLowerTerm_of_log_lt
#assert_axioms AlgebraicComplexity.Examples.cwSquareTauValueLimitLowerTerm_le_certificate
#assert_axioms AlgebraicComplexity.Examples.exists_cwSquareSymmetric112LimitCertificate
#assert_axioms AlgebraicComplexity.Examples.cwSquarePartitionedTensor_borderRankLE
#assert_axioms AlgebraicComplexity.asymptoticSumInequality
#assert_axioms AlgebraicComplexity.TauValueCertificate.term_le_asymptoticRank
#assert_axioms AlgebraicComplexity.omega_lt_three_mul_of_borderRankLE
#assert_axioms AlgebraicComplexity.Examples.cwSquareSymmetric112_omega_lt_three_mul
#assert_axioms AlgebraicComplexity.Examples.cwSquare238_stable_value_gt_64
#assert_axioms AlgebraicComplexity.Examples.coppersmithWinograd_square_omega_lt_238
