import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightFeatureCompetitorCounting

/-! Focused trust audit for visible-feature counting on total-weight quotient competitors. -/

#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightTaggedAtomCoarseIndex_atomWord
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightYFiniteCellOfTaggedAtom
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightZFiniteCellOfTaggedAtom
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_card_compatibilityCompetitorsY_le_featureClass
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_card_compatibilityCompetitorsZ_le_featureClass
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_card_ambient_le_card_YZIsolatedSupport_add_featureTypeCounts
