import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightInnerGrowthDepthFour

/-! Axiom audit for the concrete depth-four inner growth datum and its ambient bound. -/

#assert_axioms AlgebraicComplexity.WordType.isMaximumEntropyInMappedFiber_of_logLinear
#assert_axioms AlgebraicComplexity.WordType.isMaximumEntropyInMappedFiber_const
#assert_axioms AlgebraicComplexity.Examples.card_cwTotalWeightLocalizedAmbientWords_le
#assert_axioms AlgebraicComplexity.Examples.card_cwTotalWeightLocalizedAmbientWords_le_entropyBase
#assert_axioms AlgebraicComplexity.Examples.cwChunkInnerGrowthDataOfMaximumEntropy
#assert_axioms AlgebraicComplexity.Examples.cwChunkInnerGrowthDataOfMaximumEntropyZeroSafe
#assert_axioms AlgebraicComplexity.Examples.cwChunkConstantInnerGrowthDataLevelFour
#assert_axioms AlgebraicComplexity.Examples.cwChunk_dimensionProduct_ge_oneTypeWitness
#assert_axioms AlgebraicComplexity.Examples.two_rpow_le_five_pow_304
#assert_axioms AlgebraicComplexity.Examples.cwChunkLevelFour_volumeFloor_of_oneTypeCount
#assert_axioms AlgebraicComplexity.Examples.card_cwChunkPartitionedTensor_support
#assert_axioms AlgebraicComplexity.Examples.no_levelFour_leaf_growthData_matches_outerExponent
