import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightInnerGrowth

/-! Focused trust audit for the total-weight localized inner field and Behrend sequence. -/

#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightInnerTargetBase_pow_le_markedFiber
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_sourceWordLegFiber_card_le_entropyQuotient
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightInnerCompetitorRequirement_cast_le
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightInnerHashModulus_cast_le
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightInnerGrowthData.modulus_cast_le_fieldLoss_mul_pow
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightInnerGrowthData.targetBase_pow_le_markedFiber
#assert_axioms AlgebraicComplexity.Examples.exists_cwTotalWeightInnerPrimeBehrendExtraction
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightInnerBehrend_hashCount
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightInnerBehrend_degenerates
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightInnerGrowthData.exists_eventually_pow_le_behrendCopies
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightInnerGrowthData.behrendCopies_pos
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightInnerGrowthData.exists_subexponentialLoss_pow_le_behrendCopies
