import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveHashExtraction
import AxiomAudit.Command

open AlgebraicComplexity AlgebraicComplexity.Examples

/-! Focused trust audit for
`AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveHashExtraction`: the tensor-level
marked X-only hashing pass for recursive CW constituents -- the marked isolated coarse support
with its exact cardinality, physical-`sigma X` injectivity and seed-existence theorem, the three
block zero-outs realizing the common-bucket filter, the restriction onto the whole fine preimage
of every marked address, and its composition with the grouped compatibility cleanup. -/

#assert_axioms CWCoarseFieldEncoding.recursiveMarkedXIsolatedSources
#assert_axioms CWCoarseFieldEncoding.recursiveMarkedXIsolatedCoarseSupport
#assert_axioms CWCoarseFieldEncoding.mem_recursiveMarkedXIsolatedCoarseSupport_iff
#assert_axioms CWCoarseFieldEncoding.recursiveMarkedXIsolatedCoarseSupport_subset
#assert_axioms CWCoarseFieldEncoding.card_recursiveMarkedXIsolatedCoarseSupport
#assert_axioms CWCoarseFieldEncoding.recursiveX_injectiveOn_recursiveMarkedXIsolatedCoarseSupport
#assert_axioms CWCoarseFieldEncoding.exists_seed_many_recursiveMarkedXIsolatedCoarseSupport
#assert_axioms cwRecursiveCoarseSourceOfFine
#assert_axioms cwRecursiveCoarseSourceOfFine_val
#assert_axioms cwRecursiveOrientedHashKeepFineBlock
#assert_axioms cwRecursiveOrientedHashKeepFineBlock_sigma_X
#assert_axioms cwRecursiveOrientedHashKeepFineBlock_sigma_Y
#assert_axioms cwRecursiveOrientedHashKeepFineBlock_sigma_Z
#assert_axioms cwRecursiveOrientedHashFilteredFineSupport
#assert_axioms mem_cwRecursiveOrientedHashFilteredFineSupport
#assert_axioms cwRecursiveOrientedHashKeepFineBlock_all_iff_survives
#assert_axioms cwRecursiveAlphaMarginalSelectedTerm_restricts_orientedHashFilteredFine
#assert_axioms cwRecursiveFineSupportOverCoarseSupport_isGroupSaturatedIn
#assert_axioms cwRecursiveMarkedXIsolatedFine_hasGroupUniqueLegFibers
#assert_axioms cwRecursiveAlphaMarginalSelectedTerm_restricts_markedXIsolatedFine
#assert_axioms cwRecursiveSelectedTerm_orientedMarkedXHashAndGroupedCleanup
#assert_axioms exists_seed_many_recursiveMarkedXHashAndGroupedCleanup
