import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightInnerFiberCounting

/-! Focused trust audit for global and conditional inner-fiber counts in the total-weight quotient. -/

#assert_axioms AlgebraicComplexity.Examples.mem_cwTotalWeightLocalizedAmbientWords_iff
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedAmbientWords_reindex_mem_iff_of_coarse_stable
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightMarkedFiberWords_conditionalLegType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_card_conditionalLegType_mul_card_markedSourceWordLegFiber_le
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_card_conditionalLegType_mul_card_markedLegalLegFiber_le
#assert_axioms AlgebraicComplexity.Examples.mem_cwTotalWeightFineMarginalAmbientWords_iff
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedAmbientWords_subset_fineMarginalAmbientWords
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightFineMarginalAmbientWords_reindex_mem_iff
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_card_marginalType_mul_card_globalLegFiber
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_card_marginalType_mul_card_localizedLegFiber_le
