import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightNestedComposition

/-! Focused trust audit for whole-family total-weight nested composition. -/

#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedOuterConstituentStage
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedOuter_isomorphicToReference_of_fixedCoarseType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedOuter_hasUniformInnerExtraction_of_fixedCoarseType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedOuter_nestedStage_of_fixedCoarseType
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightLocalizedOuterSequenceData.toOuterConstituentSequenceData
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightLocalizedOuterSequenceData.CanonicalInnerSequenceData.hasUniformInnerExtraction
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightLocalizedOuterSequenceData.CanonicalInnerSequenceData.toNestedLaserVolumeSequenceData
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightLocalizedOuterSequenceData.CanonicalInnerSequenceData.toSubexponentialLaserVolumeSequence
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightLocalizedOuterSequenceData.CanonicalInnerSequenceData.toSubexponentialLaserVolumeSequence_addRetained
