import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradSortedPairCounting

/-!
# Focused axiom audit for sorted-pair quotient counting

This target checks the exact one- and two-stage incidence bounds, the conditional method-of-types
adapter, the concrete sorted-pair specialization, and the no-hole finite-stage packaging.
-/

#assert_axioms AlgebraicComplexity.Tensor.compatibilityCompetitors_nonempty_of_not_isolated
#assert_axioms AlgebraicComplexity.Tensor.card_le_card_compatibilityIsolatedSupport_add_sum_competitors
#assert_axioms AlgebraicComplexity.Tensor.card_le_card_YZCompatibilityIsolatedSupport_add_incidences
#assert_axioms AlgebraicComplexity.Tensor.card_le_card_YZCompatibilityIsolatedSupport_add_budgets
#assert_axioms AlgebraicComplexity.Tensor.card_le_two_mul_card_YZCompatibilityIsolatedSupport
#assert_axioms AlgebraicComplexity.Tensor.ConditionalCompetitorEncoding.card_competitors_le_card_conditionalTypeClass
#assert_axioms AlgebraicComplexity.Tensor.ConditionalCompetitorEncoding.multinomial_source_mul_card_competitors_le_multinomial_joint
#assert_axioms AlgebraicComplexity.Tensor.PointedConditionalCompetitorEncoding.card_competitors_le_card_conditionalTypeClass_tsub_one
#assert_axioms AlgebraicComplexity.Tensor.sum_card_compatibleAddresses_eq_sum_card_compatibleLabels
#assert_axioms AlgebraicComplexity.Tensor.ConditionalCompatibleLabelEncoding.card_compatibleLabels_le_card_conditionalTypeClass
#assert_axioms AlgebraicComplexity.Tensor.ConditionalCompatibleLabelEncoding.multinomial_source_mul_card_compatibleLabels_le_multinomial_joint

#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_ambient_le_card_YZIsolatedSupport_add_incidences
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_ambient_le_card_YZIsolatedSupport_add_budgets
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_ambient_le_two_mul_card_YZIsolatedSupport
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairYCompetitorIncidence_le_sum_conditionalTypeCounts
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairZCompetitorIncidence_le_sum_conditionalTypeCounts
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_ambient_le_card_YZIsolatedSupport_add_conditionalTypeCounts
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_hashCount_le_two_mul_hashLoss_mul_card_YZIsolatedSupport
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairWholeConstituentLaserVolumeStage
