/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightOccurrenceClients

/-! Focused trust audit for total-weight profiles derived from recursive occurrence laws. -/

#assert_axioms AlgebraicComplexity.Examples.cwOrientedCoarseCellToIndex_cwRecursiveOccurrenceFiniteCell
#assert_axioms AlgebraicComplexity.Examples.cwProportionalOccurrenceLaw_count
#assert_axioms AlgebraicComplexity.Examples.recursiveOccurrencePooledProfile_proportionalCounts
#assert_axioms AlgebraicComplexity.Examples.cwProportionalRecursiveOccurrenceTargetData_law
#assert_axioms AlgebraicComplexity.Examples.cwRecursiveOccurrenceTargetData_isWeightSupported
#assert_axioms AlgebraicComplexity.Examples.cwRecursiveOccurrenceFullCellType_proportionalCounts
#assert_axioms AlgebraicComplexity.Examples.recursiveOccurrencePushedProfile_eq_mappedRawProfile
#assert_axioms AlgebraicComplexity.Examples.recursiveOccurrence_mappedRawProfile_eq_fullCellFeatureType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightReferenceMultiplicity_eq_fullCellFeatureType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightReferenceMultiplicity_eq_recursiveOccurrencePushedProfile
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightReferenceProfiles_of_recursiveOccurrenceTargetData
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightReferenceProfiles_of_recursiveOccurrenceTargetData_proportionalCounts
