/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.Examples.CoppersmithWinogradZeroCTensor
import AxiomAudit.Command

/-! Axiom audit for exact zero-coordinate interfaces and their whole-support C-tensor retyping. -/

open AlgebraicComplexity
open AlgebraicComplexity.MoreAsymmetryCompatibility
open AlgebraicComplexity.Examples

#assert_axioms completeSplitProfile_weight_eq_of_isConsistent
#assert_axioms selectedExactInterfaceTerm_chunkWeight
#assert_axioms selectedExactInterfaceTerm_leg_eq_const_of_count_eq_zero
#assert_axioms selectedExactInterfaceTerm_yChunk_eq_complement_xChunk_of_z_eq_zero
#assert_axioms selectedExactInterfaceTerm_y_eq_of_x_eq_of_z_eq_zero
#assert_axioms selectedExactInterfaceTerm_x_eq_of_y_eq_of_z_eq_zero
#assert_axioms selectedExactInterfaceTerm_zeroZ_support_isSharedFiber
#assert_axioms CTensor.FiberRetyping.ofSharedSupport
#assert_axioms CTensor.FiberRetyping.ofSharedSupportAmbient
#assert_axioms cwSelectedExactInterfaceTerm_zeroZ_support_isSharedFiber
#assert_axioms cwSelectedExactInterfaceTerm_zeroZ_ambientFiberRetyping
#assert_axioms cwSelectedExactInterfaceTerm_zeroZ_restricts_ambientCTensor
