import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightEmbeddedInnerSequenceDepth

/-! Focused trust audit for the sparse embedded total-weight inner sequence. -/

#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightInnerEmbeddedBehrend_hashCountAtDepth
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightInnerEmbeddedBehrend_degeneratesAtDepth
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightInnerGrowthDataAtDepth.exists_eventually_pow_le_embeddedBehrendCopies
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightInnerGrowthDataAtDepth.embeddedBehrendCopies_pos
#assert_axioms AlgebraicComplexity.Examples.CWTotalWeightInnerGrowthDataAtDepth.exists_subexponentialLoss_pow_le_embeddedBehrendCopies
#assert_axioms AlgebraicComplexity.Examples.exists_cwTotalWeightEmbeddedCanonicalInnerSequenceData_ofDepth
