import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightTypedLeaf

/-! Focused trust audit for whole-coarse total-weight typed-leaf extraction. -/

#assert_axioms AlgebraicComplexity.WordType.mappedType_injective_of_injective
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightCoarseWordOfAddress
#assert_axioms AlgebraicComplexity.Examples.positiveSupportWordBlockAddress_cwTotalWeightCoarseWordOfAddress
#assert_axioms AlgebraicComplexity.Examples.cwChunkSupportWitness
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightSupportedShape_injective
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_jointType_eq_of_shapeType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_selectCoarsenedPositiveMappedTypes_to_fineTypes
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_coarsenedPositivePower_constituent_matrixMultiplication_of_mappedType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_indexedDirectSum_coarsenedPositivePower_constituent_matrixMultiplication_of_mappedType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_coarsenedPositivePower_constituent_matrixMultiplication_of_shapeType
