import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveRelaxedCoarseFamily
import AxiomAudit.Command

open AlgebraicComplexity AlgebraicComplexity.Examples

/-! Focused trust audit for
`AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveRelaxedCoarseFamily`: the relaxed
recursive CW coarse family built from literal labelled-child addresses -- injectivity of the
coarse address of a left-shape word, the affine occurrence equations, the exact ambient and
marked cardinalities, the containment of the approximate coarsened support in the relaxed
ambient family, and the relaxed legal-triple families with their X-fiber degree bounds. -/

#assert_axioms cwRecursiveCoarseAddressOfLeftShapeWord
#assert_axioms cwRecursiveCoarseAddressOfLeftShapeWord_left
#assert_axioms cwRecursiveCoarseAddressOfLeftShapeWord_right
#assert_axioms cwRecursiveCoarseAddressOfLeftShapeWord_injective
#assert_axioms cwRecursiveLogicalLeftTripleWord_coarseAddressOfLeftShapeWord
#assert_axioms cwRecursiveMatchesAlpha_coarseAddressOfLeftShapeWord_iff
#assert_axioms cwRecursiveCoarseAddressOfLeftShapeWord_coarse_sum
#assert_axioms cwRecursiveCoarseAddressOfLeftShapeWord_left_add_right
#assert_axioms cwRecursiveRelaxedAmbientCoarseSupport
#assert_axioms cwRecursiveRelaxedMarkedCoarseSupport
#assert_axioms cwRecursiveRelaxedMarkedCoarseSupport_subset_ambient
#assert_axioms cwRecursiveRelaxedAmbientCoarseSupport_left_add_right
#assert_axioms cwRecursivePositionRelabelCoarseAddress_of_relaxedAmbient_sameTaggedMultiplicity
#assert_axioms card_cwRecursiveRelaxedAmbientCoarseSupport
#assert_axioms card_cwRecursiveRelaxedMarkedCoarseSupport
#assert_axioms cwRecursiveApproximateLogicalLeftShapeWordOfCoarse
#assert_axioms coordinate_cwRecursiveApproximateLogicalLeftShapeWordOfCoarse
#assert_axioms coordinate_complement_cwRecursiveApproximateLogicalLeftShapeWordOfCoarse
#assert_axioms cwRecursiveCoarseAddressOfLeftShapeWord_approximateShape_eq
#assert_axioms cwRecursiveApproximateLogicalLeftShapeWordOfCoarse_mem_marginalWords
#assert_axioms cwRecursiveApproximateCoarsened_support_subset_relaxedAmbient
#assert_axioms mem_cwRecursiveRelaxedMarkedCoarseSupport_of_approximate_of_matchesAlpha
#assert_axioms CWCoarseFieldEncoding.relaxedRecursiveOrientedLegalTriple
#assert_axioms CWCoarseFieldEncoding.relaxedRecursiveOrientedLegalTriple_injective
#assert_axioms CWCoarseFieldEncoding.relaxedRecursiveAmbientTargets
#assert_axioms CWCoarseFieldEncoding.relaxedRecursiveMarkedTargets
#assert_axioms CWCoarseFieldEncoding.relaxedRecursiveMarkedTargets_subset_ambientTargets
#assert_axioms CWCoarseFieldEncoding.card_relaxedRecursiveMarkedTargets
#assert_axioms CWCoarseFieldEncoding.card_relaxedRecursiveAmbientTargets
#assert_axioms CWCoarseFieldEncoding.relaxedRecursiveAmbientTargetEquiv
#assert_axioms CWCoarseFieldEncoding.relaxedRecursiveAmbientSourceOfTarget
#assert_axioms CWCoarseFieldEncoding.relaxedRecursiveOrientedLegalTriple_ambientSourceOfTarget
#assert_axioms CWCoarseFieldEncoding.card_relaxedRecursiveAmbient_xFiber_le_marginalWordFiber
#assert_axioms CWCoarseFieldEncoding.card_coordinateType_mul_card_relaxedRecursiveAmbient_xFiber_le
