import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinograd112SymmetricConstituent

/-!
# Trust audit for the symmetric CW `112` profile

This focused audit checks the reusable equivalence-transport lemmas and the finite 64-address
maximum-entropy calculation used by the modern value proof.
-/

#assert_axioms AlgebraicComplexity.ProbabilityVector.entropyBits_pushforward_equiv
#assert_axioms AlgebraicComplexity.WordType.IsMaximumEntropyInMappedFiber.product
#assert_axioms AlgebraicComplexity.WordType.IsMaximumEntropyInMappedFiber.equivCoordinate
#assert_axioms AlgebraicComplexity.WordType.IsMaximumEntropyInMappedFiber.reindex
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricPartitionedTensor_support
#assert_axioms AlgebraicComplexity.Examples.card_cw112SymmetricSupport
#assert_axioms AlgebraicComplexity.Examples.cw112Symmetric_mappedType_eq_marginal
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricProfileProbability_isMaximumEntropy
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricProfileProbability_marginalEntropyBits
#assert_axioms AlgebraicComplexity.PositiveIntegralProfile.mass_cyclicProduct
#assert_axioms AlgebraicComplexity.RationalTypedLeaf.cyclicProduct_dimensionProduct
#assert_axioms AlgebraicComplexity.RationalTypedLeaf.IsMaximumEntropyBits.cyclicProduct
#assert_axioms AlgebraicComplexity.PositiveIntegralProfile.mass_reindex
#assert_axioms AlgebraicComplexity.RationalTypedLeaf.IsMaximumEntropyBits.reindex
#assert_axioms AlgebraicComplexity.RationalTypedLeaf.dimensionProduct_reindex
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricRationalTypedLeaf_dimensionProduct
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricPartitionRationalTypedLeaf_isMaximumEntropyBits
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricPartitionRationalTypedLeaf_dimensionProduct
#assert_axioms AlgebraicComplexity.Examples.cw112SymmetricSupportedConstituent_restricts
