import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradSortedPairCompetitorClassification

/-! Focused trust audit for concrete sorted-pair compatibility competitor classification. -/

#assert_axioms AlgebraicComplexity.Examples.positiveSupportWordBlockAddress_cwSortedPairSupportedWordOfAddress
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairTaggedAtomWord_address_apply
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairTaggedAtomWord_injective
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairTaggedAtomCoarseIndex_atomWord
#assert_axioms AlgebraicComplexity.Examples.multiplicity_jointWord_eq_cellMultiplicity
#assert_axioms AlgebraicComplexity.Examples.multiplicity_jointWord_cells_eq_cellMultiplicity
#assert_axioms AlgebraicComplexity.Examples.cellMultiplicity_subtype_val
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairYCellSymbolJointType_eq_multiplicity_of_compatible
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairZCellSymbolJointType_eq_multiplicity_of_compatible
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairYCompatibleLabelEncoding
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairZCompatibleLabelEncoding
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_compatibleLabelsY_le_conditionalTypeClass
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_compatibleLabelsZ_le_conditionalTypeClass
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_multinomial_YCellType_mul_card_compatibleLabels_le_joint
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_multinomial_ZCellType_mul_card_compatibleLabels_le_joint
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_sum_card_compatibleAddressesY_le_sum_conditionalTypeClasses
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_sum_card_compatibleAddressesZ_le_sum_conditionalTypeClasses
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairYCompetitorTypeClass_eq_conditionalFeatureTypeClass
#assert_axioms AlgebraicComplexity.Examples.cwSortedPairZCompetitorTypeClass_eq_conditionalFeatureTypeClass
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_YCompetitorTypeClass_le_sum_fullJointTypes
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_ZCompetitorTypeClass_le_sum_fullJointTypes
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_YCompetitorTypeClass_le_polynomial_mul
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_ZCompetitorTypeClass_le_polynomial_mul
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_compatibilityCompetitorsY_le_typeClass
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_compatibilityCompetitorsZ_le_typeClass
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_ambient_le_card_YZIsolatedSupport_add_evaluatorTypeCounts
#assert_axioms AlgebraicComplexity.Examples.cwSortedPair_card_ambient_le_card_YZIsolatedSupport_add_fullJointTypeCounts
