import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveCompatibilityContainment

/-! Axiom audit for recursive compatibility catchability on exact and approximate inputs. -/

#assert_axioms AlgebraicComplexity.Examples.cwRecursiveLabelledChildWord_eq_group_Y_of_orientedCompatibleY
#assert_axioms AlgebraicComplexity.Examples.cwRecursiveLabelledChildWord_eq_group_Z_of_orientedCompatibleZ
#assert_axioms AlgebraicComplexity.Examples.cwRecursiveChildGroup_Y_eq_of_orientedCompatibleY
#assert_axioms AlgebraicComplexity.Examples.cwRecursiveChildGroup_Z_eq_of_orientedCompatibleZ
#assert_axioms AlgebraicComplexity.Examples.CWCoarseFieldEncoding.recursiveOrientedLegalTriple_sharesY_of_compatibleY
#assert_axioms AlgebraicComplexity.Examples.CWCoarseFieldEncoding.recursiveOrientedLegalTriple_sharesZ_of_compatibleZ
#assert_axioms AlgebraicComplexity.Examples.CWCoarseFieldEncoding.recursiveY_groupCompetitor_distinct_and_sharesLeg
#assert_axioms AlgebraicComplexity.Examples.CWCoarseFieldEncoding.recursiveZ_groupCompetitor_distinct_and_sharesLeg
#assert_axioms AlgebraicComplexity.Examples.CWCoarseFieldEncoding.relaxedRecursiveOrientedLegalTriple_sharesY_of_approximateCompatibleY
#assert_axioms AlgebraicComplexity.Examples.CWCoarseFieldEncoding.relaxedRecursiveOrientedLegalTriple_sharesZ_of_approximateCompatibleZ
#assert_axioms AlgebraicComplexity.Examples.CWCoarseFieldEncoding.approximateRecursiveY_groupCompetitor_distinct_and_sharesLeg
#assert_axioms AlgebraicComplexity.Examples.CWCoarseFieldEncoding.approximateRecursiveZ_groupCompetitor_distinct_and_sharesLeg
