import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveApproximateInput
import AxiomAudit.Command

open AlgebraicComplexity AlgebraicComplexity.Examples

/-! Focused trust audit for
`AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveApproximateInput`: the construction of
the approximate parent source tensor for a recursive CW constituent -- the semantic parent term
with its multiplicity and index laws, the approximate alpha-marginal selected term and its
parent-position relabeling action, the restrictions built from a flat power of `CW_q`, the
coarsened marginal term with its additivity and coarse-sum laws, and the containment of the
exact selected term. -/

#assert_axioms exactInterfaceTerm_multiplicity_pos_of_eq_succ
#assert_axioms cwRecursiveSemanticParentTerm
#assert_axioms cwRecursiveSemanticParentTerm_multiplicity
#assert_axioms cwRecursiveSemanticParentTerm_index
#assert_axioms cwRecursiveApproximateAlphaMarginalSelectedTerm
#assert_axioms cwRecursiveLeftChildWord_positionRelabel_eq_comp
#assert_axioms cwRecursiveKeepsAlphaMarginal_positionEquiv_iff
#assert_axioms cwRecursiveApproximateAlphaMarginalSelectedTermPositionRelabeling
#assert_axioms cwRecursiveApproximateAlphaMarginalSelectedTermPositionRelabeling_partEquiv
#assert_axioms mem_cwRecursiveApproximateAlphaMarginalSelectedTerm_support
#assert_axioms cwSelectedApproximateInterfaceTerm_restricts_recursiveAlphaMarginals
#assert_axioms cwFlatPower_restricts_recursiveApproximateAlphaMarginals
#assert_axioms cwRecursiveApproximateCoarsenedAlphaMarginalTerm
#assert_axioms cwRecursiveApproximateAlphaMarginalSelectedTerm_restricts_coarsened
#assert_axioms cwRecursive_parentWeight_of_mem_approximateSelected_support
#assert_axioms cwRecursiveChildCompatibilityModel_isFineLegal_of_mem_approximateSelected_support
#assert_axioms cwRecursiveChildCompatibilityModel_isFineLegal_logicalAddress_of_mem_approximateSelected_support
#assert_axioms cwRecursiveApproximateCoarsenedAlphaMarginalTerm_left_add_right
#assert_axioms cwRecursiveApproximateCoarsenedAlphaMarginalTerm_coarse_sum
#assert_axioms cwRecursiveAlphaMarginalSelectedTerm_support_subset_approximate
