import AxiomAudit.Command
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightLocalizedSelection

/-! Focused trust audit for total-weight quotient outputs retaining their localized fine types. -/

#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedFineTypes
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightFineMarginalType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightTypedFiberWords
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightTypedFiberAddresses
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightMarkedFiberWords
#assert_axioms AlgebraicComplexity.Examples.card_cwTotalWeightTypedFiberAddresses
#assert_axioms AlgebraicComplexity.Examples.card_cwTotalWeightMarkedFiberWords
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedAmbientWords
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightTypedFiberAddresses_subset_localizedFineTypes
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedFineTypes_support_subset_positivePower
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightMarkedFiberWords_subset_localizedAmbientWords
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightMarkedFiberWords_type
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedFineTypes_support_eq_modeledAddresses
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedFineTypes_constituent
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedFineTypes_isomorphic_of_sameCoarseType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedMarginalTypes_isomorphic_of_sameCoarseType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedFineTypes_isomorphic_of_mem_sameCoarseType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightLocalizedFineTypes_polynomialDegenerates_of_sameCoarseType
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_coarseConstituent_to_localizedFineTypes
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeight_indexedCoarseConstituents_to_localizedFineTypes
#assert_axioms AlgebraicComplexity.Examples.cwTotalWeightCleanup_to_localizedFineTypes
