/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitAssembly

set_option autoImplicit false

/-! # Axiom audit for the six-orientation value-side assembly -/

#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.positiveSupportWordTensor_external
#assert_axioms AlgebraicComplexity.Tensor.multiplicity_eq_of_full
#assert_axioms AlgebraicComplexity.Tensor.multiplicity_const_word
#assert_axioms AlgebraicComplexity.Tensor.multiplicity_zero_word
#assert_axioms AlgebraicComplexity.Tensor.multiplicity_positiveWord_pair
#assert_axioms AlgebraicComplexity.Tensor.multiplicity_of_injective
#assert_axioms AlgebraicComplexity.Tensor.exists_positiveWord_extract_const
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.positiveSupportWordTensor_split_add
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.positiveSupportWordTensor_peel
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.positiveSupportWordTensor_peel3
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.symSixExt_eq
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.positiveSupportWordTensor_symSixPartition
#assert_axioms AlgebraicComplexity.Tensor.positiveWordEquiv_positiveWordMap_apply
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.symSixWord0_letter
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.symSixWord1_letter
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.symSixWord2_letter
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.symSixWord3_letter
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.symSixWord4_letter
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.symSixWord5_letter
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.deinterleave3
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.regroupPeel3
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.mergePower3
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.power_permute_symThree_external
#assert_axioms AlgebraicComplexity.Tensor.hasTauWeight_positiveSupportWordTensor_symSix
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.orbitTriple_merge
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.symSixHalf_regroup
#assert_axioms AlgebraicComplexity.Tensor.hasTauWeight_symSixHalf
#assert_axioms AlgebraicComplexity.Tensor.hasTauWeight_positiveSupportWordTensor_symSix_of_halves

#assert_axioms AlgebraicComplexity.Examples.dwz63JointIsolatedSupport_subset_retained
#assert_axioms AlgebraicComplexity.Examples.dwz63_hasTauWeight_jointRetained_constituent
#assert_axioms AlgebraicComplexity.Examples.dwz63_hconstituent_of_markedWordTensor
#assert_axioms AlgebraicComplexity.Examples.dwz63_hasTauWeight_permuted_constituent
#assert_axioms AlgebraicComplexity.Examples.dwz63_isomorphic_permuted_orbitConstituent
#assert_axioms AlgebraicComplexity.Examples.dwz63_isomorphic_permuted_orbitConstituent_112
#assert_axioms AlgebraicComplexity.Examples.dwz63_isomorphic_permuted_orbitConstituent_121
#assert_axioms AlgebraicComplexity.Examples.dwz63_isomorphic_permuted_orbitConstituent_211
#assert_axioms AlgebraicComplexity.Examples.dwz63_hasTauWeight_symSixWordTensor_of_halves
#assert_axioms AlgebraicComplexity.Examples.dwz63_multiplicity_symSixWord0
#assert_axioms AlgebraicComplexity.Examples.dwz63_multiplicity_symSixWord1
#assert_axioms AlgebraicComplexity.Examples.dwz63_multiplicity_symSixWord2
#assert_axioms AlgebraicComplexity.Examples.dwz63_multiplicity_symSixWord3
#assert_axioms AlgebraicComplexity.Examples.dwz63_multiplicity_symSixWord4
#assert_axioms AlgebraicComplexity.Examples.dwz63_multiplicity_symSixWord5
