import AxiomAudit.Command
import AlgebraicComplexity.Tensor.LocalizedCoarsenedSelection

/-! Focused trust audit for localized fine selection inside quotient constituents. -/

#assert_axioms AlgebraicComplexity.Tensor.positiveSupportWordBlockAddress_injective
#assert_axioms AlgebraicComplexity.Tensor.positiveWordMap_position_apply
#assert_axioms AlgebraicComplexity.Tensor.positiveWordMap_position_symm_eq_iff
#assert_axioms AlgebraicComplexity.Tensor.positiveWordEquiv_position_symm_apply
#assert_axioms AlgebraicComplexity.Tensor.positiveTypeClass_position_symm_iff
#assert_axioms AlgebraicComplexity.Tensor.positionRelabelBlockAddress
#assert_axioms AlgebraicComplexity.Tensor.positionRelabelBlockAddress_positiveSupportWordBlockAddress
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.coarseningSupportMap
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.positiveSupportWordBlockAddress_coarseningSupportMap
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.coarseningFiberSupport
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.coarseningFiber
#assert_axioms AlgebraicComplexity.Tensor.coarseningFiberSelectParts
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.coarseningFiber_select_eq_box
#assert_axioms AlgebraicComplexity.Tensor.relabelParts_coarseningFiberSelectParts_positiveWordMap
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.positivePower_localizedCoarseningFiberSelect_position
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.positivePower_localizedCoarseningFiberTypes_position
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.typedCoarseningFiberWords
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.typedCoarseningFiberPositiveWord
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.typedCoarseningFiberPositiveWords
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.card_typedCoarseningFiberPositiveWords
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.mem_typedCoarseningFiberPositiveWords_iff
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.positiveWordsOverSupport
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.image_positiveWordsOverSupport_eq
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.typedCoarseningFiberAddress
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.card_typedCoarseningFiberAddresses
#assert_axioms AlgebraicComplexity.Tensor.PartitionedTensor.typedCoarseningFiberAddresses_subset_localizedMarginalTypes
#assert_axioms AlgebraicComplexity.Tensor.Restricts.coarsen_constituent_to_fineFiber
#assert_axioms AlgebraicComplexity.Tensor.Restricts.coarsen_constituent_to_fineFiberSelect
#assert_axioms AlgebraicComplexity.Tensor.Restricts.indexedDirectSum_coarsen_constituent_to_fineFiberSelect
#assert_axioms AlgebraicComplexity.Tensor.Restricts.positivePower_coarsen_constituent
#assert_axioms AlgebraicComplexity.Tensor.Restricts.coarsenedPositivePower_constituent_to_fineFiberSelect
#assert_axioms AlgebraicComplexity.Tensor.Restricts.indexedDirectSum_coarsenedPositivePower_constituent_to_fineFiberSelect
