import AxiomAudit.Command
import AlgebraicComplexity.MatrixMultiplication.NestedLaserVolumeComposition

/-! Focused trust audit for outer-constituent/inner-family laser-volume composition. -/

#assert_axioms AlgebraicComplexity.OuterConstituentStage.ofIndexedConstituents
#assert_axioms AlgebraicComplexity.OuterConstituentStage.precompose
#assert_axioms AlgebraicComplexity.OuterConstituentStage.hasUniformInnerExtraction_ofDependentFamilies
#assert_axioms AlgebraicComplexity.OuterConstituentStage.hasUniformInnerExtraction_of_isomorphicReference
#assert_axioms AlgebraicComplexity.OuterConstituentStage.nestDependentFamilies
#assert_axioms AlgebraicComplexity.OuterConstituentStage.polynomialDegenerates_nested
#assert_axioms AlgebraicComplexity.NestedLaserVolumeSequenceData.toSubexponentialLaserVolumeSequence_addRetained
#assert_axioms AlgebraicComplexity.OuterConstituentSequenceData.toNestedLaserVolumeSequenceData
#assert_axioms AlgebraicComplexity.OuterConstituentSequenceData.toSubexponentialLaserVolumeSequence
#assert_axioms AlgebraicComplexity.OuterConstituentSequenceData.toSubexponentialLaserVolumeSequence_addRetained
