import AxiomAudit.Command
import AlgebraicComplexity.Combinatorics.RecursiveSplitMarginalCounting

/-! Focused trust audit for the exact marginal-family counts of recursive split words. -/

#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactRecursiveSplitType.mem_marginalWords
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactRecursiveSplitType.mem_markedWords
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactRecursiveSplitType.markedWords_subset_marginalWords
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactRecursiveSplitType.card_markedWords
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactRecursiveSplitType.mem_marginalWordFiber
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactRecursiveSplitType.mem_marginalWords_reindex_iff
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactRecursiveSplitType.card_marginalWordFiber_eq_of_multiplicity_eq
#assert_axioms AlgebraicComplexity.MoreAsymmetryCompatibility.ExactRecursiveSplitType.card_coordinateType_mul_card_marginalWordFiber
