import AxiomAudit.Command
import AlgebraicComplexity.Analysis.StructuralZeroMultinomial

/-! Focused trust audit for structural-zero-safe method-of-types estimates. -/

#assert_axioms AlgebraicComplexity.WordType.factorialEntropyTerm_pos_zeroSafe
#assert_axioms AlgebraicComplexity.WordType.log_proportionalEntropyBase_of_profileMass_pos
#assert_axioms AlgebraicComplexity.WordType.multinomial_le_exp_profileEntropy
#assert_axioms AlgebraicComplexity.WordType.structuralZeroMultinomialLoss_pos
#assert_axioms AlgebraicComplexity.WordType.structuralZeroMultinomialLoss_subexponential
#assert_axioms AlgebraicComplexity.WordType.proportionalEntropyBase_pow_le_structuralZeroLoss_mul_multinomial
#assert_axioms AlgebraicComplexity.WordType.proportionalEntropyBase_eq_exp_profileEntropy
#assert_axioms AlgebraicComplexity.WordType.card_conditionalTypeClass_le_structuralZeroLoss_mul_exp_entropyDifference
#assert_axioms AlgebraicComplexity.WordType.card_conditionalFeatureTypeClass_le_uniform_entropy
#assert_axioms AlgebraicComplexity.WordType.card_conditionalFeatureTypeClass_le_uniform_entropy_of_sourceMarginal
