import AxiomAudit.Command
import MatrixMultiplication.TotalWeightVolumeEndpoint

/-! Focused trust audit for the total-weight certificate endpoint. -/

#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.volumeFloor_pos
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omegaTarget_nonneg
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omegaTarget_lt_acceptanceTarget
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.acceptanceTarget_nonneg
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.acceptanceRetainedFloor_pos
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.acceptanceRetainedFloor_eq_outer_add_inner
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.volumeFloor_lt_generatedMean
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.certified_endpoint_slack
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.certified_acceptance_slack
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.acceptanceReconstruction_addRetained
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omega_lt_236588731_of_subexponentialVolumeSequence
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omega_lt_236588731_of_wholeConstituentSequenceData
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omega_lt_236999_of_subexponentialVolumeSequence
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omega_lt_236999_of_wholeConstituentSequenceData
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omega_lt_236999_of_subexponentialVolumeSequence_acceptanceFloors
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omega_lt_236999_of_wholeConstituentSequenceData_acceptanceFloors
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omega_lt_236999_of_subexponentialVolumeSequence_outer_inner_floors
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.omegaTarget_eq_decimal
#assert_axioms MatrixMultiplication.TotalWeightVolumeEndpoint.acceptanceTarget_eq_decimal
