import AxiomAudit.Command
import MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards

/-! Axiom audit for the eight-shard level-two active-edge reduction. -/

#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.cached
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.range_split
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.shard0
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.shard1
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.shard2
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.shard3
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.shard4
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.shard5
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.shard6
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.shard7
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.cached_reassemble
#assert_axioms MatrixMultiplication.TotalQuotientLevelTwoActiveEdgeShards.activeEdges_eq
