import AxiomAudit.Command
import MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate

/-! Axiom audit for the level-two branch-floor certificate of the total-weight quotient candidate. -/

#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.activeEdges_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.expectedInputChunks
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.expectedInputs
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.activeInputs_eq_expected
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.expectedBranch0_normalize
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.expectedBranch1_normalize
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.expectedBranch2_normalize
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.certifiedTables
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.certifiedMassThree
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.certifiedTargets
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.branchForm_normalize
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.levelTwoFloor_eq_commonFloor
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.levelTwoFloor_le_target
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.branchFloorCertified
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.innerRetainedFloor_le_levelTwoFamilyExponent
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoCertificate.innerRetainedFloor_le_retainedExponent
