import AxiomAudit.Command
import MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo

/-! Axiom audit for the depth-one (paper level-two) total-weight acceptance assembly. -/

#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.levelTwo_align
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.levelTwo_massIdentity
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.xWordCapacityBase_one
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.outerBase_le_xWordCapacity_levelTwo
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.capacity_decay
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.xWordCapacity_lt_outerBase_of_two_le_depth
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.levelTwoGrowthDatum
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.levelTwoGrowthDatum_exponent
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.outerData
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.outerData_spec
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.omega_lt_236999_of_levelTwoEmbeddedCanonicalInner
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.omega_lt_236999_of_named_inputs_levelTwo
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.levelTwo_letterBudget
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.card_cwChunkSupport_levelTwo
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.card_cwChunkSupport_levelTwo_le_mass
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.witnessOuterFloorLevelTwo
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.levelTwoPointProfile
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.exists_growthDatum_matching_levelTwoOuterExponent
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.levelTwoPointLeaf_volume_ge
#assert_axioms MatrixMultiplication.TotalWeightAcceptanceAssemblyLevelTwo.fullSupport_volumeLetters_le
