import AxiomAudit.Command
import AlgebraicComplexity.Examples.TwoLetterAggregateInterface

/-!
# Focused axiom audit for two-letter aggregate interfaces

This narrow target checks the exact multiplicity, empirical-probability, rational-profile, and
tensor-semantic boundaries without importing the certificate reconstruction stack.
-/

#assert_axioms AlgebraicComplexity.WordType.HasAggregateInterface.append_eq
#assert_axioms AlgebraicComplexity.WordType.hasAggregateInterface_of_proportionalProfile
#assert_axioms AlgebraicComplexity.ProbabilityVector.positiveEmpiricalDistribution_hasAggregateInterface
#assert_axioms AlgebraicComplexity.ProbabilityVector.positiveEmpiricalDistribution_hasUnequalAggregateInterface
#assert_axioms AlgebraicComplexity.ProbabilityVector.IsCoupling.aggregateInterface_marginals
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.external_positiveSupportWordTensor_aggregateInterface
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.external_positiveSupportWordTensor_unequalAggregateInterface
#assert_axioms AlgebraicComplexity.Tensor.Isomorphic.external_positiveSupportWordTensor_proportionalProfileAggregateInterface
#assert_axioms AlgebraicComplexity.Tensor.Restricts.external_positiveSupportWordTensor_aggregateInterface
#assert_axioms AlgebraicComplexity.Tensor.Restricts.external_positiveSupportWordTensor_unequalAggregateInterface
#assert_axioms AlgebraicComplexity.Tensor.Restricts.external_positiveSupportWordTensor_proportionalProfileAggregateInterface
#assert_axioms AlgebraicComplexity.Examples.duplicatedEndpoints_isomorphic_balancedPair
