import AxiomAudit.Command
import AlgebraicComplexity.Combinatorics.TypeClassCounting

/-! Focused trust audit for the arbitrary-length method of types: the two explicit polynomial
losses, the type-class upper/lower pair, the type pigeonhole and the ambient lower bound, the
conditional-fibre pair, and the base-two sequence-ready packaging. -/

#assert_axioms AlgebraicComplexity.WordType.typeCountLoss_pos
#assert_axioms AlgebraicComplexity.WordType.typeCountLoss_subexponential
#assert_axioms AlgebraicComplexity.WordType.card_types_le_typeCountLoss
#assert_axioms AlgebraicComplexity.WordType.typeClassEntropyLoss_pos
#assert_axioms AlgebraicComplexity.WordType.typeClassEntropyLoss_subexponential
#assert_axioms
  AlgebraicComplexity.WordType.structuralZeroMultinomialLoss_one_le_typeClassEntropyLoss
#assert_axioms AlgebraicComplexity.WordType.profileMass_eq_of_mem_types
#assert_axioms AlgebraicComplexity.WordType.card_typeClass_le_exp_profileEntropy
#assert_axioms
  AlgebraicComplexity.WordType.exp_profileEntropy_le_typeClassEntropyLoss_mul_card_typeClass
#assert_axioms
  AlgebraicComplexity.WordType.card_le_exp_profileEntropy_of_forall_multiplicity_eq
#assert_axioms AlgebraicComplexity.WordType.card_le_typeCountLoss_mul_exp_of_entropy_le
#assert_axioms AlgebraicComplexity.WordType.exists_type_card_le_card_types_mul_card_filter
#assert_axioms AlgebraicComplexity.WordType.exists_type_card_le_typeCountLoss_mul_card_filter
#assert_axioms
  AlgebraicComplexity.WordType.exists_type_alphabet_pow_le_card_types_mul_card_typeClass
#assert_axioms
  AlgebraicComplexity.WordType.exists_type_alphabet_pow_le_typeCountLoss_mul_card_typeClass
#assert_axioms AlgebraicComplexity.WordType.card_types_prod_le
#assert_axioms
  AlgebraicComplexity.WordType.card_typedWordMapFiber_le_typeClassEntropyLoss_mul_exp_entropyDifference
#assert_axioms
  AlgebraicComplexity.WordType.exp_entropyDifference_le_typeClassEntropyLoss_mul_card_typedWordMapFiber
#assert_axioms AlgebraicComplexity.WordType.two_rpow_mul_profileEntropyBits
#assert_axioms AlgebraicComplexity.WordType.card_typeClass_le_two_rpow_profileEntropyBits
#assert_axioms
  AlgebraicComplexity.WordType.two_rpow_profileEntropyBits_le_typeClassEntropyLoss_mul_card_typeClass
#assert_axioms AlgebraicComplexity.WordType.proportionalEntropyBase_eq_two_rpow
#assert_axioms
  AlgebraicComplexity.WordType.two_rpow_profileEntropyBits_pow_le_structuralZeroLoss_mul_card_typeClass
#assert_axioms
  AlgebraicComplexity.WordType.exists_subexponential_loss_two_rpow_pow_le_mul_card_typeClass
#assert_axioms
  AlgebraicComplexity.WordType.exists_cutoff_forall_pow_le_card_proportionalTypeClass
