/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.Combinatorics.HashingSeedHoleMass
import AlgebraicComplexity.Combinatorics.MappedTypeIdentities
import AlgebraicComplexity.Combinatorics.ProductUniformOnParts
import AlgebraicComplexity.Combinatorics.WordTypeMultiplicityFilter
import AlgebraicComplexity.MatrixMultiplication.PartitionedSymmetrization
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStageFamily
import AlgebraicComplexity.MatrixMultiplication.PartitionedSymmetrizedHashing
import AlgebraicComplexity.MatrixMultiplication.CompatibilityIsolationIncidenceMono
import AlgebraicComplexity.MatrixMultiplication.PartitionedSymmetrizedCompatibility
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoJointHashing
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSeedCancellation
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCopyCount
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrientationTypical
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoLegMarginal
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainMarginalAmbient
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineExpansion
import AlgebraicComplexity.MatrixMultiplication.SegmentedSplitRestriction
import AlgebraicComplexity.MatrixMultiplication.SegmentedAvailableWord
import AlgebraicComplexity.MatrixMultiplication.SegmentedAvailableWordShuffle
import AlgebraicComplexity.MatrixMultiplication.SegmentedHoleRepair
import AlgebraicComplexity.MatrixMultiplication.SegmentedHoleRepairGeneral
import AlgebraicComplexity.Tensor.LocalizedCoarsenedRelabeling
import AlgebraicComplexity.MatrixMultiplication.SegmentedFiberUniformity
import AlgebraicComplexity.MatrixMultiplication.SegmentedLocalizedHoleRepair
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSegmentedFineLeaf
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSegmentationData
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSegmentedFiberStabilizer
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSegmentedBreaking
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainMarginalSelect
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoHoleSupplier
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainGroupedStage
import AlgebraicComplexity.MatrixMultiplication.IndexedTauWeight
import AlgebraicComplexity.MatrixMultiplication.SymThreeCycleInvariance
import AlgebraicComplexity.MatrixMultiplication.SymSixDistribution
import AlgebraicComplexity.MatrixMultiplication.SymSixUniformLeaf
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoLocalizedStage
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoGroupedLeaf
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoBatching
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainHoleBudget
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoHoleFractionRefutation
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoAggregateHoleBudget
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoAggregateBatching
import AlgebraicComplexity.MatrixMultiplication.RestrictedSplittingValue
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoIsolatedBypass
import AlgebraicComplexity.MatrixMultiplication.SymSixPowerWeight
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCofinalIndex
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitCounting
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoAlphaAddressCells
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoAlphaTilde
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCompatibilityModel
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSeedHoleMass
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSeedSelection
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSeedInputs
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCompetitorCount
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCompetitorBound
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCompetitorRateBrick
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCompatibilityTypeCount
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCompatibilityRateIdentity
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoConstituentValues
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCopyCountRetention
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainCount
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoHashRetention
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSharpDegree
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainFiberCount
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCountComparison
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoEncodingComponent
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellOneSlice
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellWord
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellOnes
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellBase
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellPower
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellSupport
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellZeroLeg
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellPowerSupport
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellUniform
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellLiveLegs
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellResum
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellBridge
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellInjective
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineProfiles
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoTargetTypical
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSixOrientationDigits
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoLegDigitCount
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoTargetWordCount
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSharpFiberBound
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoHashingBranchRate
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoInstanceData
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoIntegration
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoIntegrationSharp
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoIntegrationMarkedFamily
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoMarginalAmbientFiber
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoMarginalAmbientFiberCount
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoMarkedRate
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoMarkedLossHash
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainRate
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainSharpDegree
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainMarkedBranch
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoJointHashBranch
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoLeafBookkeeping
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoLeafTauWeight
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoLeafTauWeightBeta
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoLeafTauWeightOrbit
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoMarginalAmbientFamily
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoMarginalAmbientSelect
import AlgebraicComplexity.MatrixMultiplication.WordTensorReindex
import AlgebraicComplexity.MatrixMultiplication.WordTensorSplitAuto
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSixOrientationValues
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitTag
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoTensorSideEndpoint
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitAssembly
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitAssemblyValue
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainCopyCount
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainIntegration
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainStage
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainOpenIntegration
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainBatchedEndpoint
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainBatchLoss
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainFineBridge
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainLeafValue
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainLeafValueDischarge
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainRetainedSum
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainUniformBatch
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainZCeiling
import AlgebraicComplexity.Tensor.CoarsenedSupportPreimage
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPreimageAmbient
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPreimageGroupedSum
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPreimageLeaf
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPreimageStage
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSquareHashEncoding
import AlgebraicComplexity.MatrixMultiplication.SegmentedLocalizedSplittingValue
import AlgebraicComplexity.Combinatorics.AggregateHoleFraction
import AlgebraicComplexity.Combinatorics.DomainWordShuffle
import AlgebraicComplexity.Combinatorics.GroupCoarsePairCounting
import AlgebraicComplexity.Combinatorics.SplitRequirementsLetterPushforward
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoEntropyXUpper
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainBatchedEndpointMargin
import AlgebraicComplexity.MatrixMultiplication.CyclicTypedLeafMarginal
import AlgebraicComplexity.MatrixMultiplication.RationalTypedLeafMarginalReindex
import AlgebraicComplexity.Tensor.CoordinateTensorSingle
import AlgebraicComplexity.Tensor.PartitionedProductConstituent
import AlgebraicComplexity.Tensor.PartitionedSelectPositivePower
import AlgebraicComplexity.Tensor.PartitionedBlockMap
import AlgebraicComplexity.Tensor.PartitionedSelectStructure
import AlgebraicComplexity.Tensor.PartitionedBlockMapPower
import AlgebraicComplexity.Examples.CoppersmithWinograd112TypedRestriction
import AlgebraicComplexity.MatrixMultiplication.PositiveWordTypeTransport
import AlgebraicComplexity.Tensor.PartitionedPermutePower
import AlgebraicComplexity.Tensor.PositiveWordAppendConst
import AlgebraicComplexity.MatrixMultiplication.SegmentMultiplicityReflect
import AlgebraicComplexity.MatrixMultiplication.SegmentedAvailableWordNonempty
import AlgebraicComplexity.MatrixMultiplication.SegmentedFiberIndependenceProof
import AlgebraicComplexity.Examples.CoppersmithWinogradPartitionRotation
import AlgebraicComplexity.Examples.CoppersmithWinogradPartitionRotationPower
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellRotatedCertificate
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineComplementaryLetter
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellFusion
import AlgebraicComplexity.MatrixMultiplication.TauValueConstantDirectSum
import AlgebraicComplexity.MatrixMultiplication.AggregateHoleBudget
import AlgebraicComplexity.MatrixMultiplication.AggregateHoleBudgetAssembly
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSplitParameterBridge
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellWeight
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFinePairSum
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoGlobalStageRate
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSplitAlphabetBridge
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoLeftPairBridge
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainPushedBases
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainLegFibreGrowth
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCountComparisonInputs
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoCofinalCompetitorDegree
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoEntropyAlphaLower
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoMarkedWitness
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoReferenceWord
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSharpDegreeElevenLower
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoIsolatedSumRate
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainBatchedEndpointMarginVariant
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainBatchedEndpointMarked
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainBatchedEndpointSeeded
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainBatchedEndpointSeededLoss
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoTripleEntropyBound
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoMarkedHashJointLoss
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoMarkedHashBranch
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoBranchGrowth
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainBatchedEndpointMarkedLoss
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoTypicalSetNonempty
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoPlainModulusBranch
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoUniformCompetitorCoarse
import AlgebraicComplexity.MatrixMultiplication.SupportedAddressWholeStage
import AlgebraicComplexity.MatrixMultiplication.RegionalConstituentStage
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoHoleIntegrationAvailability
import AlgebraicComplexity.MatrixMultiplication.PartitionedSymmetrizationSelect
import AlgebraicComplexity.MatrixMultiplication.PartitionedSymmetrizationPower
import AlgebraicComplexity.Examples.CoppersmithWinogradRecursivePresentExactTargetFiber
import AlgebraicComplexity.MatrixMultiplication.CoarsenedConstituentWholeStage
import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveApproximateWholeInnerStage
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellRate
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellHypotheses
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellRows
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellSurjective
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellEntropy
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellGeneral
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellTwoTwoZero
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellTwoTwoZeroParity
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoGoodBatchSizeGrowth
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoHoleIntegrationSeedArith
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoHoleIntegrationSeedJoin
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSeedLargeBatch
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneKeep
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCompatible
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCompatiblePosition
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCompatibleCut
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutHoles
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutDominationInputs
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutDomination
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutGroupedSum
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutLeafKeep
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutLeafFiber
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutLeaf
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutStage
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutStageUnconditional
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneLeftKeep
import AlgebraicComplexity.MatrixMultiplication.SegmentedLocalizedDivision
import AlgebraicComplexity.MatrixMultiplication.SegmentedLocalizedDivisionIterated
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellRegional
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellZeroZ
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellJoined
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoFineCellOrbit
import AlgebraicComplexity.Examples.CoppersmithWinograd112TypedRestrictionPower
import AlgebraicComplexity.Examples.CoppersmithWinograd112TypedRestrictionTransport
import AlgebraicComplexity.Examples.CoppersmithWinograd112TypedRestrictionCut
import AlgebraicComplexity.Examples.CoppersmithWinograd112LegTypedTransport
import AlgebraicComplexity.Examples.CoppersmithWinograd112SymmetricTypedCut
import AlgebraicComplexity.Examples.CoppersmithWinograd112SymmetricMarginalCut
import AlgebraicComplexity.Examples.CoppersmithWinograd112SymmetricMarginalCutImp
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitRotatedRegion
import AlgebraicComplexity.Examples.CoppersmithWinograd112LegTypedCut
import AlgebraicComplexity.Examples.CoppersmithWinograd112SymmetricSideMarginal
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitRowSixWeight
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitRowSixAmbientWeight
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitRowSixCanonical
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitBetaAmbientWeight
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitBetaWeight
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOrbitBetaCanonical
import AlgebraicComplexity.MatrixMultiplication.SegmentedConsecutiveBlocks
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoConsecutiveSegments
import AlgebraicComplexity.MatrixMultiplication.SegmentedLocalizedDivisionSymSix
import AlgebraicComplexity.MatrixMultiplication.SegmentedRegionalConstantTarget
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoRegionalTarget
import AlgebraicComplexity.MatrixMultiplication.SegmentedRegionalAssembly
import AlgebraicComplexity.MatrixMultiplication.SegmentedRegionalOneSegmentBridge
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoRegionalCellEntry
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoRegionalCells
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoRegionalLeafAssembly
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoAssembly
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoRegionalLeafWeight
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutAssemblyMarked
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoAssemblyMarked
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoAssemblyMarkedSeededLoss
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoAssemblyRowSix
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoAssemblyOrbitClosure
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutSeedStage
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoStepOneCutCountInputs
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoSeededPeriod
import AlgebraicComplexity.Examples.DuanWuZhouLevelTwoOmegaBound
import AlgebraicComplexity.Tensor.LocalizedCoarsenedSelectionBridge
import AlgebraicComplexity.Tensor.ModeledPreimagePartition
import AlgebraicComplexity.Examples.OrderingFreeAsymmetricHashingExample

set_option autoImplicit false

/-!
# The Duan--Wu--Zhou level-two tier

Umbrella for the level-two (`\ell = 2`) global-hashing development of `[duan2023faster]`.  It
declares nothing: it imports, in dependency order, the 266 library modules of the tier so that a
single configured Lake target builds them and a single `#axiom_census` closure covers them.

Why an umbrella and not a plain directory: Lake builds a library's configured roots and the
imports reachable from them, so a `.lean` file placed below a library root is not part of any
build until something imports it.  Before this module the tier was compiled only as a side effect
of the focused `AxiomAudit/` companions that import each module, which put it inside the build but
outside every census closure -- exactly the hole `scripts/check_source_coverage.sh` reports as
"built only because a focused audit imports them".  `AxiomAudit/DuanWuZhouLevelTwo.lean` is the
matching audit-side umbrella, and `AxiomAudit/CensusAll.lean` names this module explicitly, the
way it already names `Frontier`, because no other library umbrella imports it.

The mathematics lives in the imported modules; each states in its own docstring which sentence of
the paper it transcribes.

Primary source `[duan2023faster]`: Ran Duan, Hongxun Wu and Renfei Zhou, *Faster Matrix
Multiplication via Asymmetric Hashing*, arXiv:2210.10173, section 6.1 `sec:global-algo`,
`papers/sources/2210.10173/global_value.tex`.
-/
