/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.CertificateDerivedLeafVolumeBudget

/-!
# Axiom audit for certificate-derived per-leaf volume budgets

This audit lives in the **opt-in certificate tier** because the module it audits reads the
generated total-weight volume datum
`MatrixMultiplication.Generated.TotalQuotientVolumeScalar.volumeFloor`; an ordinary focused audit
may not reach generated certificate data.

Every public declaration of `MatrixMultiplication/CertificateDerivedLeafVolumeBudget.lean` is
asserted directly: the certificate-derived rate and its comparisons against the committed
hand-floored leg census, the leaf classification and its per-class rates, the census-free
aggregation over an exact division tree, the lossless fold through `LeafStages.toPacked`, and the
two `volume_growth` instantiations at the nominal and backed-off volume exponents.
-/

#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateWordVolumeBits
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateWordVolumeBits_eq
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateWordVolumeBits_nonneg
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateWordVolumeBits_pos
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateWordVolumeBits_lt_scalarCoordinateSum
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateStrideVolumeBits
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateStrideVolumeBits_eq
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateStrideVolumeBudget
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateStrideVolumeBudget_le_certificateStrideVolumeBits
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.leafExponentBudget_lt_certificateStrideVolumeBudget
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.legBudgets_lt_certificateStrideVolumeBudget
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.nominalVolume_le_certificateStrideVolumeBits
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.backedOffVolume_le_certificateStrideVolumeBits

#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.LeafVolumeClass
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.leafVolumeClass
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.leafVolumeClass_of_multiplicity_zero
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.leafVolumeClass_eq_positive
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.leafVolumeClass_eq_zeroOriented_X
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.ClassVolumeRates
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateRates
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateRates_rate
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateRates_rate_eq
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateRates_rate_empty
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateRates_rate_zeroOriented
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateRates_rate_positive
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.ClassVolumeRates.DominatesCertificate
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateRates_dominatesCertificate

#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.leafVolumeBits
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.leafVolumeBits_nonneg
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.leafVolumeBits_of_multiplicity_zero
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.treeVolumeBits
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.treeVolumeBits_leaf
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.treeVolumeBits_branch
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificate_le_treeVolumeBits

#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.MeetsBudget
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.meetsBudget_leaf
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.meetsBudget_branch
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.meetsBudget_zeroMultiplicity
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.meetsBudget_zero
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.two_rpow_treeVolumeBits_le_toPacked
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.two_rpow_treeVolumeBits_le_toPowerPacked
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.two_rpow_certificate_le_toPowerPacked

#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.volume_growth_of_aggregate
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.StrideBlockLeafCensus
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.certificateStrideVolumeBits_mul_eq
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.volume_growth_nominal_of_census
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.volume_growth_backedOff_of_census
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.volume_growth_of_classifiedLeafStages
#assert_axioms MatrixMultiplication.CertificateDerivedLeafVolumeBudget.volume_growth_backedOff_of_classifiedLeafStages
