/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import MatrixMultiplication.CertificateDerivedPerTreeForestBudget
import AxiomAudit.Command

/-! Certificate-tier axiom audit for the per-tree exact-division forest budget layer. -/

#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.positiveWordSum_positiveWordConst
#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.positiveNatProduct_positiveWordConst
#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.positiveProductToBlockedPowerPacked_copies
#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.positiveProductToBlockedPowerPacked_xSize
#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.positiveProductToBlockedPowerPacked_ySize
#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.positiveProductToBlockedPowerPacked_zSize
#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.forestMeetsBudget_positiveWordConst
#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.positiveWordSum_positiveWordConst_eq_strideValue_mul
#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.eventualForestStageData_of_treeProducts
#assert_axioms MatrixMultiplication.CertificateDerivedPerTreeForestBudget.eventualUniformForestStageData
