/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import MatrixMultiplication.CertificateDerivedForestVolumeBudget
import AxiomAudit.Command

/-! Certificate-tier axiom audit for certificate-derived exact-division forest budgets. -/

#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.ForestMeetsBudget
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.forestMeetsBudget_zero
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.forestMeetsBudget_succ
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.forestVolumeBits
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.forestVolumeBits_zero
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.forestVolumeBits_succ
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.CarriesWordRate
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.carriesCertificateWordRate_of_dominates
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.two_rpow_forestVolumeBits_le_positiveProduct
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.two_rpow_wordRate_le_positiveProduct
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.two_rpow_certificate_le_positiveProduct
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.nominalVolumeGrowth_of_forestCarriesCertificate
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.nominalVolumeGrowth_of_forestMeetsBudget
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.eventualForestStageData_of_aggregateBudget
#assert_axioms MatrixMultiplication.CertificateDerivedForestVolumeBudget.eventualForestStageData_of_meetsBudget
