/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.Generated.LegalHybridQ20ModeSchedule

set_option autoImplicit false

/-!
# Focused axiom audit for the legal-hybrid q20 mode schedule

This companion covers the exact 225-row schedule and complete 60-row exceptional-reader mask used
by the candidate described at `better_bound/paper.tex:148-159`.  It audits finite data and its
regional count/shape facts only.  It does not assert a reader-realization theorem, tensor
restriction, analytic inequality, or exponent endpoint.
-/

namespace MatrixMultiplication.Generated

#assert_axioms LegalHybridQ20ModeSchedule.instNeZeroPositiveLevelFourShapeCount
#assert_axioms LegalHybridQ20ModeSchedule.RowMode
#assert_axioms LegalHybridQ20ModeSchedule.instDecidableEqRowMode
#assert_axioms LegalHybridQ20ModeSchedule.instReprRowMode
#assert_axioms LegalHybridQ20ModeSchedule.RowAction
#assert_axioms LegalHybridQ20ModeSchedule.instDecidableEqRowAction
#assert_axioms LegalHybridQ20ModeSchedule.instReprRowAction
#assert_axioms LegalHybridQ20ModeSchedule.RowAction.mode
#assert_axioms LegalHybridQ20ModeSchedule.RowKey
#assert_axioms LegalHybridQ20ModeSchedule.ModeRecord
#assert_axioms LegalHybridQ20ModeSchedule.instDecidableEqModeRecord
#assert_axioms LegalHybridQ20ModeSchedule.instReprModeRecord
#assert_axioms LegalHybridQ20ModeSchedule.orientationLogicalToPhysical
#assert_axioms LegalHybridQ20ModeSchedule.orientationLogicalToPhysical_zero
#assert_axioms LegalHybridQ20ModeSchedule.orientationLogicalToPhysical_one
#assert_axioms LegalHybridQ20ModeSchedule.orientationLogicalToPhysical_two

#assert_axioms LegalHybridQ20ModeSchedule.regionZeroRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.regionOneRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.regionTwoRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.regionThreeRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.regionFourRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.regionFiveRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.regionZeroRowKeys_length
#assert_axioms LegalHybridQ20ModeSchedule.regionOneRowKeys_length
#assert_axioms LegalHybridQ20ModeSchedule.regionTwoRowKeys_length
#assert_axioms LegalHybridQ20ModeSchedule.regionThreeRowKeys_length
#assert_axioms LegalHybridQ20ModeSchedule.regionFourRowKeys_length
#assert_axioms LegalHybridQ20ModeSchedule.regionFiveRowKeys_length
#assert_axioms LegalHybridQ20ModeSchedule.regionZeroRowKeys_nodup
#assert_axioms LegalHybridQ20ModeSchedule.regionOneRowKeys_nodup
#assert_axioms LegalHybridQ20ModeSchedule.regionTwoRowKeys_nodup
#assert_axioms LegalHybridQ20ModeSchedule.regionThreeRowKeys_nodup
#assert_axioms LegalHybridQ20ModeSchedule.regionFourRowKeys_nodup
#assert_axioms LegalHybridQ20ModeSchedule.regionFiveRowKeys_nodup
#assert_axioms LegalHybridQ20ModeSchedule.regionalRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.activeRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.activeRowKeys_length
#assert_axioms LegalHybridQ20ModeSchedule.activeRowKeys_nodup

#assert_axioms LegalHybridQ20ModeSchedule.regionOneMixedModeRecords
#assert_axioms LegalHybridQ20ModeSchedule.regionFourMixedModeRecords
#assert_axioms LegalHybridQ20ModeSchedule.regionOneMixedModeRecords_length
#assert_axioms LegalHybridQ20ModeSchedule.regionFourMixedModeRecords_length
#assert_axioms LegalHybridQ20ModeSchedule.regionOneMixedModeRecords_valid
#assert_axioms LegalHybridQ20ModeSchedule.regionFourMixedModeRecords_valid
#assert_axioms LegalHybridQ20ModeSchedule.mixedModeRecords
#assert_axioms LegalHybridQ20ModeSchedule.mixedModeRecords_length
#assert_axioms LegalHybridQ20ModeSchedule.mixedRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.mixedRowKeys_nodup
#assert_axioms LegalHybridQ20ModeSchedule.mixedRowKeys_subset_active
#assert_axioms LegalHybridQ20ModeSchedule.modeBRowKeys
#assert_axioms LegalHybridQ20ModeSchedule.modeBRowKeys_length
#assert_axioms LegalHybridQ20ModeSchedule.modeBRowKeys_subset_active

#assert_axioms LegalHybridQ20ModeSchedule.modeOfKey
#assert_axioms LegalHybridQ20ModeSchedule.actionOfKey
#assert_axioms LegalHybridQ20ModeSchedule.modeOfKey_eq_none_iff
#assert_axioms LegalHybridQ20ModeSchedule.actionOfKey_eq_none_iff
#assert_axioms LegalHybridQ20ModeSchedule.rowKey
#assert_axioms LegalHybridQ20ModeSchedule.rowKey_mem_active
#assert_axioms LegalHybridQ20ModeSchedule.rowMode
#assert_axioms LegalHybridQ20ModeSchedule.rowAction
#assert_axioms LegalHybridQ20ModeSchedule.modeOfKey_rowKey
#assert_axioms LegalHybridQ20ModeSchedule.actionOfKey_rowKey
#assert_axioms LegalHybridQ20ModeSchedule.rowAction_mode

#assert_axioms LegalHybridQ20ModeSchedule.regionalRowCount
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeACount
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeBCount
#assert_axioms LegalHybridQ20ModeSchedule.regionalActionCount
#assert_axioms LegalHybridQ20ModeSchedule.regionalRowCount_zero
#assert_axioms LegalHybridQ20ModeSchedule.regionalRowCount_one
#assert_axioms LegalHybridQ20ModeSchedule.regionalRowCount_two
#assert_axioms LegalHybridQ20ModeSchedule.regionalRowCount_three
#assert_axioms LegalHybridQ20ModeSchedule.regionalRowCount_four
#assert_axioms LegalHybridQ20ModeSchedule.regionalRowCount_five
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeACount_zero
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeACount_one
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeACount_two
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeACount_three
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeACount_four
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeACount_five
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeBCount_zero
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeBCount_one
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeBCount_two
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeBCount_three
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeBCount_four
#assert_axioms LegalHybridQ20ModeSchedule.regionalModeBCount_five
#assert_axioms LegalHybridQ20ModeSchedule.regionalActionCounts_zero
#assert_axioms LegalHybridQ20ModeSchedule.regionalActionCounts_one
#assert_axioms LegalHybridQ20ModeSchedule.regionalActionCounts_two
#assert_axioms LegalHybridQ20ModeSchedule.regionalActionCounts_three
#assert_axioms LegalHybridQ20ModeSchedule.regionalActionCounts_four
#assert_axioms LegalHybridQ20ModeSchedule.regionalActionCounts_five
#assert_axioms LegalHybridQ20ModeSchedule.totalModeCounts
#assert_axioms LegalHybridQ20ModeSchedule.totalActionCounts

#assert_axioms LegalHybridQ20ModeSchedule.row44_key
#assert_axioms LegalHybridQ20ModeSchedule.row44_mode
#assert_axioms LegalHybridQ20ModeSchedule.row44_action
#assert_axioms LegalHybridQ20ModeSchedule.row44_parentShape

end MatrixMultiplication.Generated
