import AxiomAudit.Command
import MatrixMultiplication.SimplifiedRecursiveChildProfiles

/-!
# Axiom audit for exact level-three recursive child profiles

These checks cover the semantic bridge from guarded level-two evaluator rows to a normalized
level-three complete-split term.  In particular, both normalization and the pointwise recurrence
must be kernel proofs rather than certificate assumptions.
-/

#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelTwoWordCountAt_supported
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelTwoWordCountAtFor_supported
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeLeftChild_evaluatorTotal
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeRightChild_evaluatorTotal
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeLeftChildProfileFor_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeRightChildProfileFor_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeRecursiveParentTermFor_multiplicity
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeRecursiveParentTermFor_split_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeParentRowsValidFor_of_childRows
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeCheckedParentTermFor_split_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeLeftChildProfile_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeRightChildProfile_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeRecursiveParentTerm_multiplicity
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeRecursiveParentTerm_split_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeParentRowsValid_of_childRows
#assert_axioms MatrixMultiplication.SimplifiedRecursiveChildProfiles.levelThreeCheckedParentTerm_split_counts
