import AxiomAudit.Command
import MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences

/-!
# Axiom audit for labelled level-three occurrences

The audited statements derive the evaluator's symmetrized child rows by pooling two labelled
occurrences through the canonical complement permutation.  They ensure that neither the
symmetrization nor the resulting exact and compatibility-cell tables are trusted inputs.
-/

#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.childRowRescale_eq_levelTwoChildDenominator
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeOccurrenceCoarseIndex_total
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeOccurrenceChildShape_eq_childState
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeOccurrenceCoarseIndex_eq_childState
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeOccurrenceLaw_count_left
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeOccurrenceLaw_count_right
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeRightChildWordCount_eq_left_complementSlot
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeSlotNumerator_complement
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeSymmetrizedSlotWordCount_eq_labelled_occurrence_pair
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeOccurrenceExactCount_eq_sum_symmetrized
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeOccurrenceYPooledCount_eq_sum_symmetrized
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelThreeOccurrences.levelThreeOccurrenceZPooledCount_eq_sum_symmetrized
