/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.SimplifiedRecursiveFiniteFamilies

/-!
# Axiom audit for simplified-recursion family checkers

The audited theorem lifts the proved local level-four checker across the complete finite parent
family.  Generated certificate modules use it as their semantic boundary.
-/

#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourParentFamilyChildRowsValid_of_check
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowKey_normalized_of_check
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowKeysNormalizedCheck_append
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowKeysNormalizedCheck_append_eq_true
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowKeyCoverage_of_check
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowsValid_of_key_coverage
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowsValid_of_keyChecks
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourSlotListChildRowKeyIndexedCoverage_of_check
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourSlotListChildRowKeyIndexedCoverageCheck_append
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourSlotListChildRowKeyIndexedCoverageCheck_append_eq_true
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourCoverageSlotShard_complete
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowKeyIndexedCoverage_of_shards
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowKeyIndexedCoverage_of_check
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowsValid_of_array_key_coverage
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourChildRowsValid_of_indexed_key_check
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourParentListChildRowKeyCoverageCheck_append
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourParentListChildRowKeyCoverageCheck_append_eq_true
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourParentListChildRowKeyCoverage_of_check
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourParentListChildRowsValid_of_keyChecks
#assert_axioms MatrixMultiplication.SimplifiedRecursiveFiniteFamilies.levelFourParentFamilyChildRowsValid_of_keyChecks
