import AxiomAudit.Command
import MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles

/-!
# Axiom audit for exact level-four recursive profiles

The audited bridge reconstructs a depth-three parent profile from normalized depth-two child rows
on the nonzero support of a literal ordered top-split law.  It covers support reindexing, the
proof-free/typed slot lookup, child complement geometry, exact multiplicity, pointwise recurrence,
and evaluator-row normalization.
-/

#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.levelFourActiveSlot_numerator_ne
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.sum_levelFourActiveSlot_numerator
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.pairAt_eq_levelFourPairAtSlot
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.parentShapeAt_eq_positiveLevelFourShape
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.levelThreeWordCountAt_supported
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.levelFourRightChild_evaluatorTotal
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.levelFourLeftChildProfile_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.levelFourRightChildProfile_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.levelFourRecursiveParentTerm_multiplicity
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.levelFourRecursiveParentTerm_split_counts
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.levelFourEvaluatorParentRowsValid_of_childRows
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourProfiles.levelFourCheckedParentTerm_split_counts
