/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity

/-!
# Enforcing audit for structural level-three row validity

These checks cover the finite node/split geometry, coordinate bounds, aggregate dual-weight
positivity, and all singleton, weighted-row, regional, and explicit-node validity endpoints.
They ensure that replacing generated validity reductions by structural mathematics introduces no
placeholder or non-allowlisted axiom dependency.
-/

#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.lt_nodeCount_of_mem_activeNodes
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.levelThreeSplits_length_pos
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.nodeShapeAt_mem_positiveShapes
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.validSlots_ne_nil
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.shapeCoordinate_le_total
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.splitSlotIsValid_of_mem_validSlots
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.splitShapeAt_mem_levelThreeSplits
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.splitShapeAt_total
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.shapeCoordinate_splitShapeAt_lt_coordinateCount
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.dualWeights_forCoordinate_pos
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.localRowsFor_isValid_of_node_lt
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.localRowsFor_isValid_of_node_lt_of_legPos
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.localRows_isValid_of_node_lt
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.weightedLocalRowsFor_rows_isValid_of_node_lt
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.weightedLocalRows_rows_isValid_of_node_lt
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.regionEntriesFor_isValid_of_weights_pos
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.regionEntriesFor_isValid_of_legPos
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.regionEntries_isValid_of_weights_pos
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.regionEntries_isValid_of_legPos
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelThreeStructuralValidity.regionEntriesOnNodesFor_isValid_of_weights_pos
