import AxiomAudit.Command
import MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences

/-!
# Axiom audit for labelled level-four occurrences

These checks cover the complete provenance chain from raw ordered top-split slots to the exact,
`Y`-pooled, and `Z`-pooled compatibility targets consumed by the evaluator.  In particular,
right-child reindexing and self-complementary double occurrences are derived rather than assumed.
-/

#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.validSlots_nodup
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.sum_validSlots_eq_sum_validSlot
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.compatibilityTargets_extensionality
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourOccurrenceCoarseIndex_total
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourOccurrenceChildShape_eq_childState
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourOccurrenceCoarseIndex_eq_childState
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.fixedParentCoarseIndex_eq_levelFourSlotCoarseIndex
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourOccurrenceLaw_count_left
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourOccurrenceLaw_count_right
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.sum_levelFourOccurrenceLaw_count
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourRightChildWordCount_eq_left_complementSlot
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.betaThreeWordNumerator_eq_levelFourLeftChildWordCount
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.pairIndexAt_levelFourComplementSlot
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourSlotNumerator_complement
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.fixedParentSlotCount_eq_labelled_occurrence_pair
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourOccurrenceExactCount_eq_fixedParentExactCount
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourOccurrenceYPooledCount_eq_fixedParentYPooledCount
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourOccurrenceZPooledCount_eq_fixedParentZPooledCount
#assert_axioms MatrixMultiplication.SimplifiedRecursiveLevelFourOccurrences.levelFourOccurrenceTargets_eq_fixedParentCompatibilityTargets
