/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.SimplifiedExponentLevelFourRecurrence

/-!
# Axiom audit for quotient-parametric level-four beta-three reconstruction

The level-four recurrence can reconstruct its depth-three child rows through an arbitrary
quotient slot map.  These assertions keep the generic constructors, the bounded slot and region
folds used by generated checkers, and the historical sorted-pair wrappers inside the enforcing
certificate audit.
-/

#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.betaThreeGlobalNumeratorFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.addBetaThreeRegionContributionFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.betaThreeRegionRowByScatterFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.addBetaThreeRegionSlotFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.betaThreeRegionRowByScatterFirstSlotsFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.betaThreeRegionRowByScatterRemainingSlotsFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.betaThreeRegionRowByScatterFor_eq_slotHalves
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.betaThreeRegionRowByScatterFor_eq_of_slotHalves
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.addPositiveBetaThreeRegionFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.addPositiveBetaThreeRegionFromChildFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.addPositiveBetaThreeRegionFor_eq_fromChildFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.addPositiveBetaThreeRegionFor_eq_of_child
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.positiveBetaThreeCoordinateRowFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.positiveBetaThreeCoordinateFirstHalfFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.positiveBetaThreeCoordinateSecondHalfFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.positiveBetaThreeCoordinateRowFor_eq_halves
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.positiveBetaThreeCoordinateRowFor_eq_of_halves
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.betaThreeGlobalRowFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.betaThreeGlobalRowFor_eq_of_positive
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.reconstructedBetaThreeShapeRowsFor
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.reconstructedBetaThreeShapeRowsFor_eq_of_rows
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.reconstructedBetaThreeRowsFor

#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.betaThreeGlobalNumerator
#assert_axioms MatrixMultiplication.SimplifiedExponentLevelFourRecurrence.reconstructedBetaThreeRows
