import AxiomAudit.Command
import MatrixMultiplication.TotalWeightEventualVolumeLossEndpoint

#assert_axioms MatrixMultiplication.TotalWeightEventualVolumeLossEndpoint.omega_lt_236999_of_eventualStages
#assert_axioms MatrixMultiplication.TotalWeightEventualVolumeLossEndpoint.omega_lt_236999_of_eventualStages_at_floor
