/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThreeOrientation
import MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThreeWeights
import MatrixMultiplication.Generated.TotalQuotientOuterFloorRootWeights

/-!
# Certificate axiom audit for the outer-floor dual witnesses (root and level three)

Covers every public declaration of the `TotalQuotientOuterFloorLevelThree{Orientation,Weights*}` payload of
certificate `e7987d7fa66008d497e31c976c68f025d57664a145336d358328375cc5738ca3`.

Build with

```text
lake build AxiomAuditCertificate
```

Each `#assert_axioms` fails elaboration if its declaration depends on any axiom other than
`propext`, `Classical.choice`, and `Quot.sound`.
-/

#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Orientation.order
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Orientation.order_isPermutation
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region0.rawWeightsMinusOne
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region0.rawWeightsMinusOne_size
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region0.weight
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region0.weight_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region0.dualWeights
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region0.dualWeights_x_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region0.dualWeights_y_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region0.dualWeights_z_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region1.rawWeightsMinusOne
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region1.rawWeightsMinusOne_size
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region1.weight
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region1.weight_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region1.dualWeights
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region1.dualWeights_x_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region1.dualWeights_y_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region1.dualWeights_z_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region2.rawWeightsMinusOne
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region2.rawWeightsMinusOne_size
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region2.weight
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region2.weight_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region2.dualWeights
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region2.dualWeights_x_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region2.dualWeights_y_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region2.dualWeights_z_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region3.rawWeightsMinusOne
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region3.rawWeightsMinusOne_size
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region3.weight
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region3.weight_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region3.dualWeights
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region3.dualWeights_x_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region3.dualWeights_y_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region3.dualWeights_z_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region4.rawWeightsMinusOne
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region4.rawWeightsMinusOne_size
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region4.weight
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region4.weight_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region4.dualWeights
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region4.dualWeights_x_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region4.dualWeights_y_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region4.dualWeights_z_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region5.rawWeightsMinusOne
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region5.rawWeightsMinusOne_size
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region5.weight
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region5.weight_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region5.dualWeights
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region5.dualWeights_x_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region5.dualWeights_y_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.Region5.dualWeights_z_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.rawWeightsMinusOne
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.rawWeightsMinusOne_size
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.weight
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.weight_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.weightX
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.weightY
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.weightZ
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.weightX_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.weightY_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorRoot.Weights.weightZ_pos
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.dualWeights
#assert_axioms MatrixMultiplication.Generated.TotalQuotientOuterFloorLevelThree.Weights.dualWeights_x_pos
