/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AxiomAudit.Command
import MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance

/-!
# Certificate axiom audit for compact level-two provenance

These assertions cover the complete chain from the sparse semantic tables and computed edge
geometry, through all eighteen exact input blocks and their sufficient-statistic grouping, to the
real-valued branch-rate equality.
-/

#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputTables_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.semanticActiveEdges_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk0_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk1_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk2_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk3_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk4_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk5_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk6_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk7_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk8_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk9_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk10_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk11_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk12_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk13_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk14_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk15_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk16_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.inputChunk17_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.semanticRange_eq
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.activeInputChunks_eq_inputChunks
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.activeInputs_eq_inputChunks
#assert_axioms MatrixMultiplication.TotalQuotientExponentLevelTwoGroupedProvenance.activeBranchRate_eq_grouped
