/-
Copyright (c) 2026 Thomas Dybdahl Ahle. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas Dybdahl Ahle
-/

import AlgebraicComplexity.Examples.CoppersmithWinogradRecursiveInputHoleConcentration
import AlgebraicComplexity.Examples.CoppersmithWinogradTotalWeightOccurrenceClients
import AlgebraicComplexity.Probability.ComplementaryOccurrenceCellProjection

set_option autoImplicit false

/-!
# Projection models from recursive occurrence targets

The finite input-hole concentration theorem is stated for an abstract complementary-product
reference.  A recursive occurrence target already contains nearly all of that reference: its
ordered-state profile and its labelled child-symbol tables.  This module normalizes those exact
tables after the bounded coarse-cell quotient.

The resulting adapter proves, rather than assumes, the normalized ordered-state law and the
pooled target law required by concentration.  Two genuinely semantic facts remain visible to a
client: the doubled coarse address must be the occurrence-cell word of its ordered state word,
and concatenating the two child laws must give the prescribed parent complete-split law.  No
cleanup, repair, tensor restriction, or numerical certificate enters here.
-/

namespace AlgebraicComplexity.Examples

open AlgebraicComplexity Tensor MoreAsymmetryCompatibility

universe u v

variable {State : Type u} [Fintype State] [DecidableEq State]
variable {Part : Type v} [Fintype Part] [DecidableEq Part]
variable {depth : ℕ} {profile : State → ℕ}

/-- The bounded cell of the labelled left occurrence generated by an ordered state. -/
def cwRecursiveOccurrenceStateCell
    (depth : ℕ)
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (htotal : ∀ occurrence,
      (coarseOf occurrence).x + (coarseOf occurrence).y +
        (coarseOf occurrence).z = coarseTotal depth)
    (state : State) : CWOrientedCoarseCell Part depth :=
  cwRecursiveOccurrenceFiniteCell depth coarseOf htotal (state, .left)

omit [Fintype State] [DecidableEq State] [Fintype Part] [DecidableEq Part] in
@[simp] theorem cwOrientedCoarseCellToIndex_cwRecursiveOccurrenceStateCell
    (depth : ℕ)
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (htotal : ∀ occurrence,
      (coarseOf occurrence).x + (coarseOf occurrence).y +
        (coarseOf occurrence).z = coarseTotal depth)
    (state : State) :
    cwOrientedCoarseCellToIndex
        (cwRecursiveOccurrenceStateCell depth coarseOf htotal state) =
      coarseOf (state, .left) :=
  cwOrientedCoarseCellToIndex_cwRecursiveOccurrenceFiniteCell
    depth coarseOf htotal (state, .left)

/-- The complementary-product model canonically normalized from one logical-leg occurrence
law. -/
noncomputable def cwRecursiveOccurrenceProjectionModel
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf profile)
    (logicalLeg : Leg) (complement : Equiv.Perm State)
    (htotal : ∀ occurrence,
      (coarseOf occurrence).x + (coarseOf occurrence).y +
        (coarseOf occurrence).z = coarseTotal depth)
    (hmass : 0 < WordType.profileMass profile) :
    ComplementaryProductProjectionModel State
      (CWOrientedCoarseCell Part depth) (SplitWord depth) :=
  (data.law logicalLeg).toCellProductProjectionModel complement
    (cwRecursiveOccurrenceStateCell depth coarseOf htotal) hmass

omit [DecidableEq State] in
@[simp] theorem cwRecursiveOccurrenceProjectionModel_stateLaw_weight
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf profile)
    (logicalLeg : Leg) (complement : Equiv.Perm State)
    (htotal : ∀ occurrence,
      (coarseOf occurrence).x + (coarseOf occurrence).y +
        (coarseOf occurrence).z = coarseTotal depth)
    (hmass : 0 < WordType.profileMass profile) (state : State) :
    (cwRecursiveOccurrenceProjectionModel
      coarseOf data logicalLeg complement htotal hmass).stateLaw.weight state =
      (profile state : ℝ) / WordType.profileMass profile :=
  rfl

omit [Fintype Part] [DecidableEq Part] in
private theorem cwOrientedCoarseCellToIndex_injective_forOccurrenceModel
    {depth : ℕ} :
    Function.Injective (cwOrientedCoarseCellToIndex :
      CWOrientedCoarseCell Part depth → CoarseIndex Part) := by
  rintro ⟨leftPart, left⟩ ⟨rightPart, right⟩ h
  apply Prod.ext
  · exact congrArg CoarseIndex.part h
  · funext logicalLeg
    apply Fin.ext
    cases logicalLeg with
    | X => simpa [cwOrientedCoarseCellToIndex] using congrArg CoarseIndex.x h
    | Y => simpa [cwOrientedCoarseCellToIndex] using congrArg CoarseIndex.y h
    | Z => simpa [cwOrientedCoarseCellToIndex] using congrArg CoarseIndex.z h

omit [DecidableEq State] [Fintype Part] in
/-- Pooling the occurrence package by complement-transported bounded state cells gives exactly
its original exact coarse target table. -/
theorem recursiveOccurrenceExactProfile_eq_cellJointProfile_stateCell
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (law : ComplementaryOccurrenceLaw profile (SplitWord depth))
    (complement : Equiv.Perm State)
    (htotal : ∀ occurrence,
      (coarseOf occurrence).x + (coarseOf occurrence).y +
        (coarseOf occurrence).z = coarseTotal depth)
    (hcoarse : ∀ occurrence,
      coarseOf occurrence =
        coarseOf (occurrence.childState complement, .left))
    (cell : CWOrientedCoarseCell Part depth) (word : SplitWord depth) :
    recursiveOccurrenceExactProfile coarseOf law
        (cwOrientedCoarseCellToIndex cell) word =
      law.cellJointProfile complement
        (cwRecursiveOccurrenceStateCell depth coarseOf htotal) (cell, word) := by
  classical
  unfold recursiveOccurrenceExactProfile recursiveOccurrencePooledProfile
    ComplementaryOccurrenceLaw.cellJointProfile
  apply Finset.sum_congr rfl
  intro occurrence _
  have hcell :
      coarseOf occurrence = cwOrientedCoarseCellToIndex cell ↔
        cwRecursiveOccurrenceStateCell depth coarseOf htotal
            (occurrence.childState complement) = cell := by
    constructor
    · intro hindex
      apply cwOrientedCoarseCellToIndex_injective_forOccurrenceModel
      rw [cwOrientedCoarseCellToIndex_cwRecursiveOccurrenceStateCell,
        ← hcoarse occurrence]
      exact hindex
    · intro hfinite
      calc
        coarseOf occurrence =
            coarseOf (occurrence.childState complement, .left) := hcoarse occurrence
        _ = cwOrientedCoarseCellToIndex
            (cwRecursiveOccurrenceStateCell depth coarseOf htotal
              (occurrence.childState complement)) :=
              (cwOrientedCoarseCellToIndex_cwRecursiveOccurrenceStateCell
                depth coarseOf htotal _).symm
        _ = cwOrientedCoarseCellToIndex cell := congrArg _ hfinite
  by_cases h : coarseOf occurrence = cwOrientedCoarseCellToIndex cell
  · simp [h, hcell.mp h]
  · have hfinite :
        cwRecursiveOccurrenceStateCell depth coarseOf htotal
            (occurrence.childState complement) ≠ cell :=
      fun heq ↦ h (hcell.mpr heq)
    simp [h, hfinite]

omit [DecidableEq State] [Fintype Part] in
private theorem toCompatibilityTargets_exactProfile
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf profile)
    (logicalLeg : Leg) :
    data.toCompatibilityTargets.exactProfile logicalLeg =
      recursiveOccurrenceExactProfile coarseOf (data.law logicalLeg) := by
  cases logicalLeg <;> rfl

/-- The model's pooled reference marginal is the normalized exact target table stored by the
recursive occurrence package. -/
theorem cwRecursiveOccurrenceProjectionModel_targetReference
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf profile)
    (logicalLeg : Leg) (complement : Equiv.Perm State)
    (htotal : ∀ occurrence,
      (coarseOf occurrence).x + (coarseOf occurrence).y +
        (coarseOf occurrence).z = coarseTotal depth)
    (hcoarse : ∀ occurrence,
      coarseOf occurrence =
        coarseOf (occurrence.childState complement, .left))
    (hmass : 0 < WordType.profileMass profile)
    (cell : CWOrientedCoarseCell Part depth) (word : SplitWord depth) :
    let M := cwRecursiveOccurrenceProjectionModel
      coarseOf data logicalLeg complement htotal hmass
    (data.toCompatibilityTargets.exactProfile logicalLeg
          (cwOrientedCoarseCellToIndex cell) word : ℝ) /
        WordType.profileMass profile =
      (M.reference.pushforward M.leftFeature).weight (cell, word) +
        (M.reference.pushforward M.rightFeature).weight (cell, word) := by
  classical
  let M := cwRecursiveOccurrenceProjectionModel
    coarseOf data logicalLeg complement htotal hmass
  have href :=
    (data.law logicalLeg).toCellProductProjectionModel_reference_pooledFeature_weight
      complement (cwRecursiveOccurrenceStateCell depth coarseOf htotal)
        hmass cell word
  have hcount :
      data.toCompatibilityTargets.exactProfile logicalLeg
          (cwOrientedCoarseCellToIndex cell) word =
        (data.law logicalLeg).cellJointProfile complement
          (cwRecursiveOccurrenceStateCell depth coarseOf htotal) (cell, word) :=
    (congrFun (congrFun
      (toCompatibilityTargets_exactProfile coarseOf data logicalLeg)
        (cwOrientedCoarseCellToIndex cell)) word).trans
      (recursiveOccurrenceExactProfile_eq_cellJointProfile_stateCell
        coarseOf (data.law logicalLeg) complement htotal hcoarse cell word)
  calc
    (data.toCompatibilityTargets.exactProfile logicalLeg
          (cwOrientedCoarseCellToIndex cell) word : ℝ) /
        WordType.profileMass profile =
        ((data.law logicalLeg).cellJointProfile complement
            (cwRecursiveOccurrenceStateCell depth coarseOf htotal) (cell, word) : ℝ) /
          WordType.profileMass profile := by rw [hcount]
    _ = (M.reference.pushforward M.leftFeature).weight (cell, word) +
        (M.reference.pushforward M.rightFeature).weight (cell, word) := by
      simpa only [M, cwRecursiveOccurrenceProjectionModel] using href.symm

omit [DecidableEq State] in
/-- An exact ordered-state word realizes the normalized state law of the canonical occurrence
projection model. -/
theorem cwRecursiveOccurrenceProjectionModel_stateReference
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf profile)
    (logicalLeg : Leg) (complement : Equiv.Perm State)
    (htotal : ∀ occurrence,
      (coarseOf occurrence).x + (coarseOf occurrence).y +
        (coarseOf occurrence).z = coarseTotal depth)
    (hmass : 0 < WordType.profileMass profile)
    {n : ℕ} (state : Fin (n + 1) → State)
    (hsource : WordType.multiplicity state = profile) (u : State) :
    ((WordType.multiplicity state u : ℝ) / (n + 1)) =
      (cwRecursiveOccurrenceProjectionModel
        coarseOf data logicalLeg complement htotal hmass).stateLaw.weight u := by
  have hlength : WordType.profileMass profile = n + 1 := by
    calc
      WordType.profileMass profile =
          WordType.profileMass (WordType.multiplicity state) :=
        congrArg WordType.profileMass hsource.symm
      _ = n + 1 := by
        rw [WordType.profileMass, WordType.sum_multiplicity]
  rw [cwRecursiveOccurrenceProjectionModel_stateLaw_weight, hsource, hlength]
  simp only [Nat.cast_add, Nat.cast_one]

omit [DecidableEq State] in
/-- A positive integral profile remains positive after a positive proportional repetition. -/
theorem cwProportionalProfileMass_pos
    (sourceProfile : State → ℕ)
    (hmass : 0 < WordType.profileMass sourceProfile)
    (k : ℕ) (hk : 0 < k) :
    0 < WordType.profileMass (WordType.proportionalCounts sourceProfile k) := by
  simpa [WordType.profileMass, WordType.proportionalCounts, Finset.sum_mul] using
    Nat.mul_pos hmass hk

/-- **Occurrence-package form of recursive input-hole concentration.**  The occurrence package
constructs the projection model and discharges its normalized state and target laws.  The client
retains only the exact ordered-state word carried by the doubled coarse reference and the true
parent complete-split recursion law, in addition to the support premises already required by the
target fiber. -/
theorem card_cwRecursiveInputProfileHoles_le_of_occurrenceTargetData
    {depth n : ℕ}
    (partAt : Fin (n + 1) → Part) (sigma : Orientation)
    (term : ExactInterfaceTermParameters (depth + 1))
    (hmultiplicity : term.multiplicity = n + 1)
    {epsilon : ℝ} (hepsilon : 0 ≤ epsilon)
    (alpha : ExactRecursiveSplitType
      (cwRecursiveLogicalParent term sigma) (coarseTotal depth) (n + 1))
    (sourceProfile : State → ℕ)
    (hmass : 0 < WordType.profileMass sourceProfile)
    (k : ℕ) (hk : 0 < k)
    (coarseOf : ComplementaryOccurrence State → CoarseIndex Part)
    (data : RecursiveOccurrenceTargetData (depth := depth) coarseOf
      (WordType.proportionalCounts sourceProfile k))
    (complement : Equiv.Perm State)
    (htotal : ∀ occurrence,
      (coarseOf occurrence).x + (coarseOf occurrence).y +
        (coarseOf occurrence).z = coarseTotal depth)
    (hcoarse : ∀ occurrence,
      coarseOf occurrence =
        coarseOf (occurrence.childState complement, .left))
    (hsupported : data.toCompatibilityTargets.IsWeightSupported)
    (hcoarseSupported :
      CWRecursiveTargetCoarseTotalSupported data.toCompatibilityTargets)
    (reference : CWRecursiveCoarseAddress depth n)
    (hreference : reference ∈
      cwRecursiveRelaxedAmbientCoarseSupport term sigma alpha)
    (logicalLeg : Leg)
    (state : Fin (n + 1) → State)
    (hsource : WordType.multiplicity state =
      WordType.proportionalCounts sourceProfile k)
    (hsourceCells :
      cwRecursiveOrientedFiniteCellSequence
          depth n partAt sigma reference =
        Fin.append
          (cwRecursiveOccurrenceStateCell depth coarseOf htotal ∘ state)
          (cwRecursiveOccurrenceStateCell depth coarseOf htotal ∘
            complement ∘ state))
    (hparentReference :
      let M := cwRecursiveOccurrenceProjectionModel coarseOf data logicalLeg
        complement htotal (cwProportionalProfileMass_pos sourceProfile hmass k hk)
      M.parentLaw (fun pair ↦ concatSplitWords pair.1 pair.2) =
        ((cwRecursiveSemanticParentTerm term hmultiplicity).split
          (sigma logicalLeg)).probability) :
    let M := cwRecursiveOccurrenceProjectionModel coarseOf data logicalLeg
      complement htotal (cwProportionalProfileMass_pos sourceProfile hmass k hk)
    ((cwRecursiveInputProfileHoles
        partAt sigma term hmultiplicity epsilon data.toCompatibilityTargets reference
          (sigma logicalLeg)).card : ℝ) ≤
      ((((WordType.profileMass sourceProfile * k + 1) ^
          Fintype.card (State × (SplitWord depth × SplitWord depth)) : ℕ) : ℝ)) *
        WordType.structuralZeroMultinomialLoss sourceProfile k *
          Real.exp (((k : ℝ) * WordType.profileMass sourceProfile) *
            (M.reference.conditionalEntropy M.coarse - epsilon ^ 2 / 4)) := by
  let hscaledMass := cwProportionalProfileMass_pos sourceProfile hmass k hk
  let M := cwRecursiveOccurrenceProjectionModel
    coarseOf data logicalLeg complement htotal hscaledMass
  have hlength :
      WordType.profileMass (WordType.proportionalCounts sourceProfile k) = n + 1 := by
    calc
      WordType.profileMass (WordType.proportionalCounts sourceProfile k) =
          WordType.profileMass (WordType.multiplicity state) :=
        congrArg WordType.profileMass hsource.symm
      _ = n + 1 := by
        rw [WordType.profileMass, WordType.sum_multiplicity]
  apply card_cwRecursiveInputProfileHoles_le
    partAt sigma term hmultiplicity hepsilon alpha data.toCompatibilityTargets
      hsupported hcoarseSupported reference hreference logicalLeg M state
        sourceProfile hmass k hk hsource
  · simpa only [M, cwRecursiveOccurrenceProjectionModel,
      ComplementaryOccurrenceLaw.toCellProductProjectionModel_cellOf,
      ComplementaryOccurrenceLaw.toCellProductProjectionModel_complement,
      Function.comp_def] using hsourceCells
  · intro u
    exact cwRecursiveOccurrenceProjectionModel_stateReference
      coarseOf data logicalLeg complement htotal hscaledMass state hsource u
  · intro cell word
    have htarget := cwRecursiveOccurrenceProjectionModel_targetReference
      coarseOf data logicalLeg complement htotal hcoarse hscaledMass cell word
    rw [hlength] at htarget
    simpa only [M, Nat.cast_add, Nat.cast_one] using htarget
  · simpa only [M, hscaledMass] using hparentReference

end AlgebraicComplexity.Examples
